Repository scala/scala, pull requests merged in 2018-06, with the labels that each got.

#6599 More allocation cleanup in the pattern matcher
  src/compiler/scala/tools/nsc/transform/patmat/Logic.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala
  src/compiler/scala/tools/nsc/transform/patmat/PatternMatching.scala
Labels: performance

#6195 Fix for SI-9881 in branch 2.11.x
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/reflect/scala/reflect/internal/Names.scala
  src/repl/scala/tools/nsc/interpreter/ExprTyper.scala
  src/repl/scala/tools/nsc/interpreter/MemberHandlers.scala
  test/files/run/t9880-9881.check
  test/files/run/t9880-9881.scala
  test/junit/scala/reflect/internal/NamesTest.scala
Labels: WIP

#6631 Reducing the footprint of Context
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: performance

#6315 Deprecate scala.Predef.any2stringadd
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/library/scala/Predef.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/jvm/future-spec/FutureTests.scala
  test/files/jvm/future-spec/main.scala
  test/files/neg/implicit-any2stringadd-warning.check
  test/files/neg/implicit-any2stringadd-warning.flags
  test/files/neg/implicit-any2stringadd-warning.scala
  test/files/neg/implicit-any2stringadd.check
  test/files/neg/implicit-any2stringadd.flags
  test/files/neg/implicit-any2stringadd.scala
  test/files/run/collection-stacks.scala
  test/files/run/colltest1.scala
  test/files/run/compiler-asSeenFrom.scala
  test/files/run/equality.scala
  test/files/run/fail-non-value-types.scala
  test/files/run/macroPlugins-enterStats.flags
  test/files/run/macroPlugins-enterStats.scala
  test/files/run/mixin-signatures.scala
  test/files/run/no-pickle-skolems/Test_2.scala
  test/files/run/patmat-exprs.flags
  test/files/run/patmat-exprs.scala
  test/files/run/range.scala
  test/files/run/reflection-magicsymbols-invoke.scala
  test/files/run/reflection-valueclasses-magic.flags
  test/files/run/reflection-valueclasses-magic.scala
  test/files/run/repl-no-imports-no-predef.check
  test/files/run/repl-no-imports-no-predef.scala
  test/files/run/t10551.scala
  test/files/run/t1195-new.scala
  test/files/run/t1931.check
  test/files/run/t4027.scala
  test/files/run/t4122.scala
  test/files/run/t6731.flags
  test/files/run/t6731.scala
  test/files/run/virtpatmat_typetag.scala
  test/junit/scala/tools/nsc/backend/jvm/StringConcatTest.scala
  test/scaladoc/run/implicits-known-type-classes.scala
  test/scaladoc/run/macro_annot.scala
  test/scaladoc/run/t3314.flags
  test/scaladoc/run/t3314.scala
  test/scaladoc/run/t5235.scala
  test/scaladoc/run/t5784.scala
  test/scaladoc/run/t6509.scala
Labels: release-notes

#6723 Upgrade benchmarks to the latest version of JMH
  project/plugins.sbt
Labels: performance

#6750 Bring back List filter/filterNot optimization to 2.13
  src/library/scala/collection/immutable/List.scala
Labels: performance

#6485 Stop passing null to extractor pattern [ci: last-only]
  spec/08-pattern-matching.md
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala
  src/library/scala/Array.scala
  src/library/scala/util/matching/Regex.scala
  test/files/run/name-based-patmat.check
  test/files/run/patmatnew.check
  test/files/run/patmatnew.flags
  test/files/run/patmatnew.scala
  test/files/run/t6288.check
  test/files/run/t6288.scala
  test/files/run/t7039.check
  test/files/run/t7039.scala
  test/files/run/t9349/test.scala
  test/junit/scala/util/matching/RegexTest.scala
Labels: release-notes

#6598 Optimize patmat analysis
  src/compiler/scala/tools/nsc/transform/patmat/Logic.scala
  src/compiler/scala/tools/nsc/transform/patmat/Solving.scala
Labels: performance

#6761 Add string interpolation to specification.
  spec/01-lexical-syntax.md
  spec/08-pattern-matching.md
  spec/13-syntax-summary.md
Labels: welcome

#6814 Avoid Some boxing in the backend's BType cache
  src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromClassfile.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala
Labels: performance

#6815 Reduce allocations when gathering inner classes
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  test/junit/scala/tools/nsc/backend/jvm/NestedClassesCollectorTest.scala
Labels: performance

#6810 Micro optimization in specialization
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
Labels: performance

#6848 Minor optimizations in implicit search.
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Labels: performance

#6844 It corrects the return type by the implicit conversion from Seq[T] to Seq[Source]
  src/library/scala/sys/process/Process.scala
  test/junit/scala/sys/process/ProcessTest.scala
Labels: welcome

#6866 makes Iterable.scan and IterableOnce.fold deprecated.
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/IterableOnce.scala
Labels: welcome

#6733 Upgrade to scala-asm 6.2
  src/compiler/scala/tools/asm/LabelAccess.java
  src/compiler/scala/tools/nsc/backend/jvm/AsmUtils.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeSkelBuilder.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala
  src/compiler/scala/tools/nsc/backend/jvm/ClassNode1.java
  src/compiler/scala/tools/nsc/backend/jvm/LabelNode1.java
  src/compiler/scala/tools/nsc/backend/jvm/MethodNode1.java
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/ProdConsAnalyzerImpl.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/TypeFlowInterpreter.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/BytecodeUtils.scala
  src/partest/scala/tools/partest/nest/StreamCapture.scala
  test/benchmarks/src/main/scala/scala/tools/nsc/backend/jvm/ProdConsBenchmark.scala
  test/junit/scala/tools/nsc/backend/jvm/opt/InlinerTest.scala
  test/junit/scala/tools/testing/BytecodeTesting.scala
  versions.properties
Labels: performance
