Repository scala/scala, pull requests merged in 2018-04, with the labels that each got.

#6324 Remove octal escape literals
  spec/01-lexical-syntax.md
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/compiler/scala/tools/reflect/FormatInterpolator.scala
  src/library/scala/StringContext.scala
  test/files/neg/t7292-deprecation.check
  test/files/neg/t7292-deprecation.flags
  test/files/neg/t7292-deprecation.scala
  test/files/neg/t7292-removal.check
  test/files/neg/t7292-removal.flags
  test/files/run/literals.check
  test/files/run/literals.scala
  test/files/run/richs.check
  test/files/run/richs.scala
  test/files/run/t8266-octal-interp.check
  test/files/run/t8266-octal-interp.flags
  test/files/run/t8266-octal-interp.scala
  test/junit/scala/lang/stringinterpol/StringContextTest.scala
Labels: release-notes, reviewed

#6491 Define zip on Option
  src/library/scala/Option.scala
  test/junit/scala/OptionTest.scala
Labels: release-notes

#6149 Check bounds on implicit macro applications
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  test/files/pos/macro-bounds-check/MacroImpl_1.scala
  test/files/pos/macro-bounds-check/TestLate_2.scala
Labels: WIP

#6521 Add Regex.matches
  src/library/scala/util/matching/Regex.scala
  test/junit/scala/util/matching/RegexTest.scala
Labels: release-notes
