Repository scala/scala, pull requests merged in 2018-02, with the labels that each got.

#6317 Removed -Yliteral-types option and cleaned up docs
  project/ScalaOptionParser.scala
  src/library/scala/Predef.scala
  src/library/scala/ValueOf.scala
  test/files/pos/t6574.scala
  test/files/pos/t6891.scala
Labels: reviewed, welcome

#6105 Avoid repr call in ArrayOps
  src/library/scala/collection/mutable/ArrayOps.scala
  test/benchmarks/src/main/scala/scala/collection/mutable/ArrayOpsBenchmark.scala
Labels: WIP

#6093 Intrinsfy raw and s String interpolators
  src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeIdiomatic.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/library/scala/StringContext.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  src/reflect/scala/reflect/internal/TreeInfo.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/neg/string-context-refchecked.check
  test/files/neg/string-context-refchecked.scala
  test/junit/scala/tools/nsc/backend/jvm/StringConcatTest.scala
Labels: release-notes

#6171 Backport of fix to 10587
  src/library/mima-filters/2.12.0.backwards.excludes
  src/library/scala/concurrent/impl/ExecutionContextImpl.scala
  test/files/jvm/scala-concurrent-tck.scala
Labels: prio:blocker
