Repository scala/scala, pull requests merged in 2018-03, with the labels that each got.

#6249 Make Typer#dyna.mkInvoke more accurate
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/neg/applydynamic_sip.check
  test/files/pos/t7420.scala
Labels: welcome

#6377 Disable parallelism in the scalacheck suite
  build.sbt
Labels: prio:blocker

#6359 Report an error when using an unstable qualifier in a type selection
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/neg/t10619.check
  test/files/neg/t10619.scala
Labels: prio:blocker

#6380 Correctly synthesize `manifest[T]` when `T` is an alias
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  test/files/pos/t9155.scala
Labels: prio:blocker

#6326 threadsafe simple stats
  src/reflect/scala/reflect/internal/util/Statistics.scala
Labels: performance, prio:blocker

#6390 Move to Travis CI for building releases/nightlies
  .travis.yml
  admin/files/credentials-private-repo
  admin/files/credentials-sonatype
  admin/files/gpg.sbt
  admin/files/gpg_subkey.enc
  admin/files/m2-settings.xml
  admin/files/sonatype-curl
  admin/init.sh
  build.sbt
  project/ScriptCommands.scala
  scripts/bootstrap_fun
  scripts/common
  scripts/jobs/integrate/bootstrap
  scripts/jobs/integrate/ide
  scripts/jobs/integrate/windows
  scripts/jobs/validate/publish-core
  scripts/jobs/validate/test
Labels: prio:blocker

#6404 `qual` is used in `qual.withFilter(fun)`, but `fun` is exempt
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
  src/reflect/scala/reflect/internal/StdAttachments.scala
  src/reflect/scala/reflect/internal/TreeGen.scala
  test/files/pos/t10763.flags
  test/files/pos/t10763.scala
Labels: prio:blocker

#6395 Add Automatic-Module-Name attribute to library, reflect, compiler
  build.sbt
  project/AutomaticModuleName.scala
Labels: prio:blocker

#6362 JEP-238 (Multi-Release JAR) and JEP-247 (Compiler for older JDKs) support
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/compiler/scala/tools/nsc/classpath/FileUtils.scala
  src/compiler/scala/tools/nsc/classpath/PackageNameUtils.scala
  src/compiler/scala/tools/nsc/classpath/ZipAndJarFileLookupFactory.scala
  src/compiler/scala/tools/nsc/classpath/ZipArchiveFileLookup.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/util/PathResolver.scala
  src/reflect/mima-filters/2.12.0.forwards.excludes
  src/reflect/scala/reflect/internal/JDK9Reflectors.java
  src/reflect/scala/reflect/io/ZipArchive.scala
  test/junit/scala/tools/nsc/classpath/JrtClassPathTest.scala
  test/junit/scala/tools/nsc/classpath/MultiReleaseJarTest.scala
Labels: prio:blocker

#6400 Handle escaping characters in URL -> file
  src/reflect/scala/reflect/io/AbstractFile.scala
  test/junit/scala/reflect/io/AbstractFileSpec.scala
Labels: prio:blocker

#6412 Disable macro/plugin class loader caching, by default
  src/compiler/scala/tools/nsc/plugins/Plugins.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/typechecker/Macros.scala
Labels: release-notes

#6177 Adapt method values more cannily
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/TreeBuilder.scala
  src/compiler/scala/tools/nsc/typechecker/StdAttachments.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/Trees.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/neg/t10279.check
  test/files/neg/t10279.scala
  test/files/neg/t7187.check
  test/files/neg/t7187.scala
  test/files/run/byname.check
Labels: prio:blocker, release-notes

#6422 verify that ~/.credentials is not a directory
  build.sbt
Labels: welcome

#6292 Refactor typechecking of array instantiation for performance
  src/compiler/scala/tools/nsc/ast/TreeInfo.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: performance

#6386 Bring back List filter/filterNot optimization to 2.13
  src/library/scala/collection/immutable/List.scala
Labels: performance

#6297 Avoid creation of temporary Lists of imports during Context.lookup
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
Labels: performance

#6446 Don't compute `locations` in macroclassloader cache
  src/compiler/scala/tools/nsc/typechecker/Macros.scala
Labels: prio:blocker
