Repository scala/scala, pull requests merged in 2018-11, with the labels that each got.

#7386 override ListBuffer.last/lastOption to run in O(1)
  src/library/scala/collection/mutable/ListBuffer.scala
Labels: performance

#6831 Make postfixOps syntax an error (not just a warning) unless the feature is explicitly enabled [ci: last-only]
  src/library/scala/languageFeature.scala
  src/partest/scala/tools/partest/CompilerTest.scala
  src/partest/scala/tools/partest/TestKinds.scala
  src/partest/scala/tools/partest/nest/AbstractRunner.scala
  src/partest/scala/tools/partest/nest/PathSettings.scala
  src/partest/scala/tools/partest/nest/Runner.scala
  src/partest/scala/tools/partest/package.scala
  test/files/neg/double-feature.check
  test/files/neg/double-feature.scala
  test/files/neg/post-postfix.check
  test/files/neg/post-postfix.scala
  test/files/neg/t5675.scala
  test/files/neg/t6120.check
  test/files/neg/t6120.scala
  test/files/pos/post-postfix.scala
  test/files/pos/t8223.scala
  test/files/pos/tcpoly_infer_explicit_tuple_wrapper.scala
  test/files/pos/tcpoly_infer_implicit_tuple_wrapper.scala
  test/files/pos/tcpoly_infer_ticket716.scala
  test/junit/scala/collection/generic/DecoratorsTest.scala
  test/junit/scala/tools/nsc/reporters/PositionFilterTest.scala
Labels: prio:blocker, release-notes

#7390 Correcting the behavior of Try.recoverWith (#11242)
  src/library/scala/util/Try.scala
  test/files/jvm/try-type-tests.scala
Labels: regression

#7360 Define unzip and unzip3 for Option
  src/library/scala/Option.scala
  test/junit/scala/OptionTest.scala
Labels: welcome

#7272 Tiny standard library tweaks for Dotty compatibility
  src/library/scala/collection/immutable/Range.scala
  src/library/scala/collection/immutable/Seq.scala
Labels: collections

#7383 No static forwarders for bridges implementing abstract methods
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: release-notes

#7445 Optimizing the implementation of DefaultPromise.submitWithValue
  src/library/scala/concurrent/impl/Promise.scala
Labels: performance

#7443 LinearSeq extension problem solved
  src/library/scala/collection/LinearSeq.scala
  test/junit/scala/collection/LinearSeqTest.scala
Labels: collections

#7114 Making VectorIterator a final class
  src/library/scala/collection/immutable/Vector.scala
Labels: collections, performance

#7116 Add, move, and tidy up scaladoc variables around collections
  src/library/scala/collection/ArrayOps.scala
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/Iterator.scala
  src/library/scala/collection/LazyZipOps.scala
  src/library/scala/collection/StringOps.scala
Labels: collections

#7351 Fix inference bug involving nullary methods
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/neg/t9093.check
  test/files/pos/t11052.scala
Labels: regression
