Repository scala/scala, pull requests merged in 2018-08, with the labels that each got.

#6990 Microopts in Definitions and other hot Symbol comparison
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/transform/Erasure.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
Labels: performance

#6864 Remove scala.Symbol literal singleton types
  src/compiler/scala/reflect/reify/phases/Reify.scala
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
  src/compiler/scala/tools/nsc/backend/jvm/CoreBTypes.scala
  src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/reflect/scala/reflect/api/StandardLiftables.scala
  src/reflect/scala/reflect/internal/AnnotationInfos.scala
  src/reflect/scala/reflect/internal/Constants.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/pickling/PickleFormat.scala
  src/reflect/scala/reflect/internal/pickling/UnPickler.scala
  src/reflect/scala/reflect/internal/transform/Erasure.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/instrumented/indy-symbol-literal.scala
  test/files/neg/sip23-symbols.check
  test/files/neg/sip23-symbols.scala
  test/files/pos/sip23-narrow-no-empty-refinements.scala
  test/files/pos/sip23-narrow.scala
  test/files/pos/sip23-singleton-sub.scala
  test/files/pos/sip23-symbols.scala
  test/files/run/sip23-cast-1.scala
  test/files/run/sip23-rangepos.scala
  test/files/run/sip23-valueof.scala
  test/files/run/t6549.check
Labels: prio:blocker

#6854 Add SeqMap/VectorMap
  src/library/scala/collection/immutable/ListMap.scala
  src/library/scala/collection/immutable/SeqMap.scala
  src/library/scala/collection/immutable/VectorMap.scala
  src/library/scala/collection/mutable/LinkedHashMap.scala
  src/library/scala/collection/mutable/SeqMap.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/SeqMapBenchmark.scala
  test/scalacheck/SeqMap.scala
Labels: prio:blocker, release-notes

#7010 Work around a local type inference limitation (fixes the build)
  src/library/scala/collection/immutable/SeqMap.scala
Labels: prio:blocker

#7009 Merge 2.12 to 2.13 aug 7 [ci: last-only]
  build.sbt
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/ast/parser/SyntaxAnalyzer.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/typechecker/Analyzer.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/interactive/scala/tools/nsc/interactive/ContextTrees.scala
  src/library/scala/Enumeration.scala
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  src/reflect/scala/reflect/internal/AnnotationInfos.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/Positions.scala
  src/reflect/scala/reflect/internal/Trees.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/runtime/JavaMirrors.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/neg/t9529.check
  test/files/neg/t9529.scala
  test/files/pos/annotations.scala
  test/files/pos/attributes.scala
  test/files/pos/t10858.scala
  test/files/pos/t11020.scala
  test/files/run/reify_ann1b.check
  test/files/run/reify_ann1b.scala
  test/files/run/t10487.scala
  test/files/run/t4700.check
  test/files/run/t4700.scala
  test/files/run/t9529-types.check
  test/files/run/t9529-types/Test_1.scala
  test/files/run/t9529-types/TypeAnn_0.java
  test/files/run/t9529.check
  test/files/run/t9529/Ann_0.java
  test/files/run/t9529/Test_1.scala
  test/junit/scala/collection/immutable/HashMapTest.scala
  test/junit/scala/reflect/internal/PositionsTest.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
  test/junit/scala/tools/nsc/symtab/SymbolTableForUnitTesting.scala
Labels: prio:blocker

#6499 Support JEP 293 style long command-line options
  src/compiler/scala/tools/nsc/GenericRunnerSettings.scala
  src/compiler/scala/tools/nsc/fsc/FscSettings.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/scaladoc/scala/tools/nsc/doc/Settings.scala
Labels: release-notes

#6972 Product element name
  src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala
  src/library/scala/Product.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/run/idempotency-case-classes.check
  test/files/run/macroPlugins-namerHooks.check
  test/files/run/productElementName.check
  test/files/run/productElementName.scala
  test/files/scalap/caseClass.check
  test/files/scalap/caseObject.check
  test/junit/scala/SerializationStabilityTest.scala
  test/scaladoc/run/implicits-chaining.scala
Labels: release-notes

#7012 Speed up implicit resolution by avoiding allocations when traversing TypeRefs in core
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Labels: performance

#6682 deprecate either projections
  src/library/scala/util/Either.scala
Labels: release-notes

#7007 Adds tap and pipe
  src/library/scala/util/ChainingOps.scala
  src/library/scala/util/package.scala
  test/junit/scala/util/ChainingOpsTest.scala
Labels: release-notes

#7014 [#10919] Deprecate Map.{filterKeys,mapValues} while undeprecating those in MapView
  src/compiler/scala/reflect/reify/utils/SymbolTables.scala
  src/compiler/scala/tools/nsc/symtab/SymbolTrackers.scala
  src/compiler/scala/tools/nsc/transform/Mixin.scala
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/library/scala/collection/ArrayOps.scala
  src/library/scala/collection/Map.scala
  src/library/scala/collection/MapView.scala
  src/library/scala/collection/StringOps.scala
  src/library/scala/collection/concurrent/TrieMap.scala
  src/library/scala/concurrent/duration/Duration.scala
  src/reflect/scala/reflect/internal/Mode.scala
  src/reflect/scala/reflect/internal/util/TraceSymbolActivity.scala
  src/repl/scala/tools/nsc/interpreter/Power.scala
  src/scaladoc/scala/tools/nsc/doc/base/CommentFactoryBase.scala
  test/files/run/analyzerPlugins.scala
  test/files/run/colltest1.scala
  test/files/run/iterator-from.scala
  test/files/run/mapValues.scala
  test/files/run/t3984.scala
  test/files/run/t4027.scala
  test/files/run/t4954.scala
  test/junit/scala/collection/SetMapConsistencyTest.scala
  test/junit/scala/collection/ViewTest.scala
  test/junit/scala/collection/concurrent/TrieMapTest.scala
  test/junit/scala/collection/immutable/SerializationTest.scala
  test/scalacheck/scala/collection/mutable/MutableTreeMap.scala
Labels: prio:blocker, release-notes

#6580 Prune polymorphic implicits more aggressively
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  test/files/neg/sortedImplicitNotFound.check
  test/files/pos/prune-poly-bound.scala
  test/files/pos/prune-poly-f-bounded-view.scala
  test/files/pos/prune-poly-infer-nothing.scala
  test/files/pos/prune-poly-view.scala
Labels: performance

#7000 Make LazyList fully lazy
  src/library/scala/collection/LinearSeq.scala
  src/library/scala/collection/immutable/LazyList.scala
  src/library/scala/collection/immutable/Stream.scala
  test/files/jvm/serialization-new.check
  test/files/jvm/serialization.check
  test/files/run/infiniteloop.check
  test/files/run/lazylist-dropwhile-stack-safe.check
  test/files/run/lazylist-dropwhile-stack-safe.scala
  test/files/run/patmatnew.scala
  test/files/run/serialize-stream.check
  test/files/run/streams.check
  test/files/run/t9174.check
  test/files/run/t9174.scala
  test/files/run/t9219.check
  test/files/run/unapply.scala
  test/files/run/view-iterator-stream.check
  test/junit/scala/collection/immutable/LazyListTest.scala
  test/scalacheck/scala/collection/IndexOfSliceTest.scala
Labels: prio:blocker, release-notes

#6970 Copy arrays that are explicitly passed as varargs with `: _*`
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/run/adding-growing-set.scala
  test/files/run/t11042.check
  test/files/run/t11042.flags
  test/files/run/t11042.scala
  test/files/run/t6611.check
  test/files/run/t9567c.check
Labels: prio:blocker, release-notes

#7031 Add deprecated members `++:` and `repr` to `Iterable`
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/Seq.scala
  test/junit/scala/collection/IterableTest.scala
Labels: WIP

#6975 Cache full key hash codes in ChampMap
  src/library/scala/collection/immutable/ChampCommon.scala
  src/library/scala/collection/immutable/ChampHashMap.scala
  src/library/scala/collection/immutable/ChampHashSet.scala
  test/junit/scala/collection/immutable/ChampMapSmokeTest.scala
  test/junit/scala/collection/immutable/ChampSetSmokeTest.scala
Labels: performance, prio:blocker

#6907 Add utility for automatic resource management
  src/library/scala/util/Using.scala
  test/junit/scala/util/UsingTest.scala
Labels: release-notes

#7017 Add java varargs forwarders to mirror classes
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  test/files/jvm/varargs.check
  test/files/jvm/varargs/JavaClass.java
  test/files/jvm/varargs/VaClass.scala
Labels: prio:blocker

#7028 Mixin fields with trait setters shouldn't be JVM final
  src/compiler/scala/tools/nsc/transform/Constructors.scala
  src/compiler/scala/tools/nsc/transform/Fields.scala
  src/library/scala/runtime/ScalaRunTime.scala
  src/library/scala/runtime/VM.java
  src/reflect/scala/reflect/internal/StdAttachments.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/run/lazy-locals-2.scala
  test/files/run/t10075b.check
  test/jcstress/.gitignore
  test/jcstress/build.sbt
  test/jcstress/project/build.properties
  test/jcstress/project/plugins.sbt
  test/jcstress/src/test/scala/example/APISample_01_Simple.scala
  test/jcstress/src/test/scala/scala/collection/immutable/ListLikeStressTest.scala
  test/jcstress/src/test/scala/scala/collection/immutable/ListStressTest.scala
Labels: prio:blocker, release-notes

#7088 Revert PR 7006
  src/library/scala/collection/BuildFrom.scala
  test/junit/scala/collection/BuildFromTest.scala
  test/junit/scala/collection/IterableOnceTest.scala
Labels: prio:blocker

#6674 Add support for Views to IsIterableLike
  src/library/scala/collection/Searching.scala
  src/library/scala/collection/generic/IsIterable.scala
  src/library/scala/collection/generic/IsIterableLike.scala
  src/library/scala/collection/generic/IsIterableOnce.scala
  src/library/scala/collection/generic/IsMap.scala
  src/library/scala/collection/generic/IsSeq.scala
  src/library/scala/collection/generic/IsSeqLike.scala
  src/library/scala/collection/generic/package.scala
  src/library/scala/runtime/ScalaRunTime.scala
  test/files/run/enrich-gentraversable.check
  test/files/run/enrich-gentraversable.scala
  test/junit/scala/collection/generic/DecoratorsTest.scala
Labels: prio:blocker

#6425 Use a releaseFence after mutation of List, Vector
  src/compiler/scala/tools/nsc/transform/Constructors.scala
  src/library/scala/collection/immutable/List.scala
  src/library/scala/collection/immutable/Vector.scala
  src/library/scala/collection/mutable/ListBuffer.scala
  src/library/scala/runtime/ScalaRunTime.scala
  src/library/scala/runtime/Statics.java
  src/library/scala/runtime/VM.java
  src/reflect/scala/reflect/internal/tpe/FindMembers.scala
  src/reflect/scala/reflect/internal/util/Collections.scala
Labels: prio:blocker, release-notes

#7104 Avoid SeqFactory.unapplySeq in hot pattern matches.
  src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
  src/compiler/scala/tools/nsc/transform/CleanUp.scala
Labels: performance

#7107 Avoid expensive call to `imports` in implicit search
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
Labels: performance

#7068 Explicitly call `toSeq` on wildcard-star patterns
  src/compiler/scala/tools/nsc/transform/patmat/MatchCodeGen.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala
  src/compiler/scala/tools/nsc/transform/patmat/PatternExpansion.scala
  src/library/scala/Array.scala
  src/library/scala/collection/Factory.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/neg/patmat-seq-neg.check
  test/files/neg/patmat-seq-neg.scala
  test/files/run/macro-expand-unapply-a/Impls_Macros_1.scala
  test/files/run/patmat-seq.check
  test/files/run/patmat-seq.scala
  test/files/run/string-extractor.scala
  test/files/run/value-class-extractor-seq.check
  test/files/run/value-class-extractor-seq.scala
Labels: prio:blocker, release-notes

#6965 Small change: remove call to List.reverse.
  src/reflect/scala/reflect/internal/Types.scala
Labels: performance

#7109 A pocketful of micro optimizations
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/Names.scala
  src/reflect/scala/reflect/internal/Scopes.scala
  src/reflect/scala/reflect/internal/SymbolTable.scala
  src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
Labels: performance

#7035 Emit bridge method forwarders with BRIDGE flag
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: prio:blocker

#7097 Optimize caseFieldAccessors to avoid temporary object creation
  src/reflect/scala/reflect/internal/Symbols.scala
Labels: performance

#7096 Optimize MethodType.resultType
  src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
Labels: performance

#7105 Remove some indirections in Global and Typer
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/typechecker/Analyzer.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/nsc/typechecker/TypersTracking.scala
Labels: performance

#7115 Changing s.c.i.Vector.iterator to return Iterator.empty on empty
  src/library/scala/collection/immutable/Vector.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: performance

#7119 Separate compilation of inferred type constructors should not crash asSeenFrom (nor cause spurious recompilation)
  src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala
  src/compiler/scala/tools/nsc/typechecker/PatternTypers.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/Types.scala
  test/files/neg/hk-typevar-unification.check
  test/files/pos/t10762/t10762_1.scala
  test/files/pos/t10762/t10762_2.scala
  test/files/pos/t11103.scala
Labels: prio:blocker, regression

#7142 Add UpperBound and LowerBound methods to Type
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/ExistentialsAndSkolems.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
  src/reflect/scala/reflect/internal/tpe/TypeComparers.scala
  src/reflect/scala/reflect/internal/tpe/TypeConstraints.scala
  src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactoryTypeSupport.scala
Labels: performance

#7091 fix performance regression in mutable.HashMap#getOrElseUpdate
  src/library/scala/collection/mutable/HashMap.scala
Labels: prio:blocker

#7143 Optimize TypeRef.equals with fast paths for eq elements
  src/reflect/scala/reflect/internal/Types.scala
Labels: performance

#7128 Avoid temporary strings during classpath lookup
  src/compiler/scala/tools/nsc/classpath/ZipArchiveFileLookup.scala
  src/reflect/scala/reflect/io/ZipArchive.scala
Labels: performance

#7137 Don't re-apply type maps to info of unchanged symbols
  src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
Labels: performance

#7134 Quick fix for VectorMap
  src/library/scala/collection/immutable/VectorMap.scala
  test/scalacheck/scala/collection/immutable/VectorMapProperties.scala
Labels: prio:blocker
