Repository scala/scala, pull requests merged in 2019-03, with the labels that each got.

#7780 [backport] upgrade to ASM 7
  src/compiler/scala/tools/nsc/backend/jvm/PostProcessor.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/NullnessAnalyzer.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/ProdConsAnalyzerImpl.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/TypeFlowInterpreter.scala
  test/files/run/large_class.check
  test/files/run/large_code.check
  versions.properties
Labels: release-notes

#7712 Experimental support for build pipelining [ci: last-only]
  src/compiler/scala/reflect/macros/runtime/MacroRuntimes.scala
  src/compiler/scala/tools/nsc/CloseableRegistry.scala
  src/compiler/scala/tools/nsc/CompilationUnits.scala
  src/compiler/scala/tools/nsc/GenericRunnerSettings.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/PickleExtractor.scala
  src/compiler/scala/tools/nsc/PipelineMain.scala
  src/compiler/scala/tools/nsc/backend/JavaPlatform.scala
  src/compiler/scala/tools/nsc/classpath/ClassPathFactory.scala
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/compiler/scala/tools/nsc/classpath/FileUtils.scala
  src/compiler/scala/tools/nsc/classpath/VirtualDirectoryClassPath.scala
  src/compiler/scala/tools/nsc/classpath/ZipAndJarFileLookupFactory.scala
  src/compiler/scala/tools/nsc/classpath/ZipArchiveFileLookup.scala
  src/compiler/scala/tools/nsc/plugins/Plugin.scala
  src/compiler/scala/tools/nsc/plugins/Plugins.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/symtab/classfile/AbstractFileReader.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala
  src/compiler/scala/tools/nsc/typechecker/Macros.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/reflect/ReflectGlobal.scala
  src/compiler/scala/tools/reflect/ReflectMain.scala
  src/compiler/scala/tools/util/PathResolver.scala
  src/partest-extras/scala/tools/partest/BytecodeTest.scala
  src/reflect/mima-filters/2.12.0.backwards.excludes
  src/reflect/mima-filters/2.12.0.forwards.excludes
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/SymbolTable.scala
  src/reflect/scala/reflect/internal/pickling/UnPickler.scala
  src/reflect/scala/reflect/io/RootPath.scala
  src/reflect/scala/reflect/io/ZipArchive.scala
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
  src/repl/scala/tools/nsc/interpreter/ReplGlobal.scala
  src/scalap/scala/tools/scalap/Main.scala
  test/junit/scala/tools/nsc/GlobalCustomizeClassloaderTest.scala
  test/junit/scala/tools/nsc/classpath/JrtClassPathTest.scala
  test/junit/scala/tools/nsc/classpath/PathResolverBaseTest.scala
  test/junit/scala/tools/nsc/classpath/ZipAndJarFileLookupFactoryTest.scala
  test/junit/scala/tools/nsc/symtab/SymbolTableForUnitTesting.scala
Labels: release-notes

#7520 mutable and immutable HashMaps and HashSets cooperate in addAll/subtractAll/concat/removedAll by sharing hashcodes
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
  src/library/scala/collection/mutable/HashMap.scala
  src/library/scala/collection/mutable/HashSet.scala
  test/scalacheck/scala/collection/immutable/BitSetProperties.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashMapProperties.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashSetProperties.scala
  test/scalacheck/scala/collection/mutable/HashMapProperties.scala
  test/scalacheck/scala/collection/mutable/HashSetProperties.scala
Labels: collections, performance, prio:blocker, prio:hi

#7802 Remove usesMutableState from ScalaDocs
  src/library/scala/collection/immutable/Iterable.scala
  src/library/scala/collection/immutable/List.scala
  src/library/scala/collection/immutable/Vector.scala
Labels: collections, documentation, welcome

#7818 Override List.last
  src/library/scala/collection/immutable/List.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/Types.scala
Labels: performance

#7632 Mutable RedBlackTree improvements, tests & benchmarks
  src/library/scala/collection/mutable/RedBlackTree.scala
  src/library/scala/collection/mutable/TreeSet.scala
  test/benchmarks/src/main/scala/scala/collection/mutable/RedBlackTreeBenchmark.scala
  test/scalacheck/scala/collection/mutable/RedBlackTree.scala
Labels: collections

#7784 Add synchronous ("parasitic") ExecutionContext
  src/library/scala/concurrent/ExecutionContext.scala
  src/library/scala/concurrent/Future.scala
  src/library/scala/concurrent/Promise.scala
  src/library/scala/concurrent/impl/Promise.scala
  test/benchmarks/src/main/scala/scala/concurrent/FutureBenchmark.scala
  test/files/jvm/future-spec.check
  test/files/jvm/future-spec/FutureTests.scala
  test/files/neg/t8849.check
Labels: release-notes

#7823 Avoid the parentSymbols method: less allocations.
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/compiler/scala/tools/nsc/transform/Mixin.scala
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala
  src/reflect/scala/reflect/internal/SymbolTable.scala
  src/reflect/scala/reflect/internal/Symbols.scala
Labels: performance

#7832 Optimize attachment lookup and prefix stabilizer addition
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/macros/Attachments.scala
Labels: performance

#7604 Optimize ListMap.from(IterableOnce[(K, V)]) for LinkedHashmap,Map,MapView
  src/library/scala/collection/immutable/ListMap.scala
  src/library/scala/collection/mutable/LinkedHashMap.scala
  test/scalacheck/scala/collection/immutable/ListMapBuilderProperties.scala
  test/scalacheck/scala/collection/immutable/ListMapProperties.scala
Labels: bug fix, collections, performance

#7062 Override some collections methods in Range to use optimised implementations
  src/library/scala/collection/immutable/Range.scala
  src/library/scala/collection/immutable/WrappedString.scala
  test/junit/scala/collection/immutable/RangeTest.scala
  test/scalacheck/scala/collection/immutable/RangeProperties.scala
  test/scalacheck/scala/collection/immutable/WrappedStringProperties.scala
Labels: collections

#7837 copyMethodCompleter: Replace map2 with foreach2
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
Labels: performance

#7793 Extract the ContainsAnyCollector object out of loop.
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
Labels: performance

#7805 Clean up length/size comparison methods
  src/library/scala/collection/ArrayOps.scala
  src/library/scala/collection/IndexedSeq.scala
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/LinearSeq.scala
  src/library/scala/collection/Seq.scala
  src/library/scala/collection/StringOps.scala
Labels: collections

#7827 Uncurry: avoid using List.flatten
  src/reflect/scala/reflect/internal/transform/UnCurry.scala
Labels: performance

#7809 Avoid the call to BaseTypeSeq.toList in type Unification.
  src/reflect/scala/reflect/internal/BaseTypeSeqs.scala
  src/reflect/scala/reflect/internal/Types.scala
Labels: performance

#7820 Namers - no duplicates: backport changes to avoid allocations [nomerge]
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
Labels: performance

#7826 Avoid using List flatMap within normalizeImpl
  src/reflect/scala/reflect/internal/Types.scala
Labels: performance

#7844 Reduce allocations in Uncurry.transformArgs
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
Labels: performance

#7633 A mutable HashMap that degrades to red-black trees in the worst case
  src/library/scala/collection/mutable/CollisionProofHashMap.scala
  test/benchmarks/src/main/scala/scala/collection/mutable/CollisionProofHashMapBenchmark.scala
  test/junit/scala/collection/mutable/CollisionProofHashMapTest.scala
Labels: collections

#7860 Optimize Nil.unzip
  src/library/scala/collection/immutable/List.scala
Labels: collections, performance

#7859 Override MapN.transform for efficiency
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/library/scala/collection/immutable/Map.scala
Labels: collections, performance

#7858 Definitions - SymbolSet: avoid middle map list
  src/reflect/scala/reflect/internal/Definitions.scala
Labels: performance

#7865 Optimisations: avoid List allocations in the RefChecks.
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/reflect/scala/reflect/internal/util/Collections.scala
Labels: performance

#7861 Add Numeric#sign: T as a replacement of Numeric#signum: Int
  src/library/scala/collection/immutable/NumericRange.scala
  src/library/scala/math/BigDecimal.scala
  src/library/scala/math/BigInt.scala
  src/library/scala/math/Numeric.scala
  src/library/scala/runtime/RichByte.scala
  src/library/scala/runtime/RichChar.scala
  src/library/scala/runtime/RichDouble.scala
  src/library/scala/runtime/RichFloat.scala
  src/library/scala/runtime/RichInt.scala
  src/library/scala/runtime/RichLong.scala
  src/library/scala/runtime/RichShort.scala
  src/library/scala/runtime/ScalaNumberProxy.scala
  test/files/presentation/infix-completion.check
  test/files/presentation/infix-completion2.check
  test/junit/scala/math/DoubleTest.scala
Labels: bug fix

#7880 Deprecate `scala.Proxy`.
  src/library/scala/Proxy.scala
  test/files/run/proxy.check
Labels: library:base

#6653 Make ClassfileParser more efficient, lazy, and less cycle prone. [ci: last-only]
  project/VersionUtil.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
  src/compiler/scala/tools/nsc/symtab/classfile/AbstractFileReader.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/symtab/classfile/DataReader.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ReusableDataReader.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/Mirrors.scala
  src/reflect/scala/reflect/internal/Names.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/io/AbstractFile.scala
  src/reflect/scala/reflect/io/PlainFile.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/jvm/throws-annot-from-java.check
  test/files/jvm/throws-annot-from-java/Test_3.scala
  test/files/run/compiler-asSeenFrom.scala
  test/files/run/existentials-in-compiler.scala
  test/files/run/t7008-scala-defined/Impls_Macros_2.scala
  test/files/run/t7008/Impls_Macros_2.scala
  test/files/run/t7096.scala
  test/files/run/t7455/Test.scala
Labels: performance

#7843 Emit mixin forwarders as bridges to avoid needing generic signatures
  src/compiler/scala/tools/nsc/transform/Mixin.scala
  test/files/neg/t4749.check
  test/files/neg/t5148.check
  test/files/run/mixin-bridge-methods.scala
  test/files/run/mixin-forwarder-overload.check
  test/files/run/mixin-forwarder-overload/A.scala
  test/files/run/mixin-forwarder-overload/Test.java
  test/files/run/mixin-signatures.check
  test/files/run/t3452d/Test.java
  test/files/run/t3452g/A.scala
  test/files/run/t3452g/Test.java
  test/files/run/t7932.check
  test/files/run/t8905/DoubleRDD.scala
  test/files/run/t8905/Test.java
Labels: prio:blocker

#7111 Converters among optional Functions, PartialFunctions and extractor objects
  src/build/genprod.scala
  src/library/scala/Function1.scala
  src/library/scala/PartialFunction.scala
  test/junit/scala/ExtractorTest.scala
Labels: library:base, prio:blocker, release-notes

#7881 Replace "zipped" by functions without list allocations.
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
Labels: performance, performance:do_not_allocate

#7891 Fixes for Dotty compatibility
  project/DottySupport.scala
  src/library/scala/collection/Iterator.scala
  src/library/scala/collection/mutable/CollisionProofHashMap.scala
  src/library/scala/collection/mutable/TreeSet.scala
Labels: bug fix, library:collections, prio:blocker

#7856 Revert the implicit dummy params added for Dotty
  src/library/scala/collection/BitSet.scala
  src/library/scala/collection/Map.scala
  src/library/scala/collection/Set.scala
  src/library/scala/collection/StrictOptimizedSetOps.scala
  src/library/scala/collection/immutable/HashSet.scala
  src/library/scala/collection/immutable/Set.scala
  src/library/scala/collection/immutable/TreeSet.scala
  src/library/scala/concurrent/ExecutionContext.scala
Labels: prio:blocker

#7890 Recycle the hashset used for implicit shadowing
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Labels: performance

#7897 GlbLubs polyTypeMatch: No matrix no transpose
  src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
Labels: performance, performance:do_not_allocate

#7887 Make scala.util.Using.Releasable be an alias to java.lang.AutoCloseable
  src/library/scala/util/Using.scala
Labels: prio:blocker

#7901 Add Map.foreachEntry to avoid tupling penalty
  src/library/scala/collection/Map.scala
  src/library/scala/collection/convert/Wrappers.scala
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/IntMap.scala
  src/library/scala/collection/immutable/LongMap.scala
  src/library/scala/collection/immutable/RedBlackTree.scala
  src/library/scala/collection/immutable/TreeMap.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/library/scala/collection/mutable/CollisionProofHashMap.scala
  src/library/scala/collection/mutable/LinkedHashMap.scala
  src/library/scala/collection/mutable/LongMap.scala
  src/library/scala/collection/mutable/OpenHashMap.scala
  src/library/scala/collection/mutable/RedBlackTree.scala
  src/library/scala/collection/mutable/TreeMap.scala
Labels: library:collections

#7588 VectorBuilder shares structure of added Vector if the builder was empty, for better performance of Vector#concat
  src/library/scala/collection/immutable/Vector.scala
  test/scalacheck/scala/collection/immutable/VectorBuilderProperties.scala
Labels: library:collections, performance

#7905 Fix 11438, 11439 leaky abstraction / NPE patrol
  src/library/scala/collection/mutable/ListBuffer.scala
  src/library/scala/collection/mutable/PriorityQueue.scala
  test/junit/scala/collection/mutable/ListBufferTest.scala
  test/junit/scala/collection/mutable/PriorityQueueTest.scala
Labels: library:collections

#7900 Refactor adjustTypeArgs, giving its result record a name
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
Labels: performance:do_not_allocate

#7842 Update and improve LazyList docs
  src/library/scala/collection/immutable/LazyList.scala
  test/junit/scala/collection/immutable/LazyListLazinessTest.scala
Labels: documentation, library:collections

#7815 Merge 2.12.x to 2.13.x [ci: last-only]
  .mailmap
  README.md
  src/compiler/scala/tools/nsc/CompilationUnits.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/PickleExtractor.scala
  src/compiler/scala/tools/nsc/PipelineMain.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  src/compiler/scala/tools/nsc/classpath/ClassPathFactory.scala
  src/compiler/scala/tools/nsc/classpath/FileUtils.scala
  src/compiler/scala/tools/nsc/classpath/VirtualDirectoryClassPath.scala
  src/compiler/scala/tools/nsc/classpath/ZipAndJarFileLookupFactory.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/symtab/classfile/AbstractFileReader.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/symtab/classfile/DataReader.scala
  src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ReusableDataReader.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/compiler/scala/tools/nsc/transform/Mixin.scala
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  src/compiler/scala/tools/nsc/typechecker/Checkable.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala
  src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/util/PathResolver.scala
  src/intellij/scala.ipr.SAMPLE
  src/interactive/scala/tools/nsc/interactive/CompilerControl.scala
  src/reflect/scala/reflect/internal/BaseTypeSeqs.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/Names.scala
  src/reflect/scala/reflect/internal/SymbolTable.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/internal/Variance.scala
  src/reflect/scala/reflect/internal/Variances.scala
  src/reflect/scala/reflect/internal/pickling/UnPickler.scala
  src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
  src/reflect/scala/reflect/internal/transform/UnCurry.scala
  src/reflect/scala/reflect/internal/util/Collections.scala
  src/reflect/scala/reflect/io/RootPath.scala
  src/repl/scala/tools/nsc/interpreter/MemberHandlers.scala
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
Labels: prio:blocker

#7903 Add shrinking to ArrayBuffer, take 3
  src/library/scala/collection/mutable/ArrayBuffer.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
Labels: library:collections

#7787 HashMap merged implementation
  src/library/scala/collection/immutable/HashMap.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashMapProperties.scala
Labels: library:collections, performance, prio:blocker

#7875 Submerge the Variance extractor function into the solve functions.
  src/compiler/scala/reflect/macros/compiler/Validators.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/internal/tpe/TypeConstraints.scala
  src/reflect/scala/reflect/internal/util/Collections.scala
Labels: performance, performance:do_not_allocate

#7883 Uncurry: avoid intermediate lists and ParamTransform ADT
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
Labels: performance, performance:do_not_allocate

#7889 Infer: replace List reverse by ListBuffer
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/reflect/scala/reflect/internal/StdNames.scala
Labels: performance, performance:do_not_allocate

#7831 Optimize checkAccessible for super constructor calls
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
Labels: performance

#7926 Namers: avoid using `map2` if result is not wanted
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
Labels: performance, performance:do_not_allocate

#7776 Break up Symbol.{info,rawInfo} [ci: last-only]
  src/reflect/scala/reflect/internal/Symbols.scala
  test/benchmarks/src/main/scala/reflect/internal/SymbolBenchmark.scala
Labels: performance

#7919 Avoid IntRef in Array.apply
  src/library/scala/Array.scala
Labels: library:collections, performance

#7918 Reduce allocations in Hash{Map,Set}Builder.newEmptyRootNode
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
Labels: library:collections, performance, performance:do_not_allocate

#7775 Honour the TRIEDCOOKING fast path for overloaded symbols
  src/reflect/scala/reflect/internal/Symbols.scala
Labels: performance

#7911 Avoid allocation of Reporter.ERROR to determine !hasErrors
  src/reflect/scala/reflect/internal/Reporting.scala
Labels: performance

#7910 Avoid the use of modifyInfo in maps, use foreach
  src/compiler/scala/tools/nsc/transform/ExtensionMethods.scala
  src/compiler/scala/tools/nsc/typechecker/PatternTypers.scala
  src/reflect/scala/reflect/internal/ExistentialsAndSkolems.scala
  src/reflect/scala/reflect/internal/Symbols.scala
Labels: performance:do_not_allocate

#7912 Merge two List.map into one
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: performance:do_not_allocate

#7924 JavaMirrors: avoid the use of List flatten and map
  src/reflect/scala/reflect/runtime/JavaMirrors.scala
Labels: performance, performance:do_not_allocate

#7718 s.c.i.Hash{Map,Set} concat/removedAll use shallow mutations
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
  src/library/scala/collection/mutable/HashSet.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashMapProperties.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashSetProperties.scala
Labels: library:collections, performance

#7936 keep TrieMapIterator non-final for parallel collections
  src/library/scala/collection/concurrent/TrieMap.scala
Labels: library:collections, prio:blocker

#7794 Remove text that states CDATA sections or PIs are not supported
  spec/10-xml-expressions-and-patterns.md
Labels: documentation, library:xml

#7743 Vectors smaller than 32 allocate or reuse small arrays when possible.
  src/library/scala/collection/immutable/Vector.scala
Labels: library:collections, performance

#7578 HashMap#keySet#incl,excl,filter,filterNot do not copy data. HashMap/Set#filterImpl optimized in maps of depth 1
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
  src/library/scala/collection/immutable/Set.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashMapProperties.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashSetProperties.scala
Labels: library:collections, performance

#7938 provide map, flatMap, collect, concat that return CollisionProofHashMap
  src/library/scala/collection/mutable/CollisionProofHashMap.scala
  test/junit/scala/collection/mutable/CollisionProofHashMapTest.scala
Labels: library:collections

#7940 Don't clear parent block context of AsyncBatch
  src/library/scala/concurrent/BatchingExecutor.scala
Labels: library:concurrent, prio:blocker

#7944 Fix in the doc a couple of mentions to removeAll instead of removedAll
  src/library/scala/collection/Map.scala
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/Set.scala
Labels: documentation, library:collections

#7941 Optimization in symbol pairs a bit less wrong again
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/compiler/scala/tools/nsc/transform/OverridingPairs.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
  src/reflect/scala/reflect/internal/SymbolPairs.scala
  test/files/neg/t11136_override_conflict.check
  test/files/neg/t11136_override_conflict.scala
  test/files/run/extend-global.scala
  test/junit/scala/tools/nsc/typechecker/OverridingPairsTest.scala
Labels: prio:blocker

#7948 Fix non-compiling scala.util.Using scaladoc examples
  src/library/scala/util/Using.scala
Labels: documentation

#7946 Fix initialize method in BinaryTreeStepper
  src/library/scala/collection/convert/impl/BinaryTreeStepper.scala
  test/junit/scala/collection/convert/BinaryTreeStepperTest.scala
Labels: bug fix, library:collections
