Repository scala/scala, pull requests merged in 2019-02, with the labels that each got.

#7593 Don't make lifted method static if it's synchronized
  src/compiler/scala/tools/nsc/transform/Delambdafy.scala
  test/files/run/synchronized.check
  test/files/run/synchronized.scala
Labels: welcome

#7450 Optimize (hot) Symbol#name, and some other things
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/util/ReusableInstance.scala
Labels: performance

#7688 Constructor keeps ref to private local field
  src/compiler/scala/tools/nsc/transform/Constructors.scala
  test/files/run/t6880.check
  test/files/run/t6880.scala
Labels: bug fix

#7624 Make unified collection serialization opt-in instead of opt-out
  src/library/scala/Enumeration.scala
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/Map.scala
  src/library/scala/collection/SortedMap.scala
  src/library/scala/collection/SortedSet.scala
  src/library/scala/collection/View.scala
  src/library/scala/collection/WithFilter.scala
  src/library/scala/collection/concurrent/TrieMap.scala
  src/library/scala/collection/convert/Wrappers.scala
  src/library/scala/collection/generic/DefaultSerializationProxy.scala
  src/library/scala/collection/immutable/ArraySeq.scala
  src/library/scala/collection/immutable/BitSet.scala
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
  src/library/scala/collection/immutable/IntMap.scala
  src/library/scala/collection/immutable/LazyList.scala
  src/library/scala/collection/immutable/List.scala
  src/library/scala/collection/immutable/ListMap.scala
  src/library/scala/collection/immutable/ListSet.scala
  src/library/scala/collection/immutable/LongMap.scala
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/NumericRange.scala
  src/library/scala/collection/immutable/Queue.scala
  src/library/scala/collection/immutable/Range.scala
  src/library/scala/collection/immutable/SeqMap.scala
  src/library/scala/collection/immutable/Set.scala
  src/library/scala/collection/immutable/SortedMap.scala
  src/library/scala/collection/immutable/Stream.scala
  src/library/scala/collection/immutable/TreeMap.scala
  src/library/scala/collection/immutable/TreeSet.scala
  src/library/scala/collection/immutable/Vector.scala
  src/library/scala/collection/immutable/WrappedString.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayDeque.scala
  src/library/scala/collection/mutable/ArraySeq.scala
  src/library/scala/collection/mutable/BitSet.scala
  src/library/scala/collection/mutable/HashMap.scala
  src/library/scala/collection/mutable/HashSet.scala
  src/library/scala/collection/mutable/LinkedHashMap.scala
  src/library/scala/collection/mutable/LinkedHashSet.scala
  src/library/scala/collection/mutable/ListBuffer.scala
  src/library/scala/collection/mutable/ListMap.scala
  src/library/scala/collection/mutable/LongMap.scala
  src/library/scala/collection/mutable/Map.scala
  src/library/scala/collection/mutable/OpenHashMap.scala
  src/library/scala/collection/mutable/PriorityQueue.scala
  src/library/scala/collection/mutable/Queue.scala
  src/library/scala/collection/mutable/SortedMap.scala
  src/library/scala/collection/mutable/StringBuilder.scala
  src/library/scala/collection/mutable/TreeMap.scala
  src/library/scala/collection/mutable/TreeSet.scala
  src/library/scala/collection/mutable/UnrolledBuffer.scala
  src/library/scala/collection/mutable/WeakHashMap.scala
  test/files/run/invalid-lubs.check
  test/files/run/repl-colon-type.check
  test/junit/scala/SerializationStabilityTest.scala
Labels: collections, release-notes

#7654 Implement `take` and `slice` in VectorIterator
  src/library/scala/collection/immutable/Vector.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: collections

#7704 Remove s.c.i.Node#sizePredicate
  src/library/scala/collection/immutable/ChampCommon.scala
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
Labels: collections

#7495 Add sym shorthand for Symbol
  src/library/scala/StringContext.scala
  src/library/scala/Symbol.scala
  test/junit/scala/lang/stringinterpol/SymbolsTest.scala
Labels: release-notes

#7570 StrictOptimizedIterableOps#strictOptimizedConcat forwards original collections to builders, not iterators
  src/library/scala/collection/StrictOptimizedIterableOps.scala
Labels: collections

#7488 Widen mutable.BitSet operations to accept any collection.BitSet, not just mutable
  src/library/scala/collection/mutable/BitSet.scala
  test/benchmarks/src/main/scala/scala/collection/mutable/BitSetBenchmark.scala
  test/junit/scala/collection/mutable/BitSetTest.scala
  test/scalacheck/scala/collection/mutable/BitSetProperties.scala
Labels: collections, performance

#7711 Optimize s.c.m.HashSet#filterInPlace
  src/library/scala/collection/mutable/HashSet.scala
  test/scalacheck/scala/collection/mutable/HashSetProperties.scala
Labels: collections, performance

#7434 [#11246] MapView overrides transformations to return MapView when possible.
  src/library/scala/collection/MapView.scala
  src/library/scala/collection/immutable/Map.scala
  test/scalacheck/scala/collection/MapViewProperties.scala
Labels: collections

#7589 Delegating collection factories do not rebuild collections to be specific type the factory delegates to
  src/library/scala/collection/Factory.scala
  src/library/scala/collection/LinearSeq.scala
  src/library/scala/collection/SortedMap.scala
  src/library/scala/collection/immutable/Iterable.scala
  src/library/scala/collection/immutable/Seq.scala
  src/library/scala/collection/immutable/SortedMap.scala
  src/library/scala/collection/immutable/SortedSet.scala
  test/files/run/enrich-gentraversable.check
  test/junit/scala/SerializationStabilityTest.scala
  test/junit/scala/collection/FactoriesTest.scala
Labels: collections

#7717 Comment Set.remove
  src/library/scala/collection/mutable/Set.scala
Labels: collections, documentation

#7395 Deprecate symbol literal
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  test/files/jvm/manifests-new.check
  test/files/jvm/manifests-old.check
  test/files/jvm/serialization-new.check
  test/files/jvm/serialization.check
  test/files/neg/checksensible.check
  test/files/neg/names-defaults-neg.check
  test/files/neg/symbol-literal-deprecation.check
  test/files/neg/symbol-literal-deprecation.scala
  test/files/neg/symbol-literal-removal.check
  test/files/neg/symbol-literal-removal.scala
  test/files/run/SymbolsTest.scala
  test/files/run/arrays.scala
  test/files/run/fors.scala
  test/files/run/lisp.scala
  test/files/run/t10646.scala
  test/files/run/t4560.check
  test/files/run/t4601.check
  test/files/run/t6632.check
  test/files/run/t6633.check
  test/files/run/t6634.check
  test/files/run/t7974.check
  test/files/run/t8933/A_1.scala
  test/files/run/t8933/Test_2.scala
  test/files/run/t8933b/A.scala
  test/files/run/t8933b/Test.scala
Labels: release-notes

#7660 Eta-expand 0-arity method if expected type is Function0
  project/ScalaOptionParser.scala
  spec/06-expressions.md
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/Parsing.scala
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  src/compiler/scala/tools/nsc/typechecker/Adaptations.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/nsc/typechecker/Unapplies.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/Variances.scala
  src/reflect/scala/reflect/internal/settings/MutableSettings.scala
  src/reflect/scala/reflect/internal/tpe/TypeComparers.scala
  src/reflect/scala/reflect/runtime/Settings.scala
  test/files/jvm/future-spec/FutureTests.scala
  test/files/neg/t7187-2.14.check
  test/files/neg/t7187-2.14.scala
  test/files/neg/t7187.check
  test/files/neg/t7187.scala
  test/files/neg/t8265.check
  test/files/neg/t8265.scala
  test/files/pos/implicit-anyval-2.10.scala
  test/files/pos/t2066-2.10-compat.scala
  test/files/pos/t8157-2.10.scala
  test/files/run/macro-range.flags
  test/files/run/t6863.check
  test/files/run/t6863.scala
  test/files/run/t7187.scala
Labels: release-notes

#7615 Don’t expose Map.WithDefault in return types
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/SortedMap.scala
  src/library/scala/collection/immutable/VectorMap.scala
  src/library/scala/collection/mutable/Map.scala
  src/library/scala/collection/mutable/SortedMap.scala
  test/junit/scala/collection/immutable/HashMapTest.scala
  test/junit/scala/collection/immutable/SortedMapTest.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
  test/junit/scala/collection/mutable/HashMapTest.scala
  test/junit/scala/collection/mutable/SortedMapTest.scala
Labels: collections

#7708 Optimize s.c.m.Set#filterInPlace
  src/library/scala/collection/mutable/Set.scala
  test/scalacheck/scala/collection/mutable/SetProperties.scala
Labels: collections, performance

#7745 [bug#11399] Fix LazyList#sliding
  src/library/scala/collection/immutable/LazyList.scala
  test/junit/scala/collection/immutable/LazyListLazinessTest.scala
Labels: bug fix, collections

#7705 scala.collection.convert.JSetWrapper#filterInPlace delegates to underlying#removeIf
  src/library/scala/collection/convert/Wrappers.scala
  test/junit/scala/collection/convert/JSetWrapperTest.scala
  test/scalacheck/scala/collection/convert/WrapperProperties.scala
Labels: collections, performance

#7657 Optimized s.c.i.HashSet[A]#concat(s.c.i.HashSet[A]) implementation
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashSetProperties.scala
Labels: collections, performance

#7651 Add Builder#knownSize with reasonable implementations
  src/library/scala/collection/IndexedSeq.scala
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
  src/library/scala/collection/immutable/Vector.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  src/library/scala/collection/mutable/Buffer.scala
  src/library/scala/collection/mutable/Builder.scala
  src/library/scala/collection/mutable/Growable.scala
  src/library/scala/collection/mutable/GrowableBuilder.scala
  src/library/scala/collection/mutable/ImmutableBuilder.scala
  src/library/scala/collection/mutable/LongMap.scala
  src/library/scala/collection/mutable/Map.scala
  src/library/scala/collection/mutable/Set.scala
  src/library/scala/collection/mutable/StringBuilder.scala
  src/library/scala/collection/mutable/UnrolledBuffer.scala
  test/junit/scala/SerializationStabilityTest.scala
Labels: collections

#7663 Significant performance improvements to Futures
  .gitignore
  src/library/scala/concurrent/BatchingExecutor.scala
  src/library/scala/concurrent/BlockContext.scala
  src/library/scala/concurrent/Future.scala
  src/library/scala/concurrent/impl/ExecutionContextImpl.scala
  src/library/scala/concurrent/impl/Promise.scala
  src/library/scala/concurrent/package.scala
  test/benchmarks/src/main/scala/scala/concurrent/FutureBenchmark.scala
  test/files/jvm/future-spec/FutureTests.scala
  test/files/jvm/future-spec/PromiseTests.scala
Labels: release-notes

#7747 Future-proof the collections for Dotty
  src/library/scala/collection/Map.scala
  src/library/scala/concurrent/BatchingExecutor.scala
  src/library/scala/runtime/package.scala
Labels: collections

#7761 Add missing SeqView#knownSize
  src/library/scala/collection/SeqView.scala
Labels: collections

#7770 Added comments to the method force of class LazyList
  src/library/scala/collection/immutable/LazyList.scala
Labels: collections, documentation

#7773 Optimize ListBuffer.addAll
  src/library/scala/collection/mutable/ListBuffer.scala
  test/benchmarks/src/main/scala/scala/collection/mutable/BuilderBenchmark.scala
Labels: collections, performance

#7765 Add scaladocs to scala.collection.Searching
  src/library/scala/collection/Searching.scala
Labels: documentation

#7766 Bump timeout in future-spec
  test/files/jvm/future-spec/FutureTests.scala
  test/files/jvm/future-spec/main.scala
Labels: tests

#7754 Test defect for reflection of private fields
  test/junit/scala/collection/mutable/OpenHashMapTest.scala
  test/junit/scala/reflect/FieldAccessTest.scala
Labels: tests

#7739 Performance tweak to sameTypesFolded
  src/reflect/scala/reflect/internal/Types.scala
Labels: performance

#7786 Small optimisation in glbNorm function.
  src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
Labels: performance

#7796 Allow sorting of array slices
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/util/Sorting.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
Labels: collections

#7709 Optimize s.c.m.{Map, HashMap}#filterInPlace implementations
  src/library/scala/collection/mutable/HashMap.scala
  src/library/scala/collection/mutable/Map.scala
  test/scalacheck/scala/collection/mutable/MapProperties.scala
Labels: collections, performance

#7750 [bug#11399] Fix LazyList#sliding
  src/library/scala/collection/immutable/LazyList.scala
  test/junit/scala/collection/immutable/LazyListLazinessTest.scala
Labels: bug fix, collections

#7778 readme changes
  README.md
Labels: documentation

#7753 Improve chaining operators
  src/library/scala/util/ChainingOps.scala
Labels: performance

#7573 Add lazy builder for LazyList
  src/library/scala/collection/immutable/LazyList.scala
  test/junit/scala/collection/immutable/LazyListLazinessTest.scala
  test/junit/scala/collection/immutable/LazyListTest.scala
  test/scalacheck/scala/collection/immutable/SeqProperties.scala
Labels: collections

#7733 Override SeqView#sorted
  src/library/scala/collection/Seq.scala
  src/library/scala/collection/SeqView.scala
Labels: collections
