Repository scala/scala, pull requests merged in 2019-07, with the labels that each got.

#8087 Suppress stack trace in test
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/junit/scala/sys/process/ProcessTest.scala
  test/junit/scala/tools/testing/AssertUtilTest.scala
Labels: build, tests

#8178 Show MiMa logs at the end of testAll in case of MiMa failures
  build.sbt
  project/SavedLogs.scala
Labels: build

#8195 [#11589]s.c.Map#values returns a strict Iterable rather than a View
  src/library/scala/collection/Map.scala
  test/junit/scala/collection/MapTest.scala
Labels: library:collections

#8091 Micro-opt of ArrayDeque.remove
  src/library/scala/collection/mutable/ArrayDeque.scala
Labels: library:collections, performance

#7871 Remove safeTagMarker from Comment Parser before handing it over to ScalaDoc rendering
  src/scaladoc/scala/tools/nsc/doc/base/CommentFactoryBase.scala
  test/scaladoc/run/t11424.check
  test/scaladoc/run/t11424.scala
Labels: tool:scaladoc

#8167 [nomerge] add sbt-whitesource
  build.sbt
  project/plugins.sbt
Labels: build

#7931 Use AdoptOpenJDK JDK 8 for testing [ci: last-only]
  .travis.yml
Labels: build

#8210 Fix scalac compatibility with JDK 13
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
Labels: build

#8179 Fix vulnerability in jQuery used in ScalaDoc
  build.sbt
  project/ScaladocSettings.scala
  src/scaladoc/scala/tools/nsc/doc/html/HtmlFactory.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  src/scaladoc/scala/tools/nsc/doc/html/resource/lib/index.js
  src/scaladoc/scala/tools/nsc/doc/html/resource/lib/jquery.js
  src/scaladoc/scala/tools/nsc/doc/html/resource/lib/template.js
  src/scaladoc/scala/tools/nsc/doc/html/resource/lib/tools.tooltip.js
  src/scaladoc/scala/tools/nsc/doc/html/resource/lib/versions.txt
  test/scaladoc/javascript/test-index.html
Labels: tool:scaladoc

#8227 Reduce overhead of active analyzer plugins in hot paths
  src/compiler/scala/tools/nsc/typechecker/AnalyzerPlugins.scala
Labels: performance

#8220 [11630] Iterator#flatMap#hasNext calls outer#hasNext 1 time, not 2-3 times
  src/library/scala/collection/Iterator.scala
  test/junit/scala/collection/IteratorTest.scala
Labels: library:collections, performance, prio:blocker

#8225 Fixes Non-Iterators have iterator reuse warnings in scaladoc#11595
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/Iterator.scala
Labels: documentation, library:collections

#8221 Fixes scala/bug#11592
  src/library/scala/collection/IterableOnce.scala
  test/junit/scala/math/BigDecimalTest.scala
Labels: library:collections

#8209 add sbt-whitesource
  build.sbt
  project/plugins.sbt
Labels: build

#8231 Optimize check for by-name expressions
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
Labels: performance

#8229 Reduce allocations for virtual compilation units
  src/compiler/scala/tools/nsc/CompilationUnits.scala
  src/compiler/scala/tools/nsc/transform/Mixin.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
Labels: performance

#8228 Optimize macro plugin infrastructure to reduce allocations
  src/compiler/scala/tools/nsc/typechecker/AnalyzerPlugins.scala
Labels: performance

#8230 Hoist creation of SubstSymMap out of hot loop in deriveSymbols
  src/reflect/scala/reflect/internal/Symbols.scala
Labels: performance

#8234 [nomerge] use 'in Compile' for new scalacOptions
  build.sbt
  project/plugins.sbt
Labels: build

#8232 Optimise implicit search
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Labels: performance

#7935 Optimize some hot callers of Symbol.name to use rawname
  src/reflect/scala/reflect/internal/Scopes.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/tpe/FindMembers.scala
Labels: performance

#8238 [backport] Optimize some hot callers of Symbol.name to use rawname
  src/reflect/scala/reflect/internal/Scopes.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/tpe/FindMembers.scala
Labels: performance

#8226 [backport] List.filter optimizations from 2.13.x
  src/library/scala/collection/TraversableLike.scala
Labels: library:collections, performance

#8235 use 'in Compile' for new scalacOptions
  build.sbt
  project/DottySupport.scala
Labels: build

#8236 Fix doc for ArrayDeque
  src/library/scala/collection/mutable/ArrayDeque.scala
Labels: documentation, library:collections

#8244 Avoid allocation of LinkedHashSet in Refchecks for every member
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
Labels: performance

#8241 Inline toIterable's deprecation method
  src/library/scala/collection/IterableOnce.scala
Labels: documentation, library:collections

#8053 Clarify what Null is a subtype of.
  spec/03-types.md
  src/library-aux/scala/Null.scala
Labels: documentation

#8061 Generate shallower ASTs in pattern translation (Scala.js users, please read)
  src/compiler/scala/tools/nsc/ast/TreeDSL.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchCodeGen.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala
  src/partest-extras/scala/tools/partest/ASMConverters.scala
  test/files/run/macroPlugins-namerHooks.check
  test/files/run/sd187.check
  test/files/run/t6288.check
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: release-notes

#8249 Optimize writing of InlineInfoAttribute
  src/compiler/scala/tools/nsc/PickleExtractor.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromClassfile.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/CallGraph.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/InlineInfoAttribute.scala
  src/reflect/scala/reflect/io/RootPath.scala
  test/junit/scala/tools/nsc/PipelineMainTest.scala
  test/junit/scala/tools/nsc/backend/jvm/opt/InlineInfoTest.scala
  test/junit/scala/tools/nsc/backend/jvm/opt/ScalaInlineInfoTest.scala
Labels: performance

#8215 Improve ArrayDeque resizing logic
  src/library/scala/collection/mutable/ArrayDeque.scala
  test/junit/scala/collection/mutable/ArrayDequeTest.scala
Labels: bug fix, library:collections

#8211 Add benchmark for ArrayDeque
  test/benchmarks/src/main/scala/scala/collection/mutable/ArrayDequeBenchmark.scala
Labels: build, library:collections

#8202 Stabilize args of apply
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/run/t11397.scala
Labels: bug fix, release-notes

#8192 fix mutable.HashSet.addAll: remove redundant call to super method
  src/library/scala/collection/mutable/HashSet.scala
  test/junit/scala/collection/mutable/HashSetTest.scala
Labels: library:collections, welcome

#8243 Option test suite in Java
  test/junit/scala/OptionJavaTest.java
Labels: library:base, tests

#8184 Add many type annotations to public members
  src/library/scala/Console.scala
  src/library/scala/Enumeration.scala
  src/library/scala/PartialFunction.scala
  src/library/scala/StringContext.scala
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/concurrent/TrieMap.scala
  src/library/scala/collection/immutable/ListSet.scala
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/Range.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  src/library/scala/collection/mutable/ArrayDeque.scala
  src/library/scala/collection/mutable/StringBuilder.scala
  src/library/scala/collection/mutable/TreeSet.scala
  src/library/scala/io/Codec.scala
  src/library/scala/io/Source.scala
  src/library/scala/math/BigDecimal.scala
  src/library/scala/math/BigInt.scala
  src/library/scala/math/Ordering.scala
  src/library/scala/ref/Reference.scala
  src/library/scala/ref/ReferenceQueue.scala
  src/library/scala/ref/ReferenceWrapper.scala
  src/library/scala/ref/SoftReference.scala
  src/library/scala/ref/WeakReference.scala
  src/library/scala/sys/SystemProperties.scala
  src/library/scala/util/matching/Regex.scala
Labels: library:base, library:collections

#8247 Fix generateDocsData
  project/GenerateDocsData.scala
Labels: build

#8258 Merge 2.11.x to 2.12.x [ci: last-only]
  spec/_layouts/default.yml
  spec/_layouts/toc.yml
  spec/public/scripts/toc.js
Labels: documentation

#8183 Add protected and private visibility filters to scaladoc
  src/scaladoc/scala/tools/nsc/doc/Settings.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  src/scaladoc/scala/tools/nsc/doc/html/resource/lib/template.js
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
  src/scaladoc/scala/tools/nsc/doc/model/Visibility.scala
  test/scalacheck/scala/tools/nsc/scaladoc/HtmlFactoryTest.scala
  test/scaladoc/resources/t10999.scala
Labels: tool:scaladoc

#8084 Doc to avoid Unit box and unbox
  project/GenerateAnyVals.scala
  src/library/scala/Unit.scala
Labels: documentation

#8112 Cache materialized TypeTags
  src/reflect/mima-filters/2.12.0.forwards.excludes
  src/reflect/scala/reflect/api/TypeTags.scala
  src/reflect/scala/reflect/runtime/JavaMirrors.scala
  test/files/run/typetags_caching.scala
Labels: performance, release-notes

#8054 Scaladoc treats annotations more like classes.
  src/scaladoc/scala/tools/nsc/doc/html/Page.scala
  src/scaladoc/scala/tools/nsc/doc/model/Entity.scala
  test/scalacheck/scala/tools/nsc/scaladoc/HtmlFactoryTest.scala
  test/scaladoc/resources/t11390.scala
Labels: tool:scaladoc

#8259 Fixes PartialFunction scaladoc layout
  src/library/scala/PartialFunction.scala
Labels: documentation, library:base

#8260 Backport ListBuffer.+= optimizations
  src/library/scala/collection/mutable/ListBuffer.scala
Labels: library:collections, performance

#8254 Scaladoc: avoid bad links in `protected[x]` when `x` is external
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
  src/scaladoc/scala/tools/nsc/doc/model/Visibility.scala
  test/scalacheck/scala/tools/nsc/scaladoc/HtmlFactoryTest.scala
  test/scaladoc/resources/t11318.scala
Labels: tool:scaladoc

#8266 Tweak the PF from fn literal synthesis
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/pos/partialfun.scala
Labels: library:base

#8264 Neg test case for using non-accessible annotation
  test/files/neg/t11607.check
  test/files/neg/t11607.scala
Labels: build, tests

#8274 fix BeanProperty example code
  src/library/scala/beans/BeanProperty.scala
Labels: documentation

#8285 Fix comments in LazyList
  src/library/scala/collection/immutable/LazyList.scala
Labels: documentation
