Repository scala/scala, pull requests merged in 2019-08, with the labels that each got.

#8076 Optimise s.c.i.ArraySeq.from for s.c.i.ArraySeq
  src/library/scala/Array.scala
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/immutable/ArraySeq.scala
  test/junit/scala/collection/immutable/ArraySeqTest.scala
Labels: library:collections, performance:do_not_allocate

#8287 Blacken subtrees where necessary in RedBlackTree.take
  src/library/scala/collection/immutable/RedBlackTree.scala
  test/junit/scala/collection/immutable/TreeSetTest.scala
  test/scalacheck/redblacktree.scala
Labels: library:collections

#8305 SpecialiseTypes: do not get a keyset.
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
Labels: performance:do_not_allocate

#8306 Namers, PolyTypeCompleter: reuse the list of typeParams.
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
Labels: performance:do_not_allocate

#8304 Replace map2 with foreach2.
  src/compiler/scala/reflect/macros/compiler/Validators.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: performance:do_not_allocate

#8313 there is only one Diego
  .mailmap
Labels: build

#8294 Douse an allocation hotspot in pattern matcher
  src/compiler/scala/tools/nsc/transform/patmat/Solving.scala
Labels: performance

#8328 [backport] Fix the build for newer Java Virtual Machines.
  project/GenerateAnyVals.scala
  project/VersionUtil.scala
Labels: build

#8298 Reduce allocations in Typer / Attachments
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/mima-filters/2.12.0.forwards.excludes
  src/reflect/scala/reflect/macros/Attachments.scala
Labels: performance

#8316 Disable expensive lookup of source file in classfile parser by default
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
Labels: performance

#8295 Optimize compiler phase assembly
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/PhaseAssembly.scala
  test/benchmarks/src/main/scala/scala/tools/nsc/PhaseAssemblyBenchmark.scala
Labels: performance

#8337 Hoist TypeCollector used by containsTypeVar in hot path in basetypeseqs
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
Labels: performance

#8336 Reuse an instance of FindMember
  src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/internal/Variances.scala
  src/reflect/scala/reflect/internal/tpe/FindMembers.scala
  src/reflect/scala/reflect/internal/util/ReusableInstance.scala
Labels: performance

#8327 Revert "Generate shallower ASTs in pattern translation"
  src/compiler/scala/tools/nsc/ast/TreeDSL.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchCodeGen.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala
  src/partest-extras/scala/tools/partest/ASMConverters.scala
  test/files/run/macroPlugins-namerHooks.check
  test/files/run/sd187.check
  test/files/run/t6288.check
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: release-notes

#8290 Escape dollar signs for variables in doc comments
  src/compiler/scala/reflect/quasiquotes/Reifiers.scala
  src/compiler/scala/tools/nsc/ScriptRunner.scala
  src/compiler/scala/tools/nsc/ast/TreeGen.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/package.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/BoxUnbox.scala
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/compiler/scala/tools/nsc/transform/AccessorSynthesis.scala
  src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala
  src/compiler/scala/tools/nsc/transform/ExtensionMethods.scala
  src/compiler/scala/tools/nsc/transform/Fields.scala
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchCodeGen.scala
  src/compiler/scala/tools/nsc/typechecker/EtaExpansion.scala
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/reflect/ToolBox.scala
  src/interactive/scala/tools/nsc/interactive/Pickler.scala
  src/library/scala/Console.scala
  src/library/scala/Option.scala
  src/library/scala/StringContext.scala
  src/library/scala/annotation/implicitAmbiguous.scala
  src/library/scala/io/AnsiColor.scala
  src/library/scala/reflect/ClassTag.scala
  src/library/scala/util/Either.scala
  src/library/scala/util/matching/Regex.scala
  src/reflect/scala/reflect/api/FlagSets.scala
  src/reflect/scala/reflect/api/Liftables.scala
  src/reflect/scala/reflect/api/TypeTags.scala
  src/reflect/scala/reflect/internal/Names.scala
  src/reflect/scala/reflect/internal/TreeInfo.scala
  src/reflect/scala/reflect/internal/Trees.scala
  src/reflect/scala/reflect/macros/Evals.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
Labels: documentation

#8339 Escape dollar signs for variables in doc comments
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala
  src/compiler/scala/tools/reflect/FormatInterpolator.scala
  src/library/scala/PartialFunction.scala
  src/library/scala/StringContext.scala
  src/library/scala/annotation/implicitNotFound.scala
  src/library/scala/jdk/StreamConverters.scala
  src/library/scala/util/ChainingOps.scala
  src/partest/scala/tools/partest/BytecodeTest.scala
  src/reflect/scala/reflect/internal/TreeInfo.scala
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
Labels: documentation

#8342 Reduce allocations in the backend
  src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeSkelBuilder.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala
Labels: performance:do_not_allocate

#8340 [bug#11687] Don't rebuild scala.Seq to drop elems in unapplySeq
  src/library/scala/collection/Factory.scala
  test/files/run/matchonstream.check
  test/files/run/matchonstream.scala
Labels: bug fix, library:collections, regression

#8351 modernize the readme a bit (areas: IDEs, bootstrapping)
  README.md
Labels: documentation

#8333 Avoid using the "lines" method.
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/util/PathResolver.scala
  src/interactive/scala/tools/nsc/interactive/tests/InteractiveTest.scala
  src/interactive/scala/tools/nsc/interactive/tests/InteractiveTestSettings.scala
  src/partest-extras/scala/tools/partest/IcodeComparison.scala
  src/partest-extras/scala/tools/partest/ReplTest.scala
  src/reflect/scala/reflect/internal/Printers.scala
  src/reflect/scala/reflect/internal/util/StringOps.scala
  src/repl-jline/scala/tools/nsc/interpreter/jline/JLineHistory.scala
  src/repl/scala/tools/nsc/interpreter/ILoop.scala
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  src/repl/scala/tools/nsc/interpreter/Pasted.scala
  src/repl/scala/tools/nsc/interpreter/Power.scala
  src/repl/scala/tools/nsc/interpreter/ReplProps.scala
  src/repl/scala/tools/nsc/interpreter/ReplReporter.scala
  src/scaladoc/scala/tools/nsc/doc/html/HtmlFactory.scala
  test/files/run/repl-serialization.scala
  test/junit/scala/io/SourceTest.scala
  test/junit/scala/lang/stringinterpol/StringContextTest.scala
  test/junit/scala/reflect/internal/PrintersTest.scala
  test/junit/scala/tools/nsc/interpreter/ScriptedTest.scala
  test/junit/scala/tools/nsc/reporters/ConsoleReporterTest.scala
  test/junit/scala/tools/nsc/settings/SettingsTest.scala
  test/junit/scala/tools/nsc/util/StackTraceTest.scala
Labels: build

#8358 Optimize setting initialization with large classpaths
  src/compiler/scala/tools/nsc/CompilerCommand.scala
  src/compiler/scala/tools/nsc/ScriptRunner.scala
  src/compiler/scala/tools/nsc/settings/AbsSettings.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/util/ClassPath.scala
  src/repl/scala/tools/nsc/interpreter/ILoop.scala
  test/files/run/settings-parse.check
  test/junit/scala/tools/nsc/settings/SettingsTest.scala
Labels: performance

#8362 improve -Xdev help text
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
Labels: documentation

#8356 Optimize the classpath implementation
  src/compiler/scala/tools/nsc/backend/jvm/ClassfileWriters.scala
  src/compiler/scala/tools/nsc/classpath/AggregateClassPath.scala
  src/compiler/scala/tools/nsc/classpath/ClassPath.scala
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/compiler/scala/tools/nsc/classpath/VirtualDirectoryClassPath.scala
  src/compiler/scala/tools/nsc/classpath/ZipAndJarFileLookupFactory.scala
  src/compiler/scala/tools/nsc/classpath/ZipArchiveFileLookup.scala
  src/compiler/scala/tools/nsc/util/ClassPath.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/reflect/mima-filters/2.12.0.backwards.excludes
  src/reflect/mima-filters/2.12.0.forwards.excludes
  src/reflect/scala/reflect/io/ZipArchive.scala
  test/benchmarks/src/main/scala/scala/tools/nsc/AggregateClassPathBenchmark.scala
  test/junit/scala/tools/nsc/classpath/AggregateClassPathTest.scala
Labels: performance

#8359 Add links for Scala modules in docs
  src/library/rootdoc.txt
Labels: documentation

#8360 remove unused JavaScript dependencies and licenses
  doc/LICENSE.md
  doc/License.rtf
  doc/licenses/mit_tools.tooltip.txt
  src/scaladoc/scala/tools/nsc/doc/html/resource/lib/modernizr.custom.js
Labels: build

#8357 Add links for Scala modules in docs
  src/library/rootdoc.txt
Labels: documentation

#8365 lengthen timeout in concurrency test case
  test/files/jvm/scala-concurrent-tck.scala
Labels: build

#8355 Fix warnings in doc comments
  src/compiler/scala/reflect/macros/compiler/DefaultMacroCompiler.scala
  src/compiler/scala/tools/nsc/ObjectRunner.scala
  src/compiler/scala/tools/nsc/ast/parser/MarkupParsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/compiler/scala/tools/nsc/ast/parser/SymbolicXMLBuilder.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromClassfile.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/Inliner.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala
  src/compiler/scala/tools/nsc/transform/TypeAdaptingTransformer.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/compiler/scala/tools/nsc/typechecker/Macros.scala
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  src/compiler/scala/tools/nsc/util/DocStrings.scala
  src/interactive/scala/tools/nsc/interactive/CompilerControl.scala
  src/interactive/scala/tools/nsc/interactive/Lexer.scala
  src/interactive/scala/tools/nsc/interactive/Pickler.scala
  src/library/scala/Predef.scala
  src/library/scala/SerialVersionUID.scala
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/Stepper.scala
  src/library/scala/collection/convert/StreamExtensions.scala
  src/library/scala/jdk/Accumulator.scala
  src/library/scala/jdk/FutureConverters.scala
  src/library/scala/jdk/javaapi/DurationConverters.scala
  src/library/scala/jdk/javaapi/FutureConverters.scala
  src/library/scala/jdk/javaapi/StreamConverters.scala
  src/library/scala/reflect/ClassTag.scala
  src/partest/scala/tools/partest/BytecodeTest.scala
  src/reflect/scala/reflect/api/FlagSets.scala
  src/reflect/scala/reflect/api/Internals.scala
  src/reflect/scala/reflect/api/Mirror.scala
  src/reflect/scala/reflect/api/Mirrors.scala
  src/reflect/scala/reflect/api/Trees.scala
  src/reflect/scala/reflect/api/TypeTags.scala
  src/reflect/scala/reflect/api/Types.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
  src/reflect/scala/reflect/macros/Enclosures.scala
  src/reflect/scala/reflect/macros/Typers.scala
  src/reflect/scala/reflect/macros/Universe.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
Labels: documentation

#8300 More efficient ArraySeq iteration
  build.sbt
  src/library/scala/collection/ArrayOps.scala
  src/library/scala/collection/immutable/ArraySeq.scala
  src/library/scala/collection/mutable/ArraySeq.scala
Labels: library:collections

#8310 Make the empty method of TreeSeqMap respect the orderBy parameter
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/immutable/TreeSeqMap.scala
  test/junit/scala/collection/immutable/TreeSeqMapTest.scala
Labels: library:collections

#8374 Avoid unnecessary toSeq conversions in Seq methods
  src/library/scala/collection/Seq.scala
Labels: library:collections

#8376 switch annotation issues warnings, not errors
  src/library/scala/annotation/switch.scala
Labels: documentation

#8367 Avoid memory leaks in Stream methods
  build.sbt
  project/TestJarSize.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/Inliner.scala
  src/library/scala/collection/immutable/Stream.scala
  test/files/run/indyLambdaKinds.check
  test/files/run/stream-gc.check
  test/files/run/stream-gc.javaopts
  test/files/run/stream-gc.scala
  test/junit/scala/tools/nsc/backend/jvm/opt/InlinerTest.scala
Labels: library:collections

#8311 add knownSize to appropriate Iterators
  src/library/scala/collection/Iterator.scala
  test/junit/scala/collection/IteratorTest.scala
Labels: library:collections

#8284 Enable hyperlinking to Java docs
  build.sbt
  src/compiler/scala/tools/nsc/util/StackTracing.scala
  src/compiler/scala/tools/nsc/util/package.scala
  src/library/scala/collection/StringOps.scala
  src/library/scala/collection/mutable/StringBuilder.scala
  src/library/scala/concurrent/duration/Duration.scala
  src/library/scala/math/Equiv.scala
  src/library/scala/math/Ordering.scala
  src/library/scala/util/Using.scala
  src/reflect/scala/reflect/api/Mirrors.scala
Labels: documentation
