Repository scala/scala, pull requests merged in 2019-10, with the labels that each got.

#8453 Revert "Use travis-wait-enhanced"
  .travis.yml
Labels: build

#8455 Refactor Try tests to junit
  test/files/jvm/future-spec/TryTests.scala
  test/files/jvm/future-spec/main.scala
  test/files/jvm/try-type-tests.scala
  test/junit/scala/util/TryTest.scala
Labels: tests

#8462 Reuse buffers in pickler
  src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  test/junit/scala/collection/mutable/AnyRefMapTest.scala
Labels: performance

#8469 Scope: use direct iterator to checkNoAbstractMembers
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/reflect/scala/reflect/internal/Scopes.scala
Labels: performance:do_not_allocate

#8463 TypeHistory: use mutability to avoid allocations.
  src/reflect/scala/reflect/internal/Symbols.scala
Labels: performance:do_not_allocate

#8485 Avoid Option.WithFilter allocations.
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: performance:do_not_allocate

#8482 ByteCode Body Builder: avoid middle lists allocations.
  src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
Labels: performance:do_not_allocate

#8487 Introduce cache for lists of WildcardTypes to reduce allocations in compiler
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/Types.scala
Labels: performance:do_not_allocate

#8437 Upgrade Dotty to 0.19.0-RC1
  project/DottySupport.scala
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/SeqView.scala
  src/library/scala/collection/immutable/Vector.scala
  src/library/scala/concurrent/impl/Promise.scala
  src/library/scala/util/control/NonFatal.scala
Labels: build

#8488 Cache the wildcard substituted implicit type
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Labels: performance

#8490 Reduce allocations in the backend
  src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeIdiomatic.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeSkelBuilder.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromClassfile.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala
  src/compiler/scala/tools/nsc/backend/jvm/CoreBTypes.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/reflect/scala/reflect/internal/util/Collections.scala
  test/junit/scala/tools/nsc/backend/jvm/BTypesTest.scala
Labels: performance:do_not_allocate

#8446 2.13 version of Map.hashCode optimizations
  build.sbt
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/ListMap.scala
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/SeqMap.scala
  src/library/scala/collection/immutable/TreeMap.scala
  src/library/scala/util/hashing/MurmurHash3.scala
  src/testkit/scala/tools/testkit/AllocationTest.scala
  test/junit/scala/collection/immutable/MapHashcodeTest.scala
Labels: library:collections

#8494 Override IndexedSeq.{head, headOption} to avoid iterator allocation
  src/library/scala/collection/IndexedSeq.scala
Labels: library:collections, performance:do_not_allocate

#8504 UnPickler: avoid Boxed Integers and Tuple2 allocations.
  src/reflect/scala/reflect/internal/pickling/UnPickler.scala
Labels: performance:do_not_allocate

#8492 Reduce allocations in some hot Symbol queries
  src/compiler/scala/tools/nsc/ast/TreeGen.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/internal/tpe/TypeComparers.scala
  src/reflect/scala/reflect/internal/transform/Erasure.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
Labels: performance:do_not_allocate

#8513 Clean up sizeCompare
  src/library/scala/collection/Iterable.scala
Labels: library:collections

#8496 Avoid awkward silences during CI builds which Travis finds unacceptable
  .travis.yml
  build.sbt
  project/TravisOutput.scala
Labels: build
