Repository scala/scala, pull requests merged in 2019-11, with the labels that each got.

#8475 [Scaladoc] scala.util.Using code samples are a bit simplified
  src/library/scala/util/Using.scala
Labels: documentation

#8528 workaround for SDKMAN getting stuck
  .travis.yml
Labels: build

#8502 Removes the use of a CountDownLatch in Future.never so ScalaJS will b…
  src/library/scala/concurrent/Future.scala
Labels: regression

#8523 ZipArchiveFileLookup: avoid Option.withfilter
  src/compiler/scala/tools/nsc/classpath/ZipArchiveFileLookup.scala
Labels: performance:do_not_allocate

#8514 Mark single-use field MUTABLE for nullification
  src/compiler/scala/tools/nsc/transform/Mixin.scala
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: welcome

#8500 Show expected in AssertUtil.assertThrows
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/junit/scala/tools/testkit/AssertThrowsTest.scala
  test/scalacheck/scala/reflect/quasiquotes/QuasiquoteProperties.scala
Labels: tests

#8518 Upgrade Dotty to 0.20.0-RC1
  project/DottySupport.scala
Labels: build

#8530 spec: Replace "first-order types" with "proper types"
  spec/03-types.md
  spec/04-basic-declarations-and-definitions.md
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
Labels: documentation

#8533 ignoring some useless things
  src/compiler/scala/tools/nsc/classpath/AggregateClassPath.scala
  src/compiler/scala/tools/nsc/plugins/Plugin.scala
Labels: build, welcome

#8536 [nomerge] workaround for SDKMAN getting stuck
  .travis.yml
Labels: build

#8546 Bump Xmx for type-tag-leak
  test/files/run/type-tag-leak.javaopts
Labels: build

#8451 Matching strings makes switches
  src/compiler/scala/tools/nsc/transform/CleanUp.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchOptimization.scala
  test/files/run/string-switch-defaults-null.check
  test/files/run/string-switch-defaults-null.scala
  test/files/run/string-switch-pos.check
  test/files/run/string-switch-pos.scala
  test/files/run/string-switch.check
  test/files/run/string-switch.scala
  test/junit/scala/tools/nsc/transform/patmat/PatmatBytecodeTest.scala
Labels: performance, release-notes

#8519 PickleBuffer: avoid middle stops when growing up
  src/reflect/scala/reflect/internal/pickling/PickleBuffer.scala
Labels: performance

#8547 "Improve" root import filter for universal members
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/reflect/scala/reflect/internal/Definitions.scala
Labels: performance

#8512 Avoid some Tuple2 allocation in implicits and inline info bookkeeping
  src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromClassfile.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/InlineInfoAttribute.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  test/junit/scala/tools/nsc/backend/jvm/opt/ScalaInlineInfoTest.scala
Labels: WIP, performance:do_not_allocate

#8548 Mention `enableOptimizer` and `setupPublishCore` in the README
  README.md
Labels: documentation

#8526 BigInt tests
  src/library/scala/math/BigInt.scala
  test/junit/scala/math/BigIntTest.scala
  test/junit/scala/math/DoubleTest.scala
  test/scalacheck/scala/math/BigIntProperties.scala
Labels: build, library:base

#8539 Less yammering, more hammering: fix two broken windows tests
  src/testkit/scala/tools/testkit/TempDir.scala
  test/files/run/t11802-pluginsdir/t11802.scala
  test/junit/scala/reflect/io/ZipArchiveTest.scala
  test/junit/scala/tools/nsc/classpath/ZipAndJarFileLookupFactoryTest.scala
Labels: build

#8560 [nomerge] Backport windows test fix
  test/files/run/t11802-pluginsdir/t11802.scala
Labels: build

#8557 Override stringPrefix for SeqMap
  src/library/scala/collection/SeqMap.scala
  test/scalacheck/SeqMap.scala
Labels: library:collections
