Repository scala/scala, pull requests merged in 2019-09, with the labels that each got.

#8185 Make to able search FunctionN, ProductN and etc for N > 2
  src/scaladoc/scala/tools/nsc/doc/Settings.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/IndexScript.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
  src/scaladoc/scala/tools/nsc/doc/model/diagram/DiagramFactory.scala
Labels: tool:scaladoc, welcome

#8134 [#11559] Fix HashMap.merged behaviour for case where left HashMap size=1
  src/library/scala/collection/immutable/HashMap.scala
  test/junit/scala/collection/immutable/HashMapTest.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashMapProperties.scala
Labels: bug fix, documentation, library:collections

#8317 [backport] deprecate symbolic foldLeft (/:)
  src/library/scala/collection/GenTraversableOnce.scala
  src/library/scala/collection/TraversableOnce.scala
  src/library/scala/collection/parallel/ParIterableLike.scala
  test/files/run/collections.scala
  test/files/run/colltest1.scala
  test/files/run/t2818.scala
Labels: library:collections

#8397 [backport] Backport phase assembly regression fix
  src/compiler/scala/tools/nsc/PhaseAssembly.scala
  test/benchmarks/src/main/scala/scala/tools/nsc/PhaseAssemblyBenchmark.scala
  test/files/neg/t7622-cyclic-dependency.check
  test/junit/scala/tools/nsc/PhaseAssemblyTest.scala
Labels: prio:blocker

#8405 Merge 2.12.x to 2.13.x [ci: last-only]
  build.sbt
  src/compiler/scala/tools/nsc/CompilerCommand.scala
  src/compiler/scala/tools/nsc/backend/jvm/ClassfileWriters.scala
  src/compiler/scala/tools/nsc/classpath/AggregateClassPath.scala
  src/compiler/scala/tools/nsc/classpath/ClassPath.scala
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/compiler/scala/tools/nsc/classpath/VirtualDirectoryClassPath.scala
  src/compiler/scala/tools/nsc/classpath/ZipAndJarFileLookupFactory.scala
  src/compiler/scala/tools/nsc/classpath/ZipArchiveFileLookup.scala
  src/compiler/scala/tools/nsc/settings/AbsSettings.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/util/ClassPath.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/io/ZipArchive.scala
  src/reflect/scala/reflect/runtime/SynchronizedSymbols.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
  src/scaladoc/scala/tools/nsc/doc/html/HtmlFactory.scala
  test/benchmarks/src/main/scala/scala/tools/nsc/AggregateClassPathBenchmark.scala
  test/files/run/colltest1.check
  test/files/run/colltest1.scala
  test/files/run/settings-parse.check
  test/junit/scala/reflect/runtime/ThreadSafetyTest.scala
  test/junit/scala/tools/nsc/classpath/AggregateClassPathTest.scala
  test/junit/scala/tools/nsc/settings/SettingsTest.scala
Labels: prio:blocker

#8408 Extend the Gradle / sbt 0.13 leniency to Windows
  src/compiler/scala/tools/nsc/Reporting.scala
Labels: release-notes

#8194 [#11600] Vector.from(ArraySeq) copies elems rather than reusing unsafeArray
  src/library/scala/collection/immutable/Vector.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: bug fix, library:collections, prio:blocker, release-notes

#8422 Avoid dotty compiler crash
  src/library/scala/collection/mutable/Map.scala
Labels: prio:blocker

#8335 Reduce allocations in Typer
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: performance

#8420 Clean up test that test is not elided
  src/partest/scala/tools/partest/Util.scala
  test/files/run/t6331b.check
  test/files/run/t6331b.scala
Labels: build

#8411 Dont create tuples when generating hashcodes for immutable maps
  src/library/mima-filters/2.12.0.forwards.excludes
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/ListMap.scala
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/RedBlackTree.scala
  src/library/scala/collection/immutable/TreeMap.scala
  src/library/scala/util/hashing/MurmurHash3.scala
  test/junit/scala/collection/immutable/MapHashcodeTest.scala
  test/junit/scala/tools/testing/AllocationTest.scala
Labels: library:collections

#8412 Improve performance of BitSet.toBitMask (and .range*)
  src/library/scala/collection/immutable/BitSet.scala
  src/library/scala/collection/mutable/BitSet.scala
Labels: library:collections

#8414 Remove immutable.RedBlackTree.countInRange (dead code)
  build.sbt
  src/library/scala/collection/immutable/RedBlackTree.scala
Labels: library:collections

#8402 Wait for it
  src/partest/scala/tools/partest/TestUtil.scala
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/files/jvm/duration-tck.scala
  test/files/jvm/scala-concurrent-tck.check
  test/files/jvm/scala-concurrent-tck.scala
Labels: build

#8392 Add more termination notes
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/immutable/LazyList.scala
Labels: documentation

#8375 Avoid ObjectRef overhead for effectively final case vars
  src/compiler/scala/tools/nsc/transform/LambdaLift.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchOptimization.scala
  test/files/run/sd187.check
Labels: performance

#8364 Enable autoAPIMappings in build
  build.sbt
Labels: build, documentation

#8444 Use travis-wait-enhanced
  .travis.yml
Labels: build
