Repository scala/scala, pull requests merged in 2020-05, with the labels that each got.

#8950 bump sbt-whitesource to 0.1.18 (was 0.1.16)
  project/plugins.sbt
Labels: build

#8940 Deprecate varargs -= in Shrinkable
  src/library/scala/collection/mutable/Growable.scala
  src/library/scala/collection/mutable/Shrinkable.scala
Labels: library:collections

#8923 Warning summary respects -nowarn
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/reporters/ConsoleReporter.scala
  src/compiler/scala/tools/nsc/reporters/Reporter.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/partest/scala/tools/partest/DirectTest.scala
  src/partest/scala/tools/partest/nest/Runner.scala
  src/partest/scala/tools/partest/nest/StreamCapture.scala
  src/reflect/scala/reflect/internal/Reporting.scala
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  src/scaladoc/scala/tools/nsc/doc/ScaladocAnalyzer.scala
  test/files/neg/t11952.check
  test/files/neg/t11952.scala
  test/files/neg/t11952b.check
  test/files/neg/t11952b.scala
  test/files/pos/t11952.scala
  test/files/run/ReplacementMatching.scala
  test/files/run/t6178.check
  test/files/run/t6178.scala
  test/junit/scala/util/matching/RegexTest.scala
  test/scaladoc/run/t5527.scala
Labels: prio:blocker

#8938 Respect uncheckedVariance in higher-kinded types
  src/reflect/scala/reflect/internal/Variances.scala
  test/files/pos/variance-holes.scala
Labels: prio:blocker

#8931 Optimise ArraySeq concatenation
  src/library/scala/collection/immutable/ArraySeq.scala
  test/junit/scala/collection/immutable/ArraySeqTest.scala
Labels: library:collections, performance

#8946 Avoid boxing in ArraySeq.{appended,updated,prepended}
  src/library/scala/collection/immutable/ArraySeq.scala
  test/junit/scala/collection/immutable/ArraySeqTest.scala
Labels: library:collections

#8942 append trailing / when processing unicode escapes
  src/library/scala/StringContext.scala
  test/files/pos/t11966.scala
  test/files/run/literals.scala
Labels: prio:blocker

#8922 Fix exception running scaladoc using JDK11 on Windows
  src/scaladoc/scala/tools/nsc/doc/model/MemberLookup.scala
Labels: release-notes

#8957 reduce allocation from SortedSet/Map
  src/library/scala/collection/generic/SortedMapFactory.scala
  src/library/scala/collection/generic/SortedSetFactory.scala
  src/library/scala/collection/immutable/SortedMap.scala
  src/library/scala/collection/immutable/SortedSet.scala
  test/junit/scala/collection/immutable/SortedMapTest.scala
  test/junit/scala/collection/immutable/SortedSetTest.scala
Labels: library:collections, performance:do_not_allocate

#8966 in build, use sbt slash syntax throughout
  build.sbt
  project/AutomaticModuleName.scala
  project/DottySupport.scala
  project/License.scala
  project/Osgi.scala
  project/ScaladocSettings.scala
  project/ScriptCommands.scala
  project/TestJDeps.scala
  project/TestJarSize.scala
  project/VersionUtil.scala
  project/plugins.sbt
Labels: build

#8875 improvement to GenMap #equals
  src/library/scala/collection/GenMapLike.scala
Labels: library:collections, performance:do_not_allocate

#8964 clamp down on warnings in REPL code
  build.sbt
  src/interactive/scala/tools/nsc/interactive/Global.scala
  src/library/scala/runtime/NonLocalReturnControl.scala
  src/repl/scala/tools/nsc/interpreter/Imports.scala
Labels: build

#8963 upgrade jQuery to 3.5.1 (was 3.4.1)
  build.sbt
  doc/LICENSE.md
  doc/License.rtf
  doc/licenses/mit_jquery.txt
  project/ScaladocSettings.scala
  spec/_layouts/default.yml
  spec/_layouts/toc.yml
  src/reflect/scala/reflect/internal/Trees.scala
  src/scaladoc/scala/tools/nsc/doc/html/HtmlFactory.scala
Labels: tool:scaladoc

#8929 Optimise IndexedSeqOps.foldRight
  src/library/scala/collection/IndexedSeq.scala
Labels: library:collections, performance

#8762 Avoid recomputing key hashes in mutable.Hash{Map,Set}.hashCode
  src/library/scala/collection/mutable/HashMap.scala
  src/library/scala/collection/mutable/HashSet.scala
Labels: library:collections, performance

#8849 Exclude sig files in Symbol.sourceFile
  src/reflect/scala/reflect/internal/Symbols.scala
Labels: release-notes

#8978 Fix condition where subtraction can overflow
  src/library/scala/collection/immutable/Vector.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: library:collections, prio:blocker

#8991 Syntax clean up indicated by -Xsource:3 [ci: last-only]
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchWarnings.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala
  src/compiler/scala/tools/nsc/typechecker/TreeCheckers.scala
  src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/interactive/scala/tools/nsc/interactive/Global.scala
  src/library/scala/sys/process/ProcessBuilderImpl.scala
  src/partest/scala/tools/partest/nest/Opt.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/util/Collections.scala
  src/reflect/scala/reflect/internal/util/OwnerOnlyChmod.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/Reporter.scala
  src/repl/scala/tools/nsc/interpreter/ReplGlobal.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
  src/scalap/scala/tools/scalap/scalax/rules/Memoisable.scala
  test/junit/scala/SerializationStabilityTest.scala
  test/junit/scala/collection/IteratorTest.scala
  test/junit/scala/collection/ReusableBuildersTest.scala
  test/junit/scala/collection/SetMapConsistencyTest.scala
  test/junit/scala/collection/immutable/RangeConsistencyTest.scala
  test/junit/scala/collection/immutable/RangeTest.scala
  test/junit/scala/collection/immutable/StreamTest.scala
  test/junit/scala/collection/immutable/VectorTest.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
  test/junit/scala/collection/mutable/ArraySeqTest.scala
  test/junit/scala/collection/mutable/BitSetTest.scala
  test/junit/scala/concurrent/FutureTest.scala
  test/junit/scala/io/SourceTest.scala
  test/junit/scala/math/BigDecimalTest.scala
  test/junit/scala/reflect/internal/TypesTest.scala
  test/junit/scala/reflect/internal/util/FileUtilsTest.scala
  test/junit/scala/reflect/internal/util/WeakHashSetTest.scala
  test/junit/scala/tools/nsc/reporters/ConsoleReporterTest.scala
  test/junit/scala/util/SortingTest.scala
  test/scalacheck/duration.scala
Labels: build

#8992 Guard against unexpected flags files in partest
  src/interactive/scala/tools/nsc/interactive/tests/InteractiveTestSettings.scala
  src/partest/scala/tools/partest/nest/Runner.scala
  test/files/presentation/ide-t1000976.flags
  test/files/presentation/ide-t1000976/Test.scala
  test/files/presentation/t8085.flags
  test/files/presentation/t8085/Test.scala
  test/files/presentation/t8085b.flags
  test/files/presentation/t8085b/Test.scala
  test/macro-annot/pos.flags
  test/macro-annot/run.flags
Labels: build

#8987 Silence warn-any in test
  test/junit/scala/collection/immutable/ArraySeqTest.scala
Labels: build

#8796 Updated docs for `Constant` post removal of `LiteralArgument`
  src/reflect/scala/reflect/api/Constants.scala
Labels: documentation

#8985 Increase laziness of #:: for LazyList
  src/library/scala/collection/immutable/LazyList.scala
  test/junit/scala/collection/immutable/LazyListLazinessTest.scala
  test/junit/scala/collection/immutable/LazyListTest.scala
Labels: bug fix, library:collections, release-notes

#9001 minor cleanup: 'delegate' isn't reserved in Dotty anymore
  src/library/scala/collection/Factory.scala
  src/library/scala/concurrent/Future.scala
Labels: build

#9013 Close Source.fromFile
  src/library/scala/concurrent/package.scala
  src/library/scala/io/Source.scala
  src/partest/scala/tools/partest/nest/FileManager.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/GenerateVectorBenchmark2Charts.scala
  test/files/jvm/t2104.scala
  test/files/run/t4671.check
  test/files/run/t4671.scala
  test/files/run/t6240-universe-code-gen.scala
  test/files/specialized/fft.scala
Labels: build

#8937 Upgrade Dotty to 0.24.0-RC1
  project/DottySupport.scala
  src/library/scala/Console.scala
  src/library/scala/collection/Map.scala
  src/library/scala/collection/immutable/BitSet.scala
  src/library/scala/collection/mutable/PriorityQueue.scala
Labels: build

#9011 Improve documentation
  CONTRIBUTING.md
  README.md
  spec/03-types.md
  spec/05-classes-and-objects.md
  spec/06-expressions.md
  spec/07-implicits.md
  spec/10-xml-expressions-and-patterns.md
  spec/11-annotations.md
  spec/12-the-scala-standard-library.md
  spec/15-changelog.md
Labels: documentation

#9018 Make the spelling of "type class" consistent
  src/library/scala/util/Using.scala
  test/files/neg/t9963.scala
  test/files/pos/t10238.scala
  test/files/pos/t5862.scala
Labels: documentation
