Repository scala/scala, pull requests merged in 2020-10, with the labels that each got.

#9096 Fix a link to the separately shipped scala-reflect library
  src/library/rootdoc.txt
Labels: documentation

#9221 Fixes implicit javaBigDecimal2bigDecimal to return null, when a null is used by the implicit
  src/library/scala/math/BigDecimal.scala
  test/junit/scala/math/BigDecimalTest.scala
Labels: library:base

#9233 Try to parse Duration as Long before parsing as Double
  src/library/scala/concurrent/duration/Duration.scala
  test/files/jvm/duration-tck.scala
Labels: library:base

#9234 Make SeqView.Sorted slightly less lazy
  build.sbt
  src/library/scala/collection/SeqView.scala
Labels: library:collections

#9232 Optimise factories for Array-based collections
  build.sbt
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/immutable/ArraySeq.scala
  src/library/scala/collection/immutable/WrappedString.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  src/library/scala/collection/mutable/ArrayDeque.scala
  src/library/scala/collection/mutable/ArraySeq.scala
  src/library/scala/collection/mutable/PriorityQueue.scala
Labels: library:collections, performance

#9085 Deprecate empty-paren (nilary) prefix unary operator
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/reflect/scala/reflect/internal/Printers.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/neg/prefix-unary-nilary-deprecation.check
  test/files/neg/prefix-unary-nilary-deprecation.scala
  test/files/neg/prefix-unary-nilary-removal.check
  test/files/neg/prefix-unary-nilary-removal.scala
Labels: release-notes

#9244 Revert "Dealias when necessary to substitute symbols"
  src/reflect/scala/reflect/internal/tpe/TypeMaps.scala
  test/files/pos/t11383.scala
  test/files/pos/t9222.scala
Labels: prio:blocker

#7960 Specialize attachments for common case of zero or one attachments.
  build.sbt
  src/reflect/scala/reflect/internal/util/Position.scala
  src/reflect/scala/reflect/macros/Attachments.scala
  test/junit/scala/reflect/macros/AttachmentsTest.scala
Labels: performance

#9235 Clean up warnings in library module
  build.sbt
  src/library/scala/App.scala
  src/library/scala/PartialFunction.scala
  src/library/scala/collection/BitSet.scala
  src/library/scala/collection/IndexedSeq.scala
  src/library/scala/collection/IndexedSeqView.scala
  src/library/scala/collection/JavaConverters.scala
  src/library/scala/collection/LinearSeq.scala
  src/library/scala/collection/Map.scala
  src/library/scala/collection/MapView.scala
  src/library/scala/collection/Seq.scala
  src/library/scala/collection/SeqMap.scala
  src/library/scala/collection/SeqView.scala
  src/library/scala/collection/Set.scala
  src/library/scala/collection/SortedMap.scala
  src/library/scala/collection/SortedSet.scala
  src/library/scala/collection/View.scala
  src/library/scala/collection/immutable/BitSet.scala
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/IntMap.scala
  src/library/scala/collection/immutable/LongMap.scala
  src/library/scala/collection/immutable/Stream.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayDeque.scala
  src/library/scala/collection/mutable/Buffer.scala
  src/library/scala/collection/mutable/HashMap.scala
  src/library/scala/collection/mutable/LinkedHashMap.scala
  src/library/scala/collection/mutable/LinkedHashSet.scala
  src/library/scala/collection/mutable/ListBuffer.scala
  src/library/scala/collection/mutable/LongMap.scala
  src/library/scala/collection/mutable/OpenHashMap.scala
  src/library/scala/collection/mutable/Queue.scala
  src/library/scala/collection/mutable/Stack.scala
  src/library/scala/collection/mutable/WeakHashMap.scala
  src/library/scala/concurrent/impl/Promise.scala
  src/library/scala/io/Source.scala
  src/library/scala/jdk/Accumulator.scala
  src/library/scala/jdk/DoubleAccumulator.scala
  src/library/scala/jdk/IntAccumulator.scala
  src/library/scala/jdk/LongAccumulator.scala
  src/library/scala/math/BigInt.scala
  src/library/scala/ref/ReferenceWrapper.scala
  src/library/scala/reflect/ClassManifestDeprecatedApis.scala
  src/library/scala/reflect/ClassTag.scala
  src/library/scala/reflect/Manifest.scala
  src/library/scala/runtime/ScalaNumberProxy.scala
  src/library/scala/sys/process/BasicIO.scala
  src/library/scala/sys/process/ProcessBuilderImpl.scala
  src/library/scala/sys/process/ProcessImpl.scala
  src/library/scala/sys/process/package.scala
  src/library/scala/util/ChainingOps.scala
  src/library/scala/util/hashing/MurmurHash3.scala
  test/junit/scala/sys/process/PipedProcessTest.scala
Labels: internal

#9243 Update Syntax-Summary to reflect syntax laid out in previous chapters
  spec/13-syntax-summary.md
Labels: documentation

#8794 RedBlackTree with fast mutable builder [ci: last-only]
  build.sbt
  src/library/scala/collection/generic/Subtractable.scala
  src/library/scala/collection/immutable/OldRedBlackTree.scala
  src/library/scala/collection/immutable/RedBlackTree.scala
  src/library/scala/collection/immutable/TreeMap.scala
  src/library/scala/collection/immutable/TreeSet.scala
  test/files/run/red-black-tree-serial-new.check
  test/files/run/red-black-tree-serial-new.javaopts
  test/files/run/red-black-tree-serial-new/NewTreeSerialFormat.scala
  test/files/run/red-black-tree-serial.check
  test/files/run/red-black-tree-serial/TreeSerialFormat.scala
  test/files/run/t8549.scala
  test/junit/scala/collection/immutable/MapTest.scala
  test/junit/scala/collection/immutable/RedBlackTreeSerialFormat.scala
  test/junit/scala/collection/immutable/SortedMapTest.scala
  test/junit/scala/collection/immutable/SortedSetTest.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
  test/junit/scala/collection/immutable/TreeSetTest.scala
  test/junit/scala/collection/mutable/TreeSetTest.scala
  test/scalacheck/redblacktree.scala
Labels: library:collections, performance, performance:do_not_allocate, prio:blocker

#9174 [bug#12009] Make ListBuffer's iterator fail-fast
  build.sbt
  src/compiler/scala/tools/nsc/transform/async/AnfTransform.scala
  src/library/scala/collection/mutable/Growable.scala
  src/library/scala/collection/mutable/ListBuffer.scala
  src/library/scala/collection/mutable/MutationTracker.scala
  src/library/scala/collection/mutable/Shrinkable.scala
  test/benchmarks/src/main/scala/scala/collection/mutable/ConstructionBenchmark.scala
  test/benchmarks/src/main/scala/scala/collection/mutable/ListBufferBenchmark.scala
  test/files/run/t3088.scala
  test/files/run/t8153.check
  test/files/run/t8153.scala
  test/junit/scala/collection/mutable/ListBufferTest.scala
  test/junit/scala/collection/mutable/MutationTrackerTest.scala
  test/junit/scala/collection/mutable/MutationTrackingTest.scala
  test/scalacheck/scala/tools/nsc/scaladoc/HtmlFactoryTest.scala
Labels: library:collections, release-notes

#9249 Fix ArrayBuffer incorrectly reporting the upper bound in IndexOutOfBoundsException
  src/library/scala/collection/mutable/ArrayBuffer.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
Labels: library:collections

#9246 fixes scala/bug #11676 un-deprecate useful StringOps operations
  src/library/scala/collection/StringOps.scala
Labels: library:collections

#9259 [backport] always keep a field for `private[this] var` class parameters
  src/compiler/scala/tools/nsc/transform/Constructors.scala
  test/files/run/t12002.check
  test/files/run/t12002.scala
Labels: prio:blocker

#9262 ListMap is reverse oriented, so use that for foldRight (forward-port)
  src/library/scala/collection/immutable/ListMap.scala
  test/junit/scala/collection/immutable/ListMapTest.scala
Labels: library:collections

#9264 update nightly build information in README.md
  README.md
Labels: documentation, internal

#9265 language spec: document the un-updated status of the changelog
  spec/15-changelog.md
Labels: documentation

#9268 Allow forks to run bootstrapped tests on Travis CI
  .travis.yml
  README.md
  admin/init.sh
  build.sbt
  scripts/travis-publish-spec.sh
Labels: internal

#9274 build/CI: add comments, remove a redundancy
  .travis.yml
  build.sbt
Labels: internal

#9273 mention scala-library-next in readme
  README.md
Labels: documentation, internal

#9277 Fix attempt for "max recursion depth" in Typer
  build.sbt
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: internal

#8948 [nomerge] Reduce allocations in groupBy
  build.sbt
  src/library/scala/collection/TraversableLike.scala
  src/library/scala/collection/mutable/HashMap.scala
  src/partest/scala/tools/partest/StubErrorMessageTest.scala
  test/benchmarks/src/main/scala/scala/collection/GroupByBenchmark.scala
  test/files/run/StubErrorReturnTypePolyFunction.check
  test/files/run/StubErrorTypeDef.check
Labels: library:collections

#9283 document branching strategy in readme
  README.md
Labels: documentation, internal

#9278 Fix attempt for flaky foldRightAllocations test
  test/junit/scala/collection/immutable/ListMapTest.scala
Labels: internal

#9282 Fix another patmat max recursion depth
  src/compiler/scala/tools/nsc/backend/jvm/BCodeSyncAndTry.scala
Labels: internal
