Repository scala/scala, pull requests merged in 2020-08, with the labels that each got.

#9151 upgrade JLine to 3.16.0 (was 3.15.0)
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: tool:REPL

#9165 remove unused import
  src/library/scala/collection/immutable/Map.scala
Labels: internal

#8986 Map ++ without CBF should use the same optimised path as ++ with CBF
  build.sbt
  src/library/scala/collection/immutable/Map.scala
Labels: library:collections, performance

#9173 Simplify flatten
  src/library/scala/collection/Iterable.scala
Labels: library:collections

#9159 [2.12] [backport] Improve IntelliJ project configuration
  src/intellij/benchmarks.iml.SAMPLE
  src/intellij/scala-build.iml.SAMPLE
  src/intellij/test.iml.SAMPLE
Labels: internal

#9147 Check all bindings exhaustively, e.g. tuples components
  src/compiler/scala/tools/nsc/transform/patmat/Logic.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  test/files/neg/t10019.check
  test/files/neg/t10019.flags
  test/files/neg/t10019.scala
  test/scaladoc/run/t10673.scala
Labels: release-notes

#9091 Small optimisations - some faster array copies, reuse empty arrays
  build.sbt
  src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/AliasingFrame.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/LocalOpt.scala
  src/library/scala/Array.scala
  src/library/scala/collection/concurrent/TrieMap.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  src/library/scala/collection/mutable/BitSet.scala
  src/library/scala/collection/mutable/WrappedArrayBuilder.scala
  src/library/scala/collection/parallel/mutable/package.scala
  src/library/scala/reflect/ClassTag.scala
  src/reflect/scala/reflect/internal/pickling/PickleBuffer.scala
  src/repl-jline/scala/tools/nsc/interpreter/jline/JLineDelimiter.scala
Labels: library:collections

#9177 Move reflection-related utils from AssertUtil to new ReflectUtil.
  src/testkit/scala/tools/testkit/AssertUtil.scala
  src/testkit/scala/tools/testkit/ReflectUtil.scala
  test/junit/scala/collection/immutable/IntMapTest.scala
  test/junit/scala/collection/immutable/LongMapTest.scala
Labels: internal
