Repository scala/scala, pull requests merged in 2020-11, with the labels that each got.

#9291 RedBlackTree with fast mutable builder
  build.sbt
  src/library/scala/collection/generic/Subtractable.scala
  src/library/scala/collection/immutable/RedBlackTree.scala
  src/library/scala/collection/immutable/TreeMap.scala
  src/library/scala/collection/immutable/TreeSet.scala
  test/files/run/red-black-tree-serial.check
  test/junit/scala/collection/immutable/MapTest.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
  test/junit/scala/collection/immutable/TreeSetTest.scala
  test/junit/scala/collection/mutable/TreeSetTest.scala
  test/scalacheck/redblacktree.scala
Labels: library:collections

#9293 Stick TASTy reading behind a -Ytasty-reader flag
  doc/internal/tastyreader.md
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/tastytest/scala/tools/tastytest/TastyTest.scala
Labels: prio:blocker, release-notes

#9281 Travis CI: make a command error fatal
  .travis.yml
Labels: internal

#9300 Revert "Restore Global.reporter()Reporter"
  src/compiler/scala/tools/nsc/Global.scala
Labels: internal

#9292 Make the CharSequence wrappers in Predef non-implicit, for JDK 15
  src/library/scala/Predef.scala
  src/library/scala/collection/mutable/StringBuilder.scala
  src/reflect/scala/reflect/internal/Names.scala
  test/junit/scala/ArrayTest.scala
  test/junit/scala/CharSequenceImplicitsTests.scala
Labels: prio:blocker, release-notes

#9298 [nomerge] Emit warnings in the REPL
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  test/files/jvm/interpreter.check
  test/files/run/constrained-types.check
  test/files/run/reflection-magicsymbols-repl.check
  test/files/run/repl-bare-expr.check
  test/files/run/repl-class-based-outer-pointers.check
  test/files/run/repl-no-imports-no-predef-power.check
  test/files/run/repl-no-imports-no-predef.check
  test/files/run/repl-parens.check
  test/files/run/repl-power.check
  test/files/run/t11402.check
  test/files/run/t11402.scala
  test/files/run/t4172.check
  test/files/run/t4542.check
  test/files/run/t4594-repl-settings.check
  test/files/run/t4710.check
  test/files/run/t6329_repl.check
  test/files/run/t6329_repl_bug.check
  test/files/run/t7319.check
  test/files/run/t7747-repl.check
  test/files/run/xMigration.check
Labels: prio:blocker

#9299 Switch off exhaustivity warnings for unsealed types (by default)
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  test/files/neg/patmat-seq-neg.check
  test/files/neg/t11102.check
  test/files/neg/t11746.check
  test/files/neg/t5365c.scala
  test/files/neg/t5898.check
  test/files/neg/t7623.scala
  test/files/neg/t8597.scala
  test/files/neg/t8597b.scala
  test/files/neg/t8731.scala
  test/files/neg/tailrec-4.check
  test/files/neg/tailrec-4.scala
  test/files/neg/unchecked-refinement.check
  test/files/neg/unchecked3.scala
  test/files/neg/virtpatmat_unreach_select.check
  test/files/pos/t10680.scala
  test/files/run/matchonstream.check
  test/files/run/patmat-behavior.check
  test/files/run/patmatnew.check
  test/files/run/t6077_patmat_cse_irrefutable.scala
  test/files/run/t6288.check
  test/files/run/t9644.check
  test/files/run/unapply.check
  test/files/run/unapplyArray.check
  test/files/run/uncheckedStable.check
Labels: release-notes

#9295 Add a regression test for scala/bug#12192
  test/files/pos/t12142.scala
Labels: internal

#9302 Make annotation typechecking lazier
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/reflect/scala/reflect/internal/AnnotationInfos.scala
  test/files/pos/annotation-cycle.scala
  test/files/pos/t11870.scala
  test/files/pos/unchecked-stable-cyclic-error.scala
Labels: backport candidate

#9279 Allow using classOf with object type
  src/reflect/scala/reflect/internal/Types.scala
  test/files/pos/classOfObjectType/AnnotationWithClassType.java
  test/files/pos/classOfObjectType/Foo.scala
  test/files/run/classOfObjectType.scala
Labels: release-notes

#9312 Patterns under irrefutable extractors are fixed
  test/files/neg/t10502.check
  test/files/neg/t10502.scala
Labels: internal

#9296 Introduce ExecutionContext.opportunistic for use in apps
  build.sbt
  src/library/scala/concurrent/BlockContext.scala
  src/library/scala/concurrent/ExecutionContext.scala
Labels: release-notes

#9318 Fix regressions in immutable.TreeMap merge errors from 2.12.x
  src/library/scala/collection/immutable/RedBlackTree.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
Labels: prio:blocker

#9322 [backport] Make the CharSequence wrappers in Predef non-implicit, for JDK 15
  src/library/scala/Predef.scala
  src/library/scala/collection/mutable/StringBuilder.scala
  src/reflect/scala/reflect/internal/Names.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/run/array-charSeq.scala
  test/junit/scala/ArrayTest.scala
Labels: prio:blocker, release-notes

#9328 Re-STARR onto 2.13.4 & move+truncate the MiMa filters
  build.sbt
  project/BuildSettings.scala
  project/MimaFilters.scala
  versions.properties
Labels: internal

#9329 post re-STARR adjustments to warnings
  src/library/scala/math/BigInt.scala
  src/reflect/scala/reflect/internal/Constants.scala
Labels: internal

#9331 use slash syntax throughout build.sbt
  build.sbt
Labels: internal

#9330 uncomment an assert in compiler after re-STARR
  src/compiler/scala/tools/nsc/transform/Mixin.scala
Labels: internal

#9333 Tweaks for warnings
  src/library/scala/math/BigDecimal.scala
  src/library/scala/util/matching/Regex.scala
  test/junit/scala/collection/immutable/MapTest.scala
  test/junit/scala/collection/mutable/MutationTrackingTest.scala
  test/junit/scala/collection/mutable/OpenHashMapTest.scala
  test/junit/scala/collection/mutable/TreeSetTest.scala
  test/junit/scala/tools/nsc/DeterminismTest.scala
  test/junit/scala/tools/nsc/DeterminismTester.scala
Labels: internal

#9301 bump JUnit and ScalaCheck versions
  build.sbt
  test/files/run/BoxUnboxTest.scala
  test/junit/scala/collection/IteratorTest.scala
  test/junit/scala/collection/StringParsersTest.scala
  test/junit/scala/collection/immutable/HashSetTest.scala
  test/junit/scala/collection/immutable/RangeTest.scala
  test/junit/scala/collection/immutable/StringLikeTest.scala
  test/junit/scala/collection/mutable/BitSetTest.scala
  test/junit/scala/jdk/FunctionConvertersTest.scala
  test/junit/scala/lang/stringinterpol/StringContextTest.scala
  test/junit/scala/reflect/internal/NamesTest.scala
  test/junit/scala/reflect/internal/util/SourceFileTest.scala
  test/junit/scala/tools/nsc/backend/jvm/opt/EmptyLabelsAndLineNumbersTest.scala
  test/junit/scala/tools/nsc/backend/jvm/opt/UnreachableCodeTest.scala
  test/junit/scala/tools/nsc/symtab/StdNamesTest.scala
  test/junit/scala/util/SpecVersionTest.scala
  test/junit/scala/util/matching/RegexTest.scala
  test/scalacheck/scala/collection/FloatFormatTest.scala
  test/scalacheck/scala/collection/IntegralParseTest.scala
  test/scalacheck/scala/collection/IteratorProperties.scala
Labels: internal

#9294 Upgrade to JLine 3.17.1
  versions.properties
Labels: tool:REPL

#9334 remove orphaned RedBlackTree checkfile
  test/files/run/red-black-tree-serial.check
Labels: internal

#9335 fix never-released 2.12.13 regression where Array[Unit].empty caused NPE
  src/library/scala/reflect/ClassTag.scala
  test/junit/scala/ArrayTest.scala
Labels: library:collections

#9202 Upgrade to sbt 1.4.x
  build.sbt
  project/GenerateFunctionConverters.scala
  project/SavedLogs.scala
  project/TestJarSize.scala
  project/build.properties
  project/plugins.sbt
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
  test/jcstress/project/build.properties
Labels: internal

#9275 Refactor ArrayBuffer.ensureSize for testing
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/testkit/scala/tools/testkit/AssertUtil.scala
  src/testkit/scala/tools/testkit/ReflectUtil.scala
  test/files/run/t7880.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
  test/junit/scala/tools/testkit/ReflectUtilTest.scala
Labels: internal

#9338 Enable -Yvalidate-pos in our tests
  build.sbt
Labels: internal

#9257 Restructure ListBuffer to build and insert chains
  src/library/scala/collection/mutable/ListBuffer.scala
  test/junit/scala/collection/mutable/ListBufferTest.scala
Labels: library:collections

#9304 Enable -Werror for more modules
  build.sbt
  src/compiler/scala/reflect/quasiquotes/Reifiers.scala
  src/compiler/scala/tools/nsc/ast/Trees.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/CopyProp.scala
  src/compiler/scala/tools/nsc/tasty/TastyUnpickler.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/compiler/scala/tools/nsc/transform/OverridingPairs.scala
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/compiler/scala/tools/nsc/transform/async/ExprBuilder.scala
  src/compiler/scala/tools/nsc/transform/patmat/Logic.scala
  src/compiler/scala/tools/nsc/transform/patmat/Solving.scala
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/scaladoc/scala/tools/nsc/doc/Index.scala
  src/scaladoc/scala/tools/nsc/doc/ScaladocAnalyzer.scala
  src/scaladoc/scala/tools/nsc/doc/Settings.scala
  src/scaladoc/scala/tools/nsc/doc/base/CommentFactoryBase.scala
  src/scaladoc/scala/tools/nsc/doc/html/HtmlPage.scala
  src/scaladoc/scala/tools/nsc/doc/html/HtmlTags.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/diagram/DotDiagramGenerator.scala
  src/scaladoc/scala/tools/nsc/doc/model/IndexModelFactory.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactoryImplicitSupport.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactoryTypeSupport.scala
  src/scaladoc/scala/tools/nsc/doc/model/diagram/DiagramDirectiveParser.scala
  src/scalap/scala/tools/scalap/Arguments.scala
  src/scalap/scala/tools/scalap/JavaWriter.scala
  src/scalap/scala/tools/scalap/MetaParser.scala
  src/scalap/scala/tools/scalap/scalax/rules/scalasig/ClassFileParser.scala
  src/scalap/scala/tools/scalap/scalax/rules/scalasig/ScalaSig.scala
  src/scalap/scala/tools/scalap/scalax/rules/scalasig/ScalaSigPrinter.scala
Labels: internal

#9340 sbt 1.4.4 (was 1.4.3)
  project/build.properties
  project/plugins.sbt
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
  test/jcstress/project/build.properties
Labels: internal

#9079 Improvements to tab completion results
  src/interactive/scala/tools/nsc/interactive/CompilerControl.scala
  src/interactive/scala/tools/nsc/interactive/Global.scala
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
Labels: tool:REPL

#9332 Travis-CI: don't compile tests during initial build stage
  .travis.yml
  build.sbt
Labels: internal

#9345 Upgrade to Scala 3.0.0-M2
  project/DottySupport.scala
  project/plugins.sbt
Labels: internal

#9347 further speed up Travis-CI PR validation
  .travis.yml
Labels: internal
