Repository scala/scala, pull requests merged in 2020-12, with the labels that each got.

#9323 Fixes for JDK 11
  test/files/neg/checksensible.check
  test/files/neg/checksensible.scala
  test/files/neg/java-import-non-existing-selector.check
  test/files/neg/t10680.check
  test/files/run/t7455.check
  test/scaladoc/run/anyref-doc.check
  test/scaladoc/run/t191.scala
Labels: internal

#9357 Tasty Reader: support 3.0.0-M2
  project/DottySupport.scala
  src/compiler/scala/tools/nsc/tasty/TastyUnpickler.scala
  src/compiler/scala/tools/nsc/tasty/TreeUnpickler.scala
  src/compiler/scala/tools/nsc/tasty/bridge/AnnotationOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/FlagOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/SymbolOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/TypeOps.scala
  src/compiler/scala/tools/tasty/TastyFlags.scala
  src/compiler/scala/tools/tasty/TastyFormat.scala
  src/compiler/scala/tools/tasty/TastyName.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/tasty/neg-move-macros/src-3/MacroCompat.scala
  test/tasty/neg/src-2/TestAlphaAnnot.check
  test/tasty/neg/src-2/TestAlphaAnnot_fail.scala
  test/tasty/neg/src-2/TestCompiletimeQuoteType.check
  test/tasty/neg/src-2/TestIntent.check
  test/tasty/neg/src-2/TestIntent_fail.scala
  test/tasty/neg/src-2/TestSelectWithTarget.check
  test/tasty/neg/src-2/TestSelectWithTarget_fail.scala
  test/tasty/neg/src-2/TestTargetNameAnnot.check
  test/tasty/neg/src-2/TestTargetNameAnnot_fail.scala
  test/tasty/neg/src-3/AlphaAnnot.scala
  test/tasty/neg/src-3/CompiletimeQuoteType.scala
  test/tasty/neg/src-3/SelectWithTarget.scala
  test/tasty/neg/src-3/TargetNameAnnot.scala
  test/tasty/neg/src-3/intent/Position.scala
  test/tasty/pos/src-2/tastytest/TestInfix.scala
  test/tasty/pos/src-3/tastytest/Infix.scala
  test/tasty/run/src-2/tastytest/TestFunctor.scala
  test/tasty/run/src-2/tastytest/TestMonad.scala
  test/tasty/run/src-2/tastytest/TestReader.scala
  test/tasty/run/src-2/tastytest/TestRefinements.scala
  test/tasty/run/src-2/tastytest/TestSymbollicEnums.scala
  test/tasty/run/src-3/tastytest/MacroCompat.scala
  test/tasty/run/src-3/tastytest/Monad.scala
  test/tasty/run/src-3/tastytest/Refinements.scala
  test/tasty/run/src-3/tastytest/SuperOps.scala
Labels: release-notes, tastyreader

#9354 Add -V and -W parameters for scalac task in sbt build of scala
  project/ScalaOptionParser.scala
Labels: internal

#9360 remove empty files
  src/reflect/scala/reflect/internal/Required.scala
  src/reflect/scala/reflect/io/IOStats.scala
  src/repl/scala/tools/nsc/interpreter/ISettings.scala
  test/async/jvm/futures.check
  test/files/run/t1434.check
  test/files/run/t5857.check
  test/files/run/t7439.check
  test/files/run/t9644.check
  test/files/run/unapplyArray.check
  test/files/run/uncheckedStable.check
  test/junit/scala/collection/mutable/SetLikeTest.scala
Labels: internal

#9359 avoid including control characters directly in source code
  src/scaladoc/scala/tools/nsc/doc/base/CommentFactoryBase.scala
Labels: internal

#9370 enable fatal warnings when compiling partest's Java sources
  build.sbt
  src/partest/scala/tools/partest/nest/UnsafeAccess.java
Labels: internal

#9367 Build benchmarks as part of PR validation
  .travis.yml
  test/benchmarks/src/main/scala/scala/collection/mutable/OpenHashMapBenchmark.scala
Labels: internal

#9364 TastyReader: enable opaque types and erase correctly
  src/compiler/scala/tools/nsc/tasty/TastyModes.scala
  src/compiler/scala/tools/nsc/tasty/TreeUnpickler.scala
  src/compiler/scala/tools/nsc/tasty/bridge/ContextOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/TreeOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/TypeOps.scala
  src/reflect/scala/reflect/internal/StdAttachments.scala
  src/reflect/scala/reflect/internal/transform/Erasure.scala
  test/tasty/neg/src-2/TestLogarithms.check
  test/tasty/neg/src-2/TestLogarithms_fail.scala
  test/tasty/neg/src-2/TestNames.check
  test/tasty/neg/src-2/TestNames_fail.scala
  test/tasty/neg/src-3/Names.scala
  test/tasty/run/src-2/tastytest/TestEntityDb.scala
  test/tasty/run/src-2/tastytest/TestLogarithms.scala
  test/tasty/run/src-2/tastytest/TestNames.scala
  test/tasty/run/src-2/tastytest/TestVecs.scala
  test/tasty/run/src-3/tastytest/EntityDb.scala
  test/tasty/run/src-3/tastytest/Logarithms.scala
  test/tasty/run/src-3/tastytest/Names.scala
  test/tasty/run/src-3/tastytest/Vecs.scala
Labels: tastyreader

#9339 Add note to Unicode unaware methods
  src/library/scala/collection/StringOps.scala
Labels: documentation

#9373 Travis-CI: only compile benchmarks during PR validation
  .travis.yml
Labels: internal

#9374 make TASTy tests less noisy
  src/tastytest/scala/tools/tastytest/TastyTest.scala
Labels: internal

#9309 Tab-complete relative partest paths (eg pos/t<TAB>)
  project/ParserUtil.scala
  project/PartestUtil.scala
  project/src/test/scala/PartestUtilTest.scala
Labels: internal

#7432 Generate Specification PDF
  .travis.yml
  scripts/generate-spec-pdf.bat
  scripts/generate-spec-pdf.sh
  spec/01-lexical-syntax.md
  spec/02-identifiers-names-and-scopes.md
  spec/03-types.md
  spec/04-basic-declarations-and-definitions.md
  spec/05-classes-and-objects.md
  spec/06-expressions.md
  spec/07-implicits.md
  spec/08-pattern-matching.md
  spec/09-top-level-definitions.md
  spec/10-xml-expressions-and-patterns.md
  spec/11-annotations.md
  spec/12-the-scala-standard-library.md
  spec/13-syntax-summary.md
  spec/15-changelog.md
  spec/_includes/table-of-contents.yml
  spec/_layouts/default.yml
  spec/_layouts/toc.yml
  spec/index.md
  spec/public/scripts/main.js
  spec/public/stylesheets/print.css
  spec/public/stylesheets/screen.css
  spec/spec-toc.xslt
Labels: documentation, release-notes, welcome

#9377 sbt build: standardize on camel (not kebab) case project names
  build.sbt
Labels: internal

#9383 give sbt more heap (2G instead of 1.5)
  .jvmopts
Labels: internal

#9378 Avoid printing a large stacktrace for a tastytest failure
  test/tasty/test/scala/tools/tastytest/TastyTestJUnit.scala
Labels: internal

#9382 [backport] backport .jvmopts from 2.13.x, sbt needs heap
  .jvmopts
Labels: internal

#9384 Set `-md md5` when decrypting credentials with openssl
  admin/init.sh
Labels: internal

#9386 fix regression in spec publishing
  scripts/travis-publish-spec.sh
Labels: internal

#9385 restore correct scala-dist artifact name
  build.sbt
Labels: internal

#9387 lots of small README edits
  README.md
Labels: documentation, internal

#9390 sbt 1.4.5 (was 1.4.4)
  project/build.properties
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
  test/jcstress/project/build.properties
Labels: internal

#9395 Upgrade Dotty to 3.0.0-M3
  project/DottySupport.scala
  project/plugins.sbt
Labels: internal

#9337 Add doc for Array.equals and sameElements
  src/library/scala/Array.scala
  src/library/scala/collection/Iterator.scala
  test/junit/scala/ArrayTest.scala
Labels: documentation

#9407 Restore two blank lines bailing the REPL
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
Labels: tool:REPL

#9402 Fix scala/bug#10272: Add regression test
  test/files/pos/t10272.scala
Labels: internal

#9411 move from travis-ci.org to travis-ci.com
  README.md
  scripts/common
Labels: internal

#9412 REPL debug/trace is jline fine/finest
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
Labels: internal, tool:REPL

#9410 Update Lightbend team in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, internal

#9397 Tasty Reader: fix bug in reading parents of cats.Show [ci: last-only]
  src/compiler/scala/tools/nsc/tasty/bridge/SymbolOps.scala
  test/tasty/pos/src-2/tastytest/TestShow.scala
  test/tasty/pos/src-3/fplib/Show.scala
Labels: tastyreader

#9394 Tasty reader: support Scala 3.0.0-M3
  project/DottySupport.scala
  src/compiler/scala/tools/nsc/tasty/TreeUnpickler.scala
  src/compiler/scala/tools/nsc/tasty/bridge/NameOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/TypeOps.scala
  src/compiler/scala/tools/tasty/TastyFormat.scala
  test/tasty/run/src-2/tastytest/TestIOApp.scala
  test/tasty/run/src-2/tastytest/TestMatchables.scala
  test/tasty/run/src-2/tastytest/TestTraitInitsBase.scala
  test/tasty/run/src-2/tastytest/TestValueOfErasure.scala
  test/tasty/run/src-3/tastytest/IOApp.scala
  test/tasty/run/src-3/tastytest/Matchables.scala
  test/tasty/run/src-3/tastytest/TraitInitsBase.scala
  test/tasty/run/src-3/tastytest/ValueOfErasure.scala
Labels: tastyreader
