Repository scala/scala, pull requests merged in 2020-01, with the labels that each got.

#8615 Optimize SeqView.Drop
  src/library/scala/collection/SeqView.scala
Labels: library:collections

#8587 Spec grammar touchups pointed out by Ducanhta
  spec/05-classes-and-objects.md
Labels: documentation

#8628 Merge pull request #8628 from ashawley/fix-pickler-doc-xref
  src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala
Labels: documentation

#8632 Augment doc for breakable
  src/library/scala/util/control/Breaks.scala
Labels: build, documentation

#8636 bump copyright year to 2020
  NOTICE
  doc/LICENSE.md
  doc/License.rtf
  project/VersionUtil.scala
  src/library/scala/util/Properties.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  src/scalap/decoder.properties
Labels: documentation

#8133 Extend varargs empty sequence optimisation.
  src/compiler/scala/tools/nsc/transform/CleanUp.scala
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  test/junit/scala/tools/nsc/transform/UncurryTest.scala
Labels: performance

#7725 Small optimisations to lubList
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
  src/reflect/scala/reflect/internal/util/Collections.scala
  test/benchmarks/src/main/scala/reflect/internal/LubBenchmark.scala
Labels: performance

#8635 Fail early if self-referential LazyList runs out of elements
  src/library/scala/collection/immutable/LazyList.scala
  test/junit/scala/collection/immutable/LazyListTest.scala
Labels: library:collections

#8642 Make :: type alias covariant
  src/library/scala/package.scala
Labels: library:collections

#8525 move to sbt 1.3, fix build on JDK 13+
  build.sbt
  project/DottySupport.scala
  project/SavedLogs.scala
  project/build.properties
  project/plugins.sbt
  scripts/common
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
  test/jcstress/project/build.properties
  test/junit/scala/tools/nsc/backend/jvm/NestedClassesCollectorTest.scala
Labels: build

#8556 Add a mode to write separate .sig files without really private members
  src/compiler/scala/tools/nsc/GenericRunnerSettings.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/Settings.scala
  src/compiler/scala/tools/nsc/classpath/ClassPathFactory.scala
  src/compiler/scala/tools/nsc/io/SourceReader.scala
  src/compiler/scala/tools/nsc/settings/FscSettings.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  src/compiler/scala/tools/nsc/settings/PathFactory.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala
  src/compiler/scala/tools/nsc/typechecker/Macros.scala
  src/reflect/mima-filters/2.12.0.forwards.excludes
  src/reflect/scala/reflect/io/AbstractFile.scala
  src/reflect/scala/reflect/io/VirtualFile.scala
  src/reflect/scala/reflect/io/ZipArchive.scala
  src/scaladoc/scala/tools/nsc/doc/Settings.scala
  test/junit/scala/tools/nsc/Build.scala
  test/junit/scala/tools/nsc/FileUtils.scala
  test/junit/scala/tools/nsc/PickleWriteTest.scala
  test/junit/scala/tools/nsc/PipelineMainTest.scala
Labels: release-notes

#8640 Optimize Random.nextString
  src/library/scala/util/Random.scala
Labels: library:base, performance

#8661 remove unnecessary "TraversableOnce.alternateImplicit" reference
  src/scaladoc/scala/tools/nsc/doc/Settings.scala
Labels: documentation

#8471 Revert invert type signature change
  src/library/scala/Predef.scala
  src/library/scala/runtime/Tuple2Zipped.scala
  src/library/scala/runtime/Tuple3Zipped.scala
  test/junit/scala/runtime/ZippedTest.scala
Labels: library:base

#8645 Fix and simplify LazyList tests
  test/junit/scala/collection/immutable/LazyListLazinessTest.scala
  test/junit/scala/collection/immutable/LazyListTest.scala
Labels: build, library:collections

#8677 [2.12] Fix some tests on JDK 11
  test/files/run/repl-paste-parse.scala
  test/files/run/t6502.scala
  test/files/run/t8549.scala
Labels: build

#8676 Update ASM to 7.3.1
  versions.properties
Labels: release-notes

#8400 REPL javap under JDK9+
  src/compiler/scala/tools/nsc/util/package.scala
  src/repl/scala/tools/nsc/interpreter/ILoop.scala
  src/repl/scala/tools/nsc/interpreter/JavapClass.scala
  test/files/run/t8608-no-format.scala
Labels: release-notes

#8674 Export underlying on non-copying conversion
  src/library/scala/collection/mutable/ListBuffer.scala
  test/junit/scala/collection/IndexedSeqTest.scala
  test/junit/scala/collection/mutable/ListBufferTest.scala
Labels: library:collections, release-notes

#8658 Update ScalaCheck to 1.14.3
  build.sbt
  src/intellij/scala.ipr.SAMPLE
  src/intellij/scalacheck-src.iml.SAMPLE
  src/intellij/scalacheck-test.iml.SAMPLE
  src/scalacheck/org/scalacheck/Arbitrary.scala
  src/scalacheck/org/scalacheck/ArbitraryArities.scala
  src/scalacheck/org/scalacheck/Cogen.scala
  src/scalacheck/org/scalacheck/CogenArities.scala
  src/scalacheck/org/scalacheck/Gen.scala
  src/scalacheck/org/scalacheck/GenArities.scala
  src/scalacheck/org/scalacheck/Platform.scala
  src/scalacheck/org/scalacheck/Prop.scala
  src/scalacheck/org/scalacheck/Properties.scala
  src/scalacheck/org/scalacheck/ScalaCheckFramework.scala
  src/scalacheck/org/scalacheck/ScalaVersionSpecific.scala
  src/scalacheck/org/scalacheck/Shrink.scala
  src/scalacheck/org/scalacheck/Test.scala
  src/scalacheck/org/scalacheck/commands/Commands.scala
  src/scalacheck/org/scalacheck/rng/Seed.scala
  src/scalacheck/org/scalacheck/util/Buildable.scala
  src/scalacheck/org/scalacheck/util/BuildableVersionSpecific.scala
  src/scalacheck/org/scalacheck/util/CmdLineParser.scala
  src/scalacheck/org/scalacheck/util/ConsoleReporter.scala
  src/scalacheck/org/scalacheck/util/FreqMap.scala
  src/scalacheck/org/scalacheck/util/Pretty.scala
  test/scalacheck/org/scalacheck/CustomScalaCheckRunner.scala
  test/scalacheck/org/scalacheck/LazyFramework.java
  test/scalacheck/scala/collection/convert/WrapperProperties.scala
  test/scalacheck/scala/collection/immutable/BitSetProperties.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashMapProperties.scala
  test/scalacheck/scala/collection/immutable/ImmutableChampHashSetProperties.scala
  test/scalacheck/scala/collection/mutable/BitSetProperties.scala
  test/scalacheck/scala/collection/mutable/HashMapProperties.scala
Labels: build

#8672 remove tupling for foreach in keySet/values of immutable HashMap and TreeMap
  src/library/mima-filters/2.12.0.forwards.excludes
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/TreeMap.scala
Labels: performance
