Repository scala/scala, pull requests merged in 2020-06, with the labels that each got.

#9020 use sbt 1.3.12 (was 1.3.10)
  project/build.properties
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
  test/jcstress/project/build.properties
Labels: build

#9017 Finer grained word boundaries for the REPL's line editor
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
Labels: tool:REPL

#9010 HashMap / HashSet: Add a little explanation of the structure.
  src/library/scala/collection/mutable/HashMap.scala
  src/library/scala/collection/mutable/HashSet.scala
Labels: documentation, library:collections

#9024 upgrade JLine 3 to 3.15.0 (was 3.14.1)
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: tool:REPL

#9003 Deprecate multiarg `+=` on `AnyRefMap` and `LongMap`
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/library/scala/collection/mutable/LongMap.scala
Labels: library:collections

#9015 Tweak getParts and getClassParts
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Labels: performance

#9009 Avoid rare StackOverflow in diverging implicits check
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  test/files/neg/t12005.check
  test/files/neg/t12005.scala
Labels: release-notes

#9029 Remove extraneous check file
  test/files/neg/java-annotation-match-error.check
Labels: build

#9028 Clarify contribution workflow for new members
  README.md
Labels: documentation

#8908 Improve VectorMap.last complexity.
  src/library/scala/collection/immutable/VectorMap.scala
  test/junit/scala/collection/immutable/VectorMapTest.scala
  test/scalacheck/scala/collection/immutable/VectorMapProperties.scala
Labels: library:collections, performance

#9032 All filters must match for nowarn
  src/compiler/scala/tools/nsc/Reporting.scala
  test/files/neg/t12026.check
  test/files/neg/t12026.scala
Labels: release-notes

#9033 Cleanup some ScriptRunner & Settings code
  src/compiler/scala/tools/nsc/ScriptRunner.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  test/junit/scala/tools/nsc/ScriptRunnerTest.scala
Labels: build

#9019 Promote implicit recursion to lint
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  test/files/neg/implicitly-self.check
  test/files/neg/implicitly-self.scala
  test/files/pos/t11813.scala
Labels: release-notes

#9005 Retain var class param if used
  src/compiler/scala/tools/nsc/transform/Constructors.scala
  test/files/run/t12002.check
  test/files/run/t12002.scala
Labels: prio:blocker

#9040 -Xshow-phases/-Ydebug -> -Vphases/-Vdebug renames
  src/compiler/scala/reflect/reify/codegen/GenTypes.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/plugins/PluginComponent.scala
  src/compiler/scala/tools/reflect/ToolBox.scala
  src/reflect/scala/reflect/internal/Flags.scala
  test/files/neg/t6446-show-phases.scala
  test/files/run/programmatic-main.scala
Labels: build

#9041 Cleanup some compiler Scaladoc
  src/compiler/scala/tools/nsc/PhaseAssembly.scala
  src/compiler/scala/tools/nsc/SubComponent.scala
  src/compiler/scala/tools/nsc/ast/parser/SyntaxAnalyzer.scala
  src/compiler/scala/tools/nsc/transform/SampleTransform.scala
  src/compiler/scala/tools/nsc/transform/Transform.scala
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  src/compiler/scala/tools/nsc/typechecker/Adaptations.scala
  src/compiler/scala/tools/nsc/typechecker/Analyzer.scala
  src/compiler/scala/tools/nsc/typechecker/PatternTypers.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/SuperAccessors.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: documentation

#8983 allocation hotspot in small Map iterators
  build.sbt
  src/library/scala/collection/immutable/Map.scala
  test/junit/scala/collection/immutable/SmallMapTest.scala
Labels: library:collections, performance

#9045 Scaladoc on AnyRef#wait
  src/library-aux/scala/AnyRef.scala
  src/scaladoc/scala/tools/nsc/doc/Uncompilable.scala
  test/scaladoc/run/anyref-doc.check
  test/scaladoc/run/anyref-doc.scala
Labels: documentation

#9048 Preferred parens in junit tests
  test/junit/scala/collection/ReusableBuildersTest.scala
  test/junit/scala/collection/SortedSetMapEqualsTest.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
  test/junit/scala/collection/immutable/TreeSetTest.scala
  test/junit/scala/tools/nsc/reporters/ConsoleReporterTest.scala
Labels: build

#9049 Remove eta-expansion of SAM under -Xsource:3
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/neg/t7187-3.check
  test/files/neg/t7187-3.scala
  test/files/neg/t7187-deprecation.check
  test/files/neg/t7187-deprecation.scala
  test/files/pos/t12006.scala
Labels: release-notes

#9036 Restore special cases for small operands in {append,prepend}edAll
  build.sbt
  src/library/scala/collection/immutable/Vector.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: library:collections, prio:blocker, release-notes

#9050 Scaladoc on AnyRef#synchronized
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
  test/scaladoc/run/anyref-doc.check
  test/scaladoc/run/anyref-doc.scala
Labels: documentation

#9052 [backport] decode html escapes in intellij dependency paths
  build.sbt
Labels: build

#8989 Add ILoop.internalReplAutorunCode in REPL
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
Labels: tool:REPL

#9000 document laziness of LazyList vs Stream
  src/library/scala/collection/immutable/LazyList.scala
Labels: documentation

#9065 Run DCE also on large methods
  src/compiler/scala/tools/nsc/backend/jvm/opt/LocalOpt.scala
Labels: prio:blocker

#9061 Bulk ops on TreeSet/TreeSet or TreeMap/TreeMap prefer keys from the left
  src/library/scala/collection/immutable/RedBlackTree.scala
  test/junit/scala/collection/SetMapRulesTest.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
  test/junit/scala/collection/immutable/TreeSetTest.scala
Labels: backport candidate

#9067 docs: corrected grammatical errors in the docs
  spec/01-lexical-syntax.md
  spec/02-identifiers-names-and-scopes.md
  src/compiler/scala/reflect/macros/contexts/Names.scala
Labels: documentation

#9062 [backport] Bulk ops on TreeSet, TreeMap prefer keys from the left
  src/library/scala/collection/immutable/RedBlackTree.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
  test/junit/scala/collection/immutable/TreeSetTest.scala
Labels: library:collections

#9076 Make isEmpty for IntMap / LongMap O(1)
  src/library/scala/collection/immutable/IntMap.scala
  src/library/scala/collection/immutable/LongMap.scala
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/junit/scala/collection/immutable/IntMapTest.scala
  test/junit/scala/collection/immutable/LongMapTest.scala
Labels: library:collections, performance

#9077 tab completion: fix some isDeprecated false-positives
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
  test/junit/scala/collection/immutable/LongMapTest.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
Labels: tool:REPL

#9078 Rework recent, buggy change to immutable.TreeMap
  src/library/scala/collection/immutable/RedBlackTree.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
Labels: backport candidate, library:collections, prio:blocker

#9081 [backport] Rework recent, buggy change to immutable.TreeMap
  src/library/scala/collection/immutable/RedBlackTree.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
Labels: library:collections

#9074 HashMap bulk operations should retain existing keys
  src/library/scala/collection/immutable/HashMap.scala
  test/junit/scala/collection/immutable/HashMapTest.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
  test/junit/scala/collection/immutable/TreeSetTest.scala
Labels: prio:blocker

#9088 re-STARR onto 2.13.3
  build.sbt
  versions.properties
Labels: internal

#9086 fix typos
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
  test/files/run/t10450/A.java
  test/junit/scala/tools/nsc/classpath/MultiReleaseJarTest.scala
Labels: internal

#9089 Multiarg infix application is behind lint flag
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/run/infix.check
  test/files/run/t5565.check
Labels: release-notes

#8864 Compiler determinism for synthetic companions
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/reflect/scala/reflect/internal/Scopes.scala
  test/junit/scala/tools/nsc/DeterminismTest.scala
Labels: backport candidate
