Repository scala/scala, pull requests merged in 2020-04, with the labels that each got.

#8847 Revert "Fixes Iterable#toString forcing elements"
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/concurrent/TrieMap.scala
  src/partest/scala/tools/partest/Util.scala
  test/junit/scala/collection/IterableTest.scala
  test/scalacheck/SeqMap.scala
Labels: prio:blocker

#8601 List optimizations for List.from, ::: and prependedAll
  src/library/scala/collection/immutable/List.scala
  test/junit/scala/collection/immutable/ListTest.scala
  test/scalacheck/scala/collection/immutable/ListProperties.scala
Labels: library:collections, performance

#8850 Add name to README
  README.md
Labels: build

#8783 Don't check key equality in RedBlackTree
  src/library/scala/collection/immutable/RedBlackTree.scala
Labels: library:collections

#8814 Make {Any,Object}.## have no argument list (instead of a single empty one)
  src/library-aux/scala/Any.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  test/files/neg/auto-application.check
  test/files/neg/auto-application.scala
  test/files/pos/auto-application.scala
  test/files/presentation/callcc-interpreter.check
  test/files/presentation/completion-implicit-chained.check
  test/files/presentation/ide-bug-1000349.check
  test/files/presentation/ide-bug-1000475.check
  test/files/presentation/ide-bug-1000531.check
  test/files/presentation/implicit-member.check
  test/files/presentation/infix-completion.check
  test/files/presentation/infix-completion2.check
  test/files/presentation/ping-pong.check
  test/files/presentation/t5708.check
  test/files/presentation/visibility.check
  test/files/run/compiler-asSeenFrom.scala
  test/files/run/reflection-magicsymbols-invoke.check
  test/files/run/reflection-valueclasses-magic.check
Labels: release-notes

#8825 better diagnostics from AllocationTest
  test/junit/scala/tools/testing/AllocationTest.scala
Labels: build

#8855 Fixes Repl not cleaning after itself
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/InteractiveReader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/SimpleReader.scala
Labels: tool:REPL

#8859 Avoid allocation of TreeInfo.Applied
  src/compiler/scala/tools/nsc/typechecker/Macros.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/TreeInfo.scala
Labels: performance

#8860 Microopts in FindMember
  src/reflect/scala/reflect/internal/tpe/FindMembers.scala
Labels: performance

#8848 REPL: JLine 3: fix various issues
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/InteractiveReader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ReplCompletion.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/SimpleReader.scala
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
  test/files/run/repl-previous-result.check
  test/files/run/repl-previous-result.scala
Labels: tool:REPL

#8861 No Unit.depends bookkeeping if -Ytrack-dependencies:false
  src/compiler/scala/tools/nsc/CompilationUnits.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
Labels: performance

#8858 Improve performance of atPos under -Yrangepos
  src/reflect/scala/reflect/internal/Positions.scala
  src/reflect/scala/reflect/internal/Trees.scala
Labels: performance

#8842 Reduce the size of WrappedArray
  src/library/scala/collection/mutable/WrappedArray.scala
  test/junit/scala/collection/Sizes.scala
  test/junit/scala/tools/testing/JOL.scala
Labels: library:collections, performance, performance:do_not_allocate

#8856 Add CODEOWNERS file
  .github/CODEOWNERS
Labels: build

#8873 don't run a flaky sys.process test (t10823) on Windows
  test/junit/scala/sys/process/ProcessTest.scala
Labels: build

#8880 REPL: JLine 3: fix handling of errors during tokenization
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
Labels: tool:REPL

#8831 improve TraversableOnce.toMap
  src/library/scala/collection/TraversableOnce.scala
Labels: library:collections

#8823 remove unused `overwrite` parameter in updateNth
  src/library/scala/collection/immutable/RedBlackTree.scala
Labels: library:collections

#8876 reduce CPU in SortedMap and SortedSet #equals()
  build.sbt
  src/library/scala/collection/immutable/SortedMap.scala
  src/library/scala/collection/immutable/SortedSet.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/RedBlackTreeEqualsBenchmark.scala
Labels: performance, performance:do_not_allocate

#8872 Benchmark for equals checking of RedBlackTree
  test/benchmarks/src/main/scala/scala/collection/immutable/RedBlackTreeEqualsBenchmark.scala
Labels: build, library:collections

#8726 create a HashMap builder inspired by the 2.13 builder
  build.sbt
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/Map.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/HashMapBenchmarkData.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/HashMapBuilderBenchmark.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/HashMapBulkBenchmark.scala
Labels: library:collections, performance

#8722 HashSet builder
  build.sbt
  src/library/scala/collection/immutable/HashSet.scala
  src/library/scala/collection/immutable/Set.scala
  src/library/scala/collection/parallel/immutable/ParHashSet.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/HashSetBenchmarkData.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/HashSetBuilderBenchmark.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/HashSetBulkBenchmark.scala
  test/junit/scala/collection/immutable/HashSetTest.scala
Labels: library:collections

#8663 Fix broken Scaladoc external references with JDK11
  project/ScalaOptionParser.scala
  src/manual/scala/man1/scaladoc.scala
  src/scaladoc/scala/tools/nsc/doc/Settings.scala
  src/scaladoc/scala/tools/nsc/doc/model/MemberLookup.scala
  test/scaladoc/run/t191.scala
Labels: release-notes

#8854 Fix VectorMap Bug [scala/bug#11933]
  build.sbt
  src/library/scala/collection/immutable/VectorMap.scala
  test/junit/scala/collection/immutable/VectorMapTest.scala
Labels: library:collections

#8884 Suppress Javac 8 output in test
  test/files/run/t10641.check
  test/files/run/t10641.scala
Labels: build

#8795 [backport] 7768 completed future is not blocking
  src/library/scala/concurrent/package.scala
Labels: library:concurrent

#8887 Use Using in ProcessTest
  src/testkit/scala/tools/testkit/TempDir.scala
  test/junit/scala/sys/process/ProcessTest.scala
Labels: build

#8862 [backport] SetN / MapN optimizations
  build.sbt
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/Set.scala
Labels: library:collections

#8891 Reduce string allocations in JAR classpath elements
  src/reflect/scala/reflect/io/ZipArchive.scala
Labels: performance

#8892 Optimize adaptInfos by devirtualizing Symbol.phaseWithId
  build.sbt
  src/compiler/scala/tools/nsc/Global.scala
  src/reflect/scala/reflect/internal/SymbolTable.scala
  src/reflect/scala/reflect/runtime/ReflectSetup.scala
  test/junit/scala/tools/nsc/symtab/SymbolTableForUnitTesting.scala
Labels: performance

#8775 RedBlackTree should not allocate a new tree if the Key and Value is eq the existing one
  src/library/scala/collection/immutable/RedBlackTree.scala
  test/junit/scala/collection/immutable/TreeMapTest.scala
  test/junit/scala/collection/immutable/TreeSetTest.scala
Labels: library:collections, performance:do_not_allocate

#8888 Fix suppressed stack trace frame count in REPL
  src/compiler/scala/tools/nsc/util/StackTracing.scala
  src/partest/scala/tools/partest/ReplTest.scala
  test/files/run/repl-trace-elided-more.check
  test/files/run/repl-trace-elided-more.scala
Labels: bug fix, tool:REPL

#8790 avoid creation of ListBuffers for small Seq.apply,
  src/compiler/scala/tools/nsc/transform/CleanUp.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/junit/scala/collection/SeqTest.scala
  test/junit/scala/collection/Sizes.scala
  test/junit/scala/collection/immutable/ListTest.scala
  test/junit/scala/collection/immutable/SeqTest.scala
Labels: library:collections, performance, performance:do_not_allocate

#8904 fix buggy Java version check in Scaladoc tool
  src/scaladoc/scala/tools/nsc/doc/model/MemberLookup.scala
Labels: prio:blocker

#8906 REPL: JLine 3: bring back `-Xnojline`, but deprecate it
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
Labels: tool:REPL

#8893 microopt subtyping avoiding Symbol.{owner,needFlatClasses}
  src/reflect/scala/reflect/internal/tpe/TypeComparers.scala
Labels: performance

#8905 REPL: JLine 3: improve tab completion behavior
  build.sbt
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/Completion.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/LoopCommands.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ReplCompletion.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
  test/files/run/repl-completions.check
  test/files/run/repl-completions.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
  versions.properties
Labels: tool:REPL

#8910 re-STARR onto 2.13.2
  build.sbt
  versions.properties
Labels: build

#8916 [backport] Break up Symbol.info for JIT friendliness
  src/reflect/scala/reflect/internal/Symbols.scala
Labels: performance

#8911 Use cache of implicit pt function arity more often
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Labels: performance

#8918 build with sbt 1.3.10 (was 1.3.8)
  project/build.properties
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
  test/jcstress/project/build.properties
Labels: build

#8917 Remove some statistics
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/Scopes.scala
  src/reflect/scala/reflect/internal/Trees.scala
  src/reflect/scala/reflect/internal/Types.scala
Labels: performance

#8914 Optimize flag lookup in findMember
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/tpe/FindMembers.scala
Labels: performance

#8915 Actually use ReusableDataReader in classfile parsing
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/symtab/classfile/DataReader.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ReusableDataReader.scala
Labels: performance

#8909 separate CanBuildFrom for each SeqFactory
  src/library/scala/collection/IndexedSeq.scala
  src/library/scala/collection/generic/IndexedSeqFactory.scala
  src/library/scala/collection/immutable/List.scala
  src/library/scala/collection/immutable/Vector.scala
  test/files/run/t6150.scala
  test/junit/scala/collection/immutable/ListTest.scala
Labels: library:collections

#8924 Workaround performance bug in Zinc
  src/compiler/scala/tools/nsc/classpath/AggregateClassPath.scala
Labels: performance

#8926 [nomerge] Avoid some Some allocations in HashMaps
  build.sbt
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/mutable/LinkedHashMap.scala
Labels: library:collections, performance:do_not_allocate

#8927 Reduce allocations when loading packages from classpath
  src/compiler/scala/tools/nsc/classpath/ClassPath.scala
  src/compiler/scala/tools/nsc/symtab/BrowsingLoaders.scala
  src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
  src/compiler/scala/tools/nsc/util/ClassPath.scala
Labels: performance

#8928 Reduce allocation in unexpandedName
  src/reflect/scala/reflect/internal/StdNames.scala
Labels: performance

#8739 A simple TreeMapBuilder
  build.sbt
  src/library/scala/collection/immutable/TreeMap.scala
Labels: library:collections, performance:do_not_allocate

#8936 Reduce allocation cost of dead code elimination
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/ClosureOptimizer.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/Inliner.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/LocalOpt.scala
  test/junit/scala/tools/nsc/backend/jvm/opt/UnreachableCodeTest.scala
Labels: performance

#8939 Restore isWin exclusion to t10823 tests
  test/junit/scala/sys/process/ProcessTest.scala
Labels: build
