Repository scala/scala, pull requests merged in 2020-03, with the labels that each got.

#8772 [backport] Build intellij task: don't prompt for confirmation
  build.sbt
Labels: build

#8778 TreeMap is serialization compat with 2.12.10 again
  build.sbt
  src/library/scala/collection/immutable/TreeMap.scala
  test/files/run/t8549.scala
Labels: prio:blocker

#8282 Un-special-case unicode escapes
  build.sbt
  project/ScalaOptionParser.scala
  spec/01-lexical-syntax.md
  spec/13-syntax-summary.md
  spec/15-changelog.md
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/compiler/scala/tools/nsc/javac/JavaScanners.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/util/CharArrayReader.scala
  src/compiler/scala/tools/reflect/FastStringInterpolator.scala
  src/library/scala/StringContext.scala
  src/manual/scala/man1/scalac.scala
  test/files/neg/t3220-1.check
  test/files/neg/t3220-1.scala
  test/files/neg/t3220-2.check
  test/files/neg/t3220-2.scala
  test/files/neg/t4584.check
  test/files/neg/t4584.scala
  test/files/neg/t6631.check
  test/files/neg/t8015-ffb.scala
  test/files/neg/t8266-invalid-interp.check
  test/files/neg/u000a.check
  test/files/neg/u000a.scala
  test/files/neg/unicode-unterminated-quote.check
  test/files/neg/unicode-unterminated-quote.scala
  test/files/pos/t389.scala
  test/files/pos/u000a.scala
  test/files/run/literals.check
  test/files/run/literals.scala
  test/files/run/repl-no-uescape.scala
  test/files/run/t3220-213.check
  test/files/run/t3220-213.scala
  test/files/run/t3220-214.scala
  test/files/run/t3835.scala
  test/files/run/t8015-ffc.scala
  test/files/run/xMigration.scala
Labels: release-notes

#8757 Deprecate numeric widening of numeric literals which are not representable with Float/Double
  spec/06-expressions.md
  src/compiler/scala/tools/nsc/typechecker/ConstantFolder.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/Constants.scala
  test/files/jvm/duration-tck.scala
  test/files/neg/deprecated_widening.check
  test/files/neg/deprecated_widening.scala
Labels: release-notes

#8763 Merge 2.12.x to 2.13.x [ci: last-only]
  src/library/scala/runtime/ScalaRunTime.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/HashMapBulkBenchmark.scala
Labels: prio:blocker

#8761 Take advantage of Map.foreachentry in some Map operations
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/mutable/HashMap.scala
  test/junit/scala/collection/SetMapConsistencyTest.scala
Labels: library:collections, performance

#8785 Trivial tweaks
  src/compiler/scala/tools/nsc/transform/patmat/Logic.scala
  src/compiler/scala/tools/nsc/transform/patmat/Solving.scala
  src/repl/scala/tools/nsc/interpreter/Power.scala
  test/files/jvm/annotations/Test_2.scala
  test/files/jvm/t2163/t2163.scala
  test/files/pos/t11303.scala
  test/files/pos/t1439.scala
  test/files/run/abstype_implicits.scala
  test/files/run/abstypetags_serialize.scala
  test/files/run/byname-implicits-5.scala
  test/files/run/classmanifests_new_alias.scala
  test/files/run/classmanifests_new_core.scala
  test/files/run/hk-typevar-unification.scala
  test/files/run/interop_classtags_are_classmanifests.scala
  test/files/run/interop_manifests_are_classtags.scala
  test/files/run/kmpSliceSearch.scala
  test/files/run/manifests-new.scala
  test/files/run/manifests-old.scala
  test/files/run/names-defaults.scala
  test/files/run/partialfun.scala
  test/files/run/reflection-allmirrors-tostring.scala
  test/files/run/reify_implicits-old.scala
  test/files/run/search.check
  test/files/run/search.scala
  test/files/run/sequenceComparisons.scala
  test/files/run/t0421-old.scala
  test/files/run/t0677-old.scala
  test/files/run/t10344.scala
  test/files/run/t10545.scala
  test/files/run/t1427.scala
  test/files/run/t2308a.scala
  test/files/run/t2594_tcpoly.scala
  test/files/run/t3242.scala
  test/files/run/t3452f.scala
  test/files/run/t3758-old.scala
  test/files/run/t5294.scala
  test/files/run/t6113.scala
  test/files/run/t6329_vanilla.scala
  test/files/run/t6329_vanilla_bug.check
  test/files/run/t6329_vanilla_bug.scala
  test/files/run/t7120b.scala
  test/files/run/t7200.scala
  test/files/run/t7291.scala
  test/files/run/t7932.scala
  test/files/run/tcpoly_monads.scala
  test/files/run/tcpoly_overriding.scala
  test/files/run/tcpoly_parseridioms.scala
  test/files/run/type-currying.scala
  test/files/run/valueclasses-classmanifest-basic.scala
  test/files/run/valueclasses-classmanifest-existential.scala
  test/files/run/valueclasses-classmanifest-generic.scala
  test/files/specialized/spec-matrix-old.scala
  test/junit/scala/collection/SearchingTest.scala
Labels: build

#8802 More accurate description of BitSet memory footprint in scaladoc
  src/library/scala/collection/BitSet.scala
Labels: documentation, library:collections

#8801 Avoid duplicate imports
  src/compiler/scala/tools/nsc/typechecker/Analyzer.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
Labels: performance

#8534 Rewrite Vector (now "radix-balanced finger tree vectors"), for performance
  build.sbt
  src/library/scala/collection/immutable/ArraySeq.scala
  src/library/scala/collection/immutable/Vector.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/GenerateVectorBenchmark2Charts.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/OldVector.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/VectorBenchmark2.scala
  test/benchmarks/vector-results.html
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: library:collections, release-notes

#8811 Fix fallback of scalacOpts in partest's SBTRunner
  src/partest/scala/tools/partest/sbt/SBTRunner.scala
Labels: build

#8810 Upgrade Dotty to 0.23.0-RC1
  project/DottySupport.scala
  src/library/scala/collection/immutable/List.scala
Labels: build

#8545 Plug many variance holes (pos and neg)
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/reflect/scala/reflect/internal/Variances.scala
  test/files/neg/t7872.check
  test/files/neg/t7872b.check
  test/files/neg/t9911.check
  test/files/neg/t9911.scala
  test/files/neg/variance-holes.check
  test/files/neg/variance-holes.scala
  test/files/neg/variances.check
  test/files/pos/t9725.scala
  test/files/pos/variance-holes.scala
Labels: release-notes

#8749 backport 2.13 immutable RedBlackTree to 2.12
  build.sbt
  src/library/scala/collection/SetLike.scala
  src/library/scala/collection/TraversableLike.scala
  src/library/scala/collection/generic/SortedMapFactory.scala
  src/library/scala/collection/generic/Subtractable.scala
  src/library/scala/collection/immutable/RedBlackTree.scala
  src/library/scala/collection/immutable/TreeMap.scala
  src/library/scala/collection/immutable/TreeSet.scala
Labels: library:collections, performance, release-notes

#8793 backport a benchmark. Adjust API for 2.12
  test/benchmarks/src/main/scala/scala/collection/immutable/RedBlackTreeBenchmark.scala
Labels: build, library:collections

#8791 Avoid creation of Option for TreeMap.getOrElse
  src/library/scala/collection/immutable/TreeMap.scala
Labels: library:collections, performance:do_not_allocate

#8036 REPL: upgrade to JLine 3 (benefits include multi-line editing)
  build.sbt
  doc/LICENSE.md
  doc/License.rtf
  doc/licenses/apache_jna.txt
  doc/licenses/bsd_jline.txt
  doc/licenses/bsd_scalacheck.txt
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/fsc/ResidentScriptRunner.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  src/manual/scala/man1/scalac.scala
  src/partest/scala/tools/partest/ReplTest.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/FileBackedHistory.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/JLineDelimiter.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/JLineHistory.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/JLineReader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/Completion.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/History.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/InteractiveReader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/LoopCommands.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ReplCompletion.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ShellConfig.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/SimpleReader.scala
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
  test/benchmarks/README.md
  test/files/run/repl-paste-parse.check
  test/files/run/type-tag-leak.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
  test/macro-annot/run/repl/repl_2.scala
  versions.properties
Labels: release-notes, tool:REPL

#8832 Disable event expansion in REPL JLine reader
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
Labels: tool:REPL

#8837 Drop duplicate CompilerTest
  test/files/run/compiler-asSeenFrom.scala
  test/files/run/t7096.scala
Labels: build

#8838 Update neg/t7187-deprecation
  test/files/neg/t7187-deprecation.check
  test/files/neg/t7187-deprecation.scala
Labels: build

#8829 More Scala.js-friendly Vector.apply and .updated
  src/library/scala/collection/immutable/Vector.scala
Labels: library:collections

#8827 Do not rely on `ArrayIndexOOBE` in `Vector.{head,last}`.
  src/library/scala/collection/immutable/Vector.scala
Labels: library:collections

#8836 Fast-track deprecating nullary method eta-expansion
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/neg/t7187-3.check
  test/files/neg/t7187-3.scala
  test/files/neg/t7187-deprecation.check
  test/files/neg/t7187-deprecation.scala
  test/files/neg/t7187.check
  test/files/neg/t7187.scala
  test/files/run/amp.scala
  test/files/run/byname.scala
  test/files/run/existentials3-new.scala
  test/files/run/existentials3-old.scala
  test/files/run/pr7593.scala
  test/files/run/sammy_cbn.scala
  test/files/run/t1247.scala
Labels: release-notes
