Repository scala/scala, pull requests merged in 2021-11, with the labels that each got.

#9798 re-STARR onto 2.13.7
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#9807 JLine 3.21.0 / JNA 5.9.0 (was 3.20.0 / 5.8.0)
  versions.properties
Labels: release-notes

#9796 Remove unused code for NL before LBRACKET
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
Labels: internal

#9804 cleanup documentation for ordering
  src/library/scala/math/Ordering.scala
Labels: documentation

#9803 Stack popAll preserves order
  src/library/scala/collection/mutable/Stack.scala
  test/junit/scala/collection/mutable/StackTest.scala
Labels: library:collections

#9799 Fix slicing of views of `IndexedSeq`s (including fixing 2.13.7-only `reverseIterator` regression)
  src/library/scala/collection/IndexedSeqView.scala
  src/library/scala/collection/Iterator.scala
  test/junit/scala/collection/IndexedSeqViewTest.scala
  test/junit/scala/collection/immutable/SmallMapTest.scala
Labels: library:collections
