Repository scala/scala, pull requests merged in 2021-04, with the labels that each got.

#9562 spec: include pattern matching function in block expression
  spec/06-expressions.md
Labels: documentation

#9444 sbt 1.5 (was 1.4)
  build.sbt
  project/JitWatch.scala
  project/ScriptCommands.scala
  project/build.properties
  project/plugins.sbt
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
  test/jcstress/project/build.properties
Labels: internal

#9554 Spec: add block expression to function application
  spec/06-expressions.md
Labels: documentation

#9560 Support `?` as wildcard marker under -Xsource:3
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/pos/wildcards-future.scala
Labels: release-notes

#9559 Upgrade Dotty to 3.0.0-RC2
  project/DottySupport.scala
Labels: internal

#9566 Replace 0.asInstanceOf[B] with null.asInstanceOf[B]
  src/library/scala/collection/TraversableOnce.scala
Labels: internal

#9570 Fix typo in TastyFormat.scala
  src/compiler/scala/tools/tasty/TastyFormat.scala
Labels: documentation, internal

#9575 Drop old ScalaVersions
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/Parsing.scala
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/Unapplies.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/internal/settings/MutableSettings.scala
  src/reflect/scala/reflect/internal/tpe/TypeComparers.scala
  src/reflect/scala/reflect/runtime/Settings.scala
Labels: internal

#9504 More accurate outer checks in patterns
  src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala
  test/files/neg/t7721.check
  test/files/pos/t11534.scala
  test/files/run/t11534b.scala
  test/files/run/t11534c.scala
Labels: release-notes

#9558 Support `case` in pattern bindings under -Xsource:3
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  test/files/neg/for-comprehension-case-future.check
  test/files/neg/for-comprehension-case-future.scala
  test/files/neg/for-comprehension-case.check
  test/files/neg/for-comprehension-case.scala
Labels: release-notes

#9582 Support Scala 3 wildcard and renaming imports under -Xsource:3
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/neg/import-future.check
  test/files/neg/import-future.scala
  test/files/pos/import-future.scala
Labels: release-notes

#9518 REPL: handle `.inputrc`
  build.sbt
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
Labels: release-notes, tool:REPL

#9580 Allow soft keywords `open` and `infix` under -Xsource:3
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/neg/open-infix-future.check
  test/files/neg/open-infix-future.scala
  test/files/pos/open-infix-future.scala
Labels: release-notes

#9584 Support Scala 3 vararg splice syntax under -Xsource:3
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  test/files/pos/varargs-future.scala
Labels: release-notes

#7785 Integrate splain – implicit resolution chains and type diffs in error messages
  project/ScalaOptionParser.scala
  src/compiler/scala/reflect/reify/Taggers.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/typechecker/AnalyzerPlugins.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
  src/compiler/scala/tools/nsc/typechecker/splain/SplainData.scala
  src/compiler/scala/tools/nsc/typechecker/splain/SplainDiagnostics.scala
  src/compiler/scala/tools/nsc/typechecker/splain/SplainErrors.scala
  src/compiler/scala/tools/nsc/typechecker/splain/SplainFormatData.scala
  src/compiler/scala/tools/nsc/typechecker/splain/SplainFormatting.scala
  src/compiler/scala/tools/reflect/ToolBox.scala
  src/manual/scala/man1/scalac.scala
  src/reflect/scala/reflect/internal/TypeDebugging.scala
  src/reflect/scala/reflect/macros/Typers.scala
  test/files/neg/implicit-any2stringadd.scala
  test/files/neg/implicit-log.check
  test/files/neg/implicit-log.scala
  test/files/neg/implicit-shadow.check
  test/files/neg/implicit-shadow.scala
  test/files/neg/t6323a.check
  test/files/neg/t6323a.scala
  test/files/run/splain-tree.check
  test/files/run/splain-tree.scala
  test/files/run/splain-truncrefined.check
  test/files/run/splain-truncrefined.scala
  test/files/run/splain.check
  test/files/run/splain.scala
Labels: release-notes

#9496 GitHub Actions: build and test on Windows [ci: last-only]
  .gitattributes
  .github/workflows/ci.yml
  project/build.properties
  scripts/common
  scripts/jobs/integrate/ide
  scripts/jobs/integrate/windows
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
Labels: internal

#9586 Upgrade Dotty to 3.0.0-RC3
  project/DottySupport.scala
Labels: internal

#9585 GitHub Actions: Windows CI: align with Travis-CI (simpler bootstrap) [ci: last-only]
  .github/workflows/ci.yml
Labels: internal

#9579 Build and test mergely on JDK 16 (on Travis)
  .travis.yml
  build.sbt
  project/MimaFilters.scala
  src/compiler/scala/tools/nsc/ast/TreeBrowsers.scala
  src/library/scala/reflect/package.scala
  src/reflect/scala/reflect/internal/util/AbstractFileClassLoader.scala
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/files/neg/macro-invalidret.check
  test/files/presentation/infix-completion.check
  test/files/presentation/infix-completion2.check
  test/files/run/reflection-magicsymbols-invoke.check
  test/files/run/repl-trim-stack-trace.check
  test/files/run/t3613.scala
  test/files/run/t6344.check
  test/files/run/t7741a.check
  test/files/run/t7741a/GroovyInterface$1Dump.java
  test/files/run/t9529.check
Labels: internal

#9590 Fix typo in ExprBuilder.scala
  src/compiler/scala/tools/nsc/transform/async/ExprBuilder.scala
Labels: internal

#9578 remove references to Bintray and JCenter
  scripts/common
Labels: internal

#9589 [backport] Support for Scala 3 syntax under `-Xsource:3`
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/nsc/typechecker/Unapplies.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/neg/for-comprehension-case-future.check
  test/files/neg/for-comprehension-case-future.scala
  test/files/neg/for-comprehension-case.check
  test/files/neg/for-comprehension-case.scala
  test/files/neg/import-future.check
  test/files/neg/import-future.scala
  test/files/neg/open-infix-future.check
  test/files/neg/open-infix-future.scala
  test/files/pos/import-future.scala
  test/files/pos/open-infix-future.scala
  test/files/pos/varargs-future.scala
  test/files/pos/wildcards-future.scala
Labels: release-notes

#9587 Partest tests can require a java version range
  CONTRIBUTING.md
  src/partest/scala/tools/partest/ConsoleLog.scala
  src/partest/scala/tools/partest/TestState.scala
  src/partest/scala/tools/partest/nest/AbstractRunner.scala
  src/partest/scala/tools/partest/nest/Runner.scala
  test/files/pos/sammy_java8/F.java
  test/files/pos/sammy_java8/Test.scala
  test/files/pos/t7398/Iterator.java
  test/files/pos/t7398/Test.scala
  test/files/pos/t8852/Interface.java
  test/files/pos/t8852/Test.scala
  test/files/run/sammy_java8.scala
  test/files/run/t12348.scala
  test/files/run/t7398.scala
  test/files/run/t7825.scala
  test/files/run/t8852a.scala
Labels: internal

#9548 SI-12290: support JDK15 text blocks in Java parser
  src/compiler/scala/tools/nsc/javac/JavaScanners.scala
  test/files/neg/text-blocks.check
  test/files/neg/text-blocks/Invalid1.java
  test/files/neg/text-blocks/Invalid2.java
  test/files/run/t12290.check
  test/files/run/t12290/Test.scala
  test/files/run/t12290/TextBlocks.java
Labels: java interop, release-notes

#9593 Partest: use a `// java: -flags` comment instead of .javaopts file
  src/partest/scala/tools/partest/nest/Runner.scala
  src/partest/scala/tools/partest/package.scala
  test/files/jvm/methvsfield.javaopts
  test/files/jvm/methvsfield/Test_2.scala
  test/files/jvm/natives.javaopts
  test/files/jvm/natives.scala
  test/files/jvm/t1600.javaopts
  test/files/jvm/t1600.scala
  test/files/jvm/t8689.javaopts
  test/files/jvm/t8689.scala
  test/files/run/bridges.javaopts
  test/files/run/bridges.scala
  test/files/run/lambda-serialization-gc.javaopts
  test/files/run/lambda-serialization-gc.scala
  test/files/run/reflection-mem-glbs.javaopts
  test/files/run/reflection-mem-glbs.scala
  test/files/run/reflection-mem-tags.javaopts
  test/files/run/reflection-mem-tags.scala
  test/files/run/reify_copypaste1.javaopts
  test/files/run/reify_copypaste1.scala
  test/files/run/shutdownhooks.javaopts
  test/files/run/shutdownhooks.scala
  test/files/run/stream-gc.javaopts
  test/files/run/stream-gc.scala
  test/files/run/t2318.javaopts
  test/files/run/t2318.scala
  test/files/run/t4415.scala
  test/files/run/t6411a.javaopts
  test/files/run/t6411a.scala
  test/files/run/t6488.javaopts
  test/files/run/t6488.scala
  test/files/run/t7634.javaopts
  test/files/run/t7634.scala
  test/files/run/t7805-repl-i.javaopts
  test/files/run/t7805-repl-i.scala
  test/files/run/t8266-octal-interp.javaopts
  test/files/run/t8928.javaopts
  test/files/run/t8928/Test_1.scala
  test/files/run/type-tag-leak.javaopts
  test/files/run/type-tag-leak.scala
Labels: internal

#9591 [forward port from 2.12.x] GitHub Actions: build and test on Windows
  .gitattributes
  .github/workflows/ci.yml
  scripts/jobs/integrate/ide
  scripts/jobs/integrate/windows
Labels: internal

#9598 sbt 1.5.1 (was 1.5.0)
  project/build.properties
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
  test/jcstress/project/build.properties
Labels: internal

#9594 Support writing `&` instead of `with` in types under `-Xsource:3`
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/neg/and-future.check
  test/files/neg/and-future.scala
  test/files/pos/and-future.scala
Labels: release-notes

#9571 Rework AlmostFinalValue, to make it as fast as possible
  build.sbt
  src/reflect/scala/reflect/internal/util/AlmostFinalValue.java
  src/reflect/scala/reflect/internal/util/Statistics.scala
  src/reflect/scala/reflect/internal/util/StatisticsStatics.java
  test/benchmarks/src/main/java/scala/reflect/internal/util/AlmostFinalValueBenchmarkStatics.java
  test/benchmarks/src/main/scala/scala/reflect/internal/util/AlmostFinalValueBenchmark.scala
Labels: performance

#9572 Put all debug/developer behind an AlmostFinalValue false
  src/compiler/scala/tools/nsc/CompilerCommand.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/MainTokenMetric.scala
  src/compiler/scala/tools/nsc/ast/Positions.scala
  src/compiler/scala/tools/nsc/backend/jvm/BCodeSkelBuilder.scala
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala
  src/compiler/scala/tools/nsc/backend/jvm/CodeGen.scala
  src/compiler/scala/tools/nsc/backend/jvm/PostProcessorFrontendAccess.scala
  src/compiler/scala/tools/nsc/plugins/Plugins.scala
  src/compiler/scala/tools/nsc/reporters/Reporter.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/symtab/SymbolLoaders.scala
  src/compiler/scala/tools/nsc/symtab/SymbolTrackers.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala
  src/compiler/scala/tools/nsc/tasty/bridge/ContextOps.scala
  src/compiler/scala/tools/nsc/transform/CleanUp.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/compiler/scala/tools/nsc/transform/TypeAdaptingTransformer.scala
  src/compiler/scala/tools/nsc/transform/async/AsyncPhase.scala
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/TreeCheckers.scala
  src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
  src/compiler/scala/tools/nsc/typechecker/TypeStrings.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/nsc/typechecker/TypersTracking.scala
  src/compiler/scala/tools/reflect/ToolBoxFactory.scala
  src/interactive/scala/tools/nsc/interactive/REPL.scala
  src/reflect/scala/reflect/internal/Kinds.scala
  src/reflect/scala/reflect/internal/Mirrors.scala
  src/reflect/scala/reflect/internal/Printers.scala
  src/reflect/scala/reflect/internal/SymbolTable.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/Trees.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/internal/pickling/UnPickler.scala
  src/reflect/scala/reflect/internal/settings/MutableSettings.scala
  src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
  src/reflect/scala/reflect/internal/tpe/TypeComparers.scala
  src/reflect/scala/reflect/internal/tpe/TypeConstraints.scala
  src/reflect/scala/reflect/internal/tpe/TypeToStrings.scala
  src/reflect/scala/reflect/internal/util/StatisticsStatics.java
  src/reflect/scala/reflect/runtime/JavaMirrors.scala
  src/reflect/scala/reflect/runtime/Settings.scala
  src/reflect/scala/reflect/runtime/SymbolTable.scala
  src/scaladoc/scala/tools/nsc/ScalaDoc.scala
  src/scaladoc/scala/tools/nsc/doc/ScaladocAnalyzer.scala
  src/scaladoc/scala/tools/nsc/doc/Uncompilable.scala
Labels: performance
