Repository scala/scala, pull requests merged in 2021-08, with the labels that each got.

#9687 Accept supplementary Unicode characters in source code
  build.sbt
  spec/01-lexical-syntax.md
  spec/06-expressions.md
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/compiler/scala/tools/nsc/symtab/classfile/AbstractFileReader.scala
  src/partest/scala/tools/partest/DirectTest.scala
  src/partest/scala/tools/partest/package.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/files/neg/surrogates.check
  test/files/neg/surrogates.scala
  test/files/pos/surrogates.scala
  test/files/run/t12276.scala
  test/files/run/t1406.scala
  test/files/run/t1406b.check
  test/files/run/t1406b.scala
  test/files/run/t9915/Test_2.scala
  test/junit/scala/tools/testkit/AssertUtilTest.scala
Labels: release-notes

#9716 fix scala/bug#12420: complete LambdaType param symbols lazily
  src/compiler/scala/tools/nsc/tasty/TreeUnpickler.scala
  src/compiler/scala/tools/nsc/tasty/bridge/ContextOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/FlagOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/TastyCore.scala
  src/compiler/scala/tools/nsc/tasty/bridge/TypeOps.scala
  test/files/run/tasty-lambdatype-strawman.check
  test/files/run/tasty-lambdatype-strawman.scala
  test/tasty/pos/src-2/dottyi3149/TestFooChildren.scala
  test/tasty/run/src-2/tastytest/TestIssue12420.scala
  test/tasty/run/src-3/tastytest/issue12420/ShareLambda.scala
  test/tasty/run/src-3/tastytest/issue12420/absurd.scala
  test/tasty/run/src-3/tastytest/issue12420/hasId.scala
Labels: tastyreader

#9656 Improvements to tab completion and code assist in the REPL
  src/interactive/scala/tools/nsc/interactive/Global.scala
  src/reflect/scala/reflect/internal/Positions.scala
  src/reflect/scala/reflect/internal/Printers.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/Completion.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/LoopCommands.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ReplCompletion.scala
  src/repl/scala/tools/nsc/interpreter/IMain.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
  test/files/run/repl-completions.check
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
  versions.properties
Labels: tool:REPL

#9719 Clean up junit test
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/junit/scala/util/matching/CharRegexTest.scala
  test/junit/scala/util/matching/RegexTest.scala
Labels: internal

#9721 Allow `case` in pattern bindings even without -Xsource:3
  spec/06-expressions.md
  spec/13-syntax-summary.md
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  test/files/neg/for-comprehension-case-future.check
  test/files/neg/for-comprehension-case-future.scala
  test/files/neg/for-comprehension-case.check
  test/files/neg/for-comprehension-case.scala
Labels: release-notes

#9729 remove Whitesource
  build.sbt
  project/plugins.sbt
  src/intellij/scala.ipr.SAMPLE
Labels: internal

#9728 Fix ArraySeq/Vector array sharing optimization in Vector.from
  src/library/scala/collection/immutable/Vector.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: performance, library:collections

#9731 fix scala/bug#12399: add tests
  test/tasty/run/src-2/a/Main.scala
  test/tasty/run/src-2/tastytest/TestOpaquesPackage.scala
  test/tasty/run/src-3/tastytest/opaques/package.scala
Labels: tastyreader

#9730 fix scala/bug#12409: tasty - fix case class apply default params
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  test/tasty/run/src-2/tastytest/TestCaseClassDefault.scala
  test/tasty/run/src-3/tastytest/CaseClassDefault.scala
Labels: tastyreader

#9720 Optimise ArraySeq#map
  src/library/scala/collection/immutable/ArraySeq.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/ArraySeqBenchmark.scala
Labels: performance, library:collections

#9726 Do not compute size in TrieMap#isEmpty
  src/library/scala/collection/concurrent/MainNode.java
  src/library/scala/collection/concurrent/TrieMap.scala
  test/junit/scala/collection/concurrent/TrieMapTest.scala
Labels: performance, library:collections, library:concurrent

#9727 Fix TrieMap#{filterInPlace,mapValuesInPlace}
  project/MimaFilters.scala
  src/library/scala/collection/concurrent/Map.scala
  src/library/scala/collection/concurrent/TrieMap.scala
  src/library/scala/collection/mutable/Map.scala
  test/junit/scala/collection/concurrent/ConcurrentMapTestHelper.scala
  test/junit/scala/collection/concurrent/ConcurrentMapTester.scala
  test/junit/scala/collection/concurrent/TrieMapTest.scala
  test/junit/scala/collection/convert/JConcurrentMapWrapperTest.scala
Labels: library:collections, library:concurrent

#9724 Allow `import x.{*, given}` under -Xsource:3
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  test/files/pos/import-future.scala
Labels: release-notes

#9736 [backport] Allow `import x.{*, given}` under -Xsource:3
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/pos/import-future.scala
Labels: release-notes

#9258 Make ArrayBuffer's iterator fail-fast
  project/MimaFilters.scala
  src/library/scala/collection/IndexedSeq.scala
  src/library/scala/collection/IndexedSeqView.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/CheckedIndexedSeqView.scala
  test/benchmarks/README.md
  test/benchmarks/src/main/scala/scala/collection/mutable/ArrayBufferBenchmark.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
  test/junit/scala/collection/mutable/MutationTrackingTest.scala
Labels: release-notes, library:collections
