Repository scala/scala, pull requests merged in 2021-12, with the labels that each got.

#9816 fix build (JDK 17 + bootstrapped + fatal warnings)
  src/compiler/scala/tools/reflect/WrappedProperties.scala
  src/library/scala/sys/SystemProperties.scala
Labels: internal

#9828 Update sbt 1.5.5 to 1.5.6
  project/build.properties
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/jcstress/project/build.properties
Labels: internal

#9830 upgrade sbt, logback, slf4j
  build.sbt
  project/build.properties
  project/plugins.sbt
  scripts/common
Labels: internal

#9829 Tweak inferMethodInstance to consider if implicits are enabled
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
Labels: prio:blocker

#9818 GroupedIterator improvements
  src/library/scala/collection/Iterator.scala
Labels: library:collections

#9831 bye bye Gitter, hello Discord
  CONTRIBUTING.md
  README.md
Labels: documentation, internal

#9842 Update biz.aQute.bndlib to 6.1.0 in 2.12.x
  project/plugins.sbt
Labels: internal

#9843 Update jackson-annotations, jackson-core to 2.9.10 in 2.12.x
  build.sbt
Labels: internal

#9845 Update jackson-dataformat-yaml to 2.9.10 in 2.12.x
  build.sbt
Labels: internal

#9848 Update sbt-mima-plugin to 0.9.2 in 2.12.x
  project/plugins.sbt
Labels: internal

#9849 Update sbt-header to 5.6.0 in 2.12.x
  project/plugins.sbt
Labels: internal

#9852 Update org.eclipse.jgit to 4.6.1.201703071140-r in 2.12.x
  project/plugins.sbt
Labels: internal

#9859 Revert PR #9818 (GroupedIterator improvements)
  src/library/scala/collection/Iterator.scala
Labels: prio:blocker, internal

#9854 Update sbt to 1.5.7 in 2.12.x
  project/build.properties
  scripts/common
Labels: internal

#9844 Update jackson-databind to 2.9.10.8 in 2.12.x
  build.sbt
Labels: internal

#9860 Update sbt-mima-plugin to 1.0.1 in 2.12.x
  project/plugins.sbt
Labels: internal

#9856 Update sbt-jmh to 0.4.3 in 2.12.x
  project/plugins.sbt
Labels: internal

#9853 Update jol-core to 0.16 in 2.12.x
  build.sbt
Labels: internal

#9862 Update org.eclipse.jgit to 4.11.9.201909030838-r in 2.12.x
  project/plugins.sbt
Labels: internal

#9846 Update jackson-module-scala to 2.9.10 in 2.12.x
  build.sbt
Labels: internal

#9866 Update jackson-module-scala to 2.13.0 in 2.12.x
  build.sbt
Labels: internal

#9857 Update jackson-annotations, jackson-core to 2.13.0 in 2.12.x
  build.sbt
Labels: internal

#9870 upgrade all jackson libraries together
  build.sbt
Labels: internal

#9875 [backport] cut down on warning noise in 2.12 build
  build.sbt
  src/partest/scala/tools/partest/nest/UnsafeAccess.java
Labels: internal

#9879 Update sbt to 1.5.8 in 2.12.x
  project/build.properties
  scripts/common
Labels: internal
