Repository scala/scala, pull requests merged in 2021-09, with the labels that each got.

#9746 Fix scala/bug#12449: keep ThisType prefix in more places
  src/compiler/scala/tools/nsc/tasty/TreeUnpickler.scala
  src/compiler/scala/tools/nsc/tasty/bridge/ContextOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/SymbolOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/TreeOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/TypeOps.scala
  test/tasty/neg/src-2/TestThisTypes.check
  test/tasty/neg/src-2/TestThisTypes_fail.scala
  test/tasty/neg/src-3/ThisTypes.scala
  test/tasty/run/src-2/tastytest/TestAsyncSuite.scala
  test/tasty/run/src-2/tastytest/TestThisTypes.scala
  test/tasty/run/src-3/tastytest/ThisTypes.scala
  test/tasty/run/src-3/tastytest/testsuite/testsuites.scala
Labels: tastyreader

#9745 Merge 2.12.x to 2.13.x [ci: last-only]
  build.sbt
  project/plugins.sbt
  src/intellij/scala.ipr.SAMPLE
Labels: internal

#9741 Add specialized builder for s.c.i.SeqMap
  project/MimaFilters.scala
  src/library/scala/collection/immutable/SeqMap.scala
  test/junit/scala/collection/FactoriesTest.scala
  test/junit/scala/collection/immutable/SeqMapTest.scala
Labels: performance, library:collections

#9739 Statics.releaseFence() should also catch NoSuchMethodException for java.lang.invoke.VarHandle.releaseFence() call
  src/library/scala/runtime/Statics.java
Labels: release-notes

#9749 Prevent compilation of library/reflect/compiler on bsp import
  project/ScaladocSettings.scala
Labels: internal

#9750 Minor build cleanup
  build.sbt
Labels: internal

#9748 Allow concrete private interface methods in Java sources
  src/compiler/scala/tools/nsc/javac/JavaParsers.scala
  test/files/pos/t12393/R1.java
Labels: java interop

#9733 Optimise TrieMap methods by using eq
  project/MimaFilters.scala
  src/library/scala/collection/concurrent/Map.scala
  src/library/scala/collection/concurrent/TrieMap.scala
Labels: performance, library:collections, library:concurrent

#9759 fix Sonatype publishing
  .travis.yml
Labels: internal

#9760 re-STARR on 2.12.15
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#9761 Fix range position end for infix calls
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  test/files/run/infix-rangepos.scala
Labels: release-notes

#9764 test on JDK 18-ea
  .travis.yml
Labels: internal

#9766 Remove unused AssertUtil.assert8.
  test/junit/scala/tools/testing/AssertUtil.scala
Labels: internal

#9770 Revert "test on JDK 18-ea"
  .travis.yml
Labels: internal

#9772 Windows CI: test on 17 final (not early-access)
  .github/workflows/ci.yml
Labels: internal

#9775 [backport] fix t2318 on JDK 17
  test/files/run/t2318.scala
Labels: internal

#9773 [ci: last-only] Merge 2.12.x to 2.13.x (September 28, 2021)
  .github/workflows/ci.yml
  .travis.yml
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/files/jvm/javaReflection/Test.scala
  test/files/run/infix-rangepos.scala
Labels: internal
