Repository scala/scala, pull requests merged in 2021-03, with the labels that each got.

#9527 Backport fix for detecting jar
  src/compiler/scala/tools/nsc/classpath/FileUtils.scala
  src/compiler/scala/tools/nsc/io/Jar.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  test/files/run/t12019/J_1.java
  test/files/run/t12019/Test.scala
Labels: prio:blocker

#9524 patmat: Remove some dead/stale code+TODOs & cleanup some
  src/compiler/scala/tools/nsc/ast/TreeDSL.scala
  src/compiler/scala/tools/nsc/transform/ExplicitOuter.scala
  src/compiler/scala/tools/nsc/transform/patmat/Logic.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchCodeGen.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchOptimization.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchTranslation.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchTreeMaking.scala
  src/compiler/scala/tools/nsc/transform/patmat/PatternMatching.scala
  src/compiler/scala/tools/nsc/typechecker/Duplicators.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/interactive/scala/tools/nsc/interactive/tests/core/CoreTestDefs.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/presentation/t8941/Runner.scala
  test/files/run/t3835.scala
Labels: internal

#9530 Follow JDK 11+ spec for signature polymorphic methods
  spec/06-expressions.md
  src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala
  src/compiler/scala/tools/nsc/backend/jvm/opt/BytecodeUtils.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: backport candidate

#9529 [nomerge] Reuse `tasksupport` in CombinerFactory
  src/library/scala/collection/parallel/ParIterableLike.scala
  test/junit/scala/collection/parallel/TaskTest.scala
Labels: library:collections

#9519 Use -s option to decode junit test names
  build.sbt
Labels: internal

#4400 Can catch any expression
  spec/06-expressions.md
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/TreeBuilder.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/neg/catch-all.check
  test/files/neg/catch-all.scala
  test/files/neg/t5887.check
  test/files/neg/t5887.scala
  test/files/run/t5887.scala
Labels: release-notes

#9482 Import from _root_
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  test/files/neg/t9125.check
  test/files/neg/t9125.scala
  test/files/pos/t283.scala
  test/files/pos/t9125.scala
Labels: release-notes

#9540 Try to fix the flaky patmat test
  src/compiler/scala/tools/nsc/transform/patmat/Logic.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  src/compiler/scala/tools/nsc/transform/patmat/Solving.scala
Labels: internal

#9539 sbt 1.4.9 (was 1.4.7)
  project/build.properties
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/benchmarks/project/build.properties
  test/jcstress/project/build.properties
Labels: internal

#9535 Fix regression in ZipArchive
  src/reflect/scala/reflect/io/ZipArchive.scala
  test/junit/scala/reflect/io/ZipArchiveTest.scala
Labels: backport candidate

#9533 spec private class
  spec/05-classes-and-objects.md
Labels: documentation

#9521 REPL: improve tab-completion of `:`-prefixed commands (fixes scala/bug#12264)
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/Completion.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/LoopCommands.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ReplCompletion.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
Labels: tool:REPL

#8383 add testing for status quo of Byte and Short toHexString
  test/files/run/richs.check
  test/files/run/richs.scala
  test/junit/scala/lang/RicherTest.scala
Labels: internal

#9536 allow $ escaping double quotes in interpolations under -Xsource:3
  spec/01-lexical-syntax.md
  spec/13-syntax-summary.md
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  test/files/neg/t5856.check
  test/files/run/interpolation.check
  test/files/run/interpolation.scala
Labels: release-notes

#9336 Make more annotations extend `ConstantAnnotation`
  project/MimaFilters.scala
  src/library/scala/annotation/elidable.scala
  src/library/scala/annotation/implicitAmbiguous.scala
  src/library/scala/annotation/implicitNotFound.scala
  src/library/scala/annotation/migration.scala
  src/library/scala/deprecated.scala
  src/library/scala/deprecatedInheritance.scala
  src/library/scala/deprecatedName.scala
  src/library/scala/deprecatedOverriding.scala
  test/files/run/t5225_2.check
Labels: library:base, welcome

#9547 clarify what it means to 'usually' evaluate in that order
  spec/06-expressions.md
Labels: documentation

#9552 fix #12357: all inline defs from tasty are treated as macros
  src/compiler/scala/tools/nsc/tasty/bridge/ContextOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/SymbolOps.scala
  src/compiler/scala/tools/nsc/tasty/bridge/TreeOps.scala
  test/tasty/neg/src-2/TestHello.check
  test/tasty/neg/src-2/TestHello_2.check
  test/tasty/neg/src-2/TestHello_2_fail.scala
  test/tasty/neg/src-2/TestHello_fail.scala
  test/tasty/neg/src-3/HelloWorld.scala
  test/tasty/run/src-2/tastytest/TestInlineCompat.scala
  test/tasty/run/src-2/tastytest/TestInlineCompat2.scala
  test/tasty/run/src-3/tastytest/InlineCompat.scala
  test/tasty/run/src-3/tastytest/InlineCompat2.scala
Labels: tastyreader

#9546 Don't pickle `@nowarn` annotations...
  src/reflect/scala/reflect/internal/AnnotationInfos.scala
Labels: prio:blocker

#9510 REPL: when tab-completing, don't show a method as deprecated unless all overloads are deprecated
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ReplCompletion.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
Labels: tool:REPL
