Repository scala/scala, pull requests merged in 2022-01, with the labels that each got.

#9876 JQuery 3.6.0 (was 3.5.1)
  build.sbt
  project/ScaladocSettings.scala
  spec/_layouts/default.yml
  spec/_layouts/toc.yml
  src/intellij/scala.ipr.SAMPLE
  src/scaladoc/scala/tools/nsc/doc/html/HtmlFactory.scala
Labels: tool:scaladoc

#9896 re-STARR onto 2.13.8
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#9895 upgrade tasty reader tests for Scala 3.1.1
  project/DottySupport.scala
  test/tasty/neg-move-macros/src-3/MacroCompat.scala
  test/tasty/pos/src-3/tastytest/AnythingIsPossible.scala
  test/tasty/run/src-3/tastytest/AnythingIsPossible.scala
  test/tasty/run/src-3/tastytest/InlineCompat.scala
  test/tasty/run/src-3/tastytest/InlineCompat2.scala
  test/tasty/run/src-3/tastytest/MacroCompat.scala
Labels: internal, tastyreader

#9888 Tweak PriorityQueue class doc
  src/library/scala/collection/mutable/PriorityQueue.scala
  test/junit/scala/collection/mutable/PriorityQueueTest.scala
Labels: documentation

#9883 Update junit-interface to 0.13.3
  build.sbt
Labels: internal

#9763 sbt 1.6 (was 1.5)
  project/build.properties
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/jcstress/project/build.properties
Labels: internal

#9874 Tweak doc for ordering of SeqMap
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/SeqMap.scala
Labels: documentation

#9897 Update sbt to 1.6.1
  project/build.properties
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/jcstress/project/build.properties
Labels: internal

#9867 Simplify grouped iterator
  src/library/scala/collection/Iterator.scala
  test/files/run/unittest_collection.scala
  test/files/run/unittest_iterator.scala
  test/junit/scala/collection/IteratorTest.scala
  test/junit/scala/collection/mutable/ListBufferTest.scala
Labels: performance, library:collections

#8491 Use ArrayBuilder for line indices
  src/reflect/scala/reflect/internal/util/SourceFile.scala
  test/junit/scala/reflect/internal/util/SourceFileTest.scala
Labels: performance

#9904 Avoid sys.props
  project/genprod.scala
  src/library/scala/Function0.scala
  src/library/scala/Function1.scala
  src/library/scala/Function2.scala
  src/reflect/scala/reflect/io/ZipArchive.scala
Labels: documentation

#9903 Ignore .bsp
  .gitignore
Labels: internal

#9821 [bug#12473] Throw on unsigned type in `NumericRange#reverse`
  src/library/scala/collection/immutable/NumericRange.scala
  test/junit/scala/runtime/RichCharTest.scala
Labels: library:collections

#9882 Update spec for assignment to prefix op expr
  spec/06-expressions.md
  spec/13-syntax-summary.md
  test/files/pos/i13282.scala
Labels: documentation

#9885 Test for usage doc comment position
  test/junit/scala/tools/nsc/parser/ParserTest.scala
Labels: internal

#9905 [ci: last-only] Merge 2.12.x to 2.13.x (January 18, 2022)
  NOTICE
  build.sbt
  doc/LICENSE.md
  doc/License.rtf
  project/ScaladocSettings.scala
  project/VersionUtil.scala
  project/plugins.sbt
  spec/_layouts/default.yml
  spec/_layouts/toc.yml
  src/compiler/scala/tools/nsc/typechecker/Macros.scala
  src/library/scala/util/Properties.scala
  src/scaladoc/scala/tools/nsc/doc/html/HtmlFactory.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  src/scalap/decoder.properties
Labels: internal

#9754 Tab completion for aliased constructors in REPL
  src/interactive/scala/tools/nsc/interactive/CompilerControl.scala
  src/interactive/scala/tools/nsc/interactive/Global.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
Labels: tool:REPL

#9907 remove now-unused JDK 6/7 code in backend
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
Labels: internal

#9909 minor cleanup: avoid importing language.experimental._
  test/files/pos/t7046-2/Macros_1.scala
  test/files/pos/t7377/Macro_1.scala
  test/files/pos/t7987/Macro_1.scala
  test/files/run/macro-system-properties.check
  test/files/run/macro-system-properties.scala
  test/junit/scala/tools/nsc/PipelineMainTest.scala
Labels: internal

#9913 Update slf4j-nop to 1.7.35 in 2.12.x
  project/plugins.sbt
Labels: internal

#9797 BigInt delegates for inputs not in domain
  src/library/scala/math/BigInt.scala
  test/junit/scala/math/BigIntTest.scala
Labels: library:base
