Repository scala/scala, pull requests merged in 2022-04, with the labels that each got.

#9983 Fix NPE regression in Vector.prependedAll
  src/library/scala/collection/immutable/Vector.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: release-notes, library:collections

#9986 Avoid unnecessary update of a map when updatedWith changes nothing.
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/SortedMap.scala
Labels: performance, library:collections

#10004 Prefer StandardCharsets
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/PickleExtractor.scala
  src/compiler/scala/tools/nsc/PipelineMain.scala
  src/compiler/scala/tools/nsc/backend/jvm/ClassfileWriters.scala
  src/compiler/scala/tools/nsc/fsc/CompileSocket.scala
  src/library/scala/io/Codec.scala
  src/reflect/scala/reflect/internal/util/FileUtils.scala
  src/reflect/scala/reflect/runtime/JavaMirrors.scala
  src/testkit/scala/tools/testkit/VirtualCompilerTesting.scala
Labels: internal

#10002 Use normal mixed-in Product.productIterator
  src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala
  test/files/run/idempotency-case-classes.check
  test/files/scalap/caseClass.check
  test/files/scalap/caseObject.check
  test/scaladoc/run/implicits-chaining.scala
Labels: internal

#9988 Consistent slice sorting
  src/library/scala/util/Sorting.scala
  test/junit/scala/util/SortingTest.scala
Labels: library:collections

#10006 Maintain iteration order in SetOps.--
  src/library/scala/collection/Map.scala
  src/library/scala/collection/Set.scala
  test/scalacheck/scala/collection/mutable/LinkedHashMapProperties.scala
  test/scalacheck/scala/collection/mutable/LinkedHashSetProperties.scala
Labels: library:collections

#10005 [backport] Allow ? as a wildcard even without -Xsource:3
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  test/files/pos/wildcards-present.scala
Labels: release-notes

#9978 Update links to completed sips
  spec/11-annotations.md
  src/library/scala/Array.scala
Labels: documentation

#10009 Fix a tree shape in untypecheck-ing extractors
  src/compiler/scala/tools/nsc/ast/Trees.scala
  test/files/run/t12577/A_1.scala
  test/files/run/t12577/B_2.scala
Labels: backport candidate

#10000 [nomerge] Upgrade to asm 9.3, for JDK19 support
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  test/junit/scala/tools/nsc/settings/TargetTest.scala
  versions.properties
Labels: release-notes

#10001 Support JDK19
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  test/junit/scala/tools/nsc/settings/TargetTest.scala
  versions.properties
Labels: release-notes

#10013 Update sbt-header to 5.7.0 in 2.12.x
  project/plugins.sbt
Labels: internal

#10018 Only check accessible extension for non-empty refinement
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  test/files/pos/t11787b.scala
Labels: prio:blocker, internal
