Repository scala/scala, pull requests merged in 2022-09, with the labels that each got.

#10128 revert argument parsing changes (PRs 10114 and 10123)
  src/compiler/scala/tools/nsc/CompilerCommand.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  src/library/scala/sys/process/Parser.scala
  test/junit/scala/sys/process/ParserTest.scala
Labels: internal

#10129 Preserve null policy in wrapped Java Map
  src/library/scala/collection/concurrent/Map.scala
  src/library/scala/collection/convert/JavaCollectionWrappers.scala
  test/junit/scala/collection/convert/MapWrapperTest.scala
Labels: library:collections

#10137 [nomerge] New reference compiler is Scala 2.12.17
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#10143 use MiMa 1.1.1 (was 1.1.0)
  project/plugins.sbt
Labels: internal

#10146 New reference compiler is 2.13.9
  README.md
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#10140 get rid of some warnings (& tweak readme)
  README.md
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/reflect/package.scala
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: internal

#10144 fix a tiny error in the spec
  spec/03-types.md
Labels: documentation

#10142 Update typo in 6.11 Blocks of specs
  spec/06-expressions.md
Labels: documentation

#10134 for `ValueOf`, improve Scaladoc and `implicitNotFound` message
  src/library/scala/ValueOf.scala
Labels: documentation

#10152 Usage of "tpe" in an Exception message
  src/compiler/scala/reflect/reify/package.scala
  test/files/neg/t10073.check
  test/files/neg/t10073b.check
Labels: welcome

#10151 Fix a minor bug in test/scalacheck/VectorMap
  test/scalacheck/VectorMap.scala
Labels: internal

#10139 fix Range contains method
  src/library/scala/collection/immutable/Range.scala
  test/junit/scala/collection/immutable/NumericRangeTest.scala
Labels: library:collections

#10155 Revert using mixin productIterator for case class
  src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala
  test/files/run/idempotency-case-classes.check
  test/files/scalap/caseClass.check
  test/files/scalap/caseObject.check
  test/scaladoc/run/implicits-chaining.scala
Labels: prio:blocker

#10170 Regression test
  test/files/pos/t9931.scala
Labels: internal

#10169 Regression test for view slicing, stack safety
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/junit/scala/collection/IndexedSeqViewTest.scala
  test/junit/scala/collection/IteratorTest.scala
  test/junit/scala/tools/testkit/AssertUtilTest.scala
Labels: internal

#10163 Fix bugs in test/scalacheck
  test/scalacheck/TreeSeqMapTest.scala
  test/scalacheck/t2460.scala
Labels: internal
