Repository scala/scala, pull requests merged in 2022-06, with the labels that each got.

#10027 Java ConcurrentMap wrapper updateWith is compute
  project/MimaFilters.scala
  src/library/scala/collection/convert/JavaCollectionWrappers.scala
  test/junit/scala/collection/convert/MapWrapperTest.scala
Labels: library:collections

#10040 Fix AST positions for XML literals, selections from blocks
  src/compiler/scala/tools/nsc/ast/parser/MarkupParsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/SymbolicXMLBuilder.scala
  test/files/neg/t2275a.check
  test/files/neg/t2275b.check
  test/files/neg/t3604.check
  test/files/neg/t3769.check
  test/files/neg/t4069.check
  test/files/neg/t5702-neg-ugly-xbrace.check
  test/files/neg/xmltruncated7.check
  test/files/run/t12597.check
  test/files/run/t12597.scala
  test/files/run/t3368-b.check
  test/files/run/t3368-c.check
  test/files/run/t3368-d.check
  test/files/run/t3368.check
Labels: release-notes

#9982 Make -release more useful, deprecate -target
  src/compiler/scala/tools/nsc/backend/jvm/PostProcessorFrontendAccess.scala
  src/compiler/scala/tools/nsc/settings/AbsSettings.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  test/files/neg/t12543.check
  test/files/neg/t12543.scala
  test/junit/scala/tools/nsc/settings/TargetTest.scala
Labels: release-notes, prio:hi

#10056 Partest uses -release 8
  src/partest/scala/tools/partest/nest/Runner.scala
  test/files/neg/choices.check
  test/files/neg/partestInvalidFlag.check
Labels: internal

#10045 Only keep static members when looking up java static members
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/pos/t12605/A.scala
  test/files/pos/t12605/C.java
Labels: release-notes, prio:blocker

#10059 Revert "Partest uses -release 8"
  src/partest/scala/tools/partest/nest/Runner.scala
  test/files/neg/choices.check
  test/files/neg/partestInvalidFlag.check
Labels: internal

#10035 Update jackson-annotations, jackson-core, ... to 2.13.3 in 2.12.x
  build.sbt
Labels: internal

#10038 Uninstate global.treeTpe
  src/reflect/scala/reflect/internal/Types.scala
Labels: internal
