Repository scala/scala, pull requests merged in 2022-11, with the labels that each got.

#10204 sbt 1.7.3 (was .2)
  project/Osgi.scala
  project/build.properties
Labels: internal

#10184 Upgrade to asm 9.4, for JDK20 support
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: release-notes

#10203 {get=>find}Resource in some tests
  test/junit/scala/reflect/io/ZipArchiveTest.scala
  test/junit/scala/tools/nsc/classpath/ZipAndJarFileLookupFactoryTest.scala
Labels: internal

#10206 GitHub Actions: allow manual runs
  .github/workflows/ci.yml
Labels: internal

#10207 Test roundtrips path.toUri.getPath for windows
  test/junit/scala/reflect/io/ZipArchiveTest.scala
  test/junit/scala/tools/nsc/classpath/ZipAndJarFileLookupFactoryTest.scala
Labels: internal

#10205 Restore IterableWrapper equals and hashCode
  src/library/scala/collection/convert/JavaCollectionWrappers.scala
  test/junit/scala/collection/convert/EqualsTest.scala
Labels: release-notes

#10208 Tweak test for readability
  test/files/run/t1406b.check
  test/files/run/t1406b.scala
Labels: internal

#10197 Document: don't allow characters with unicode property Bidi_Class in source files
  spec/01-lexical-syntax.md
  spec/13-syntax-summary.md
Labels: welcome, documentation

#10194 Require element copies succeed
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  src/library/scala/collection/mutable/ArrayDeque.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
Labels: library:collections

#10210 Update sbt-header to 5.8.0 in 2.12.x
  project/plugins.sbt
Labels: internal

#10209 Reduce implicit search space for BuildFrom avoiding divergence
  src/library/scala/collection/BuildFrom.scala
  test/junit/scala/collection/BuildFromTest.scala
Labels: release-notes

#10215 Update scalacheck to 1.17.0
  build.sbt
  project/Osgi.scala
  test/scalacheck/scala/tools/nsc/scaladoc/HtmlFactoryTest.scala
Labels: internal

#10224 Update sbt to 1.8.0 in 2.12.x
  project/build.properties
Labels: internal

#10223 Update sbt-header to 5.9.0 in 2.12.x
  project/plugins.sbt
Labels: internal

#10225 restore a bit of spec language that went missing
  spec/06-expressions.md
Labels: documentation

#10181 =lib Make use of CompletionStage#handle instead of whenComplete
  project/MimaFilters.scala
  src/library/scala/concurrent/impl/FutureConvertersImpl.scala
  src/library/scala/jdk/javaapi/FutureConverters.scala
Labels: library:concurrent, java interop

#10227 Do not catch {Array,String}IndexOutOfBoundsException.
  src/library/scala/collection/ArrayOps.scala
  src/library/scala/collection/StringOps.scala
Labels: library:collections

#10159 Faster `Vector` concatenation
  src/library/scala/collection/immutable/Vector.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/VectorConcatAlignToWorstCaseBenchmark.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/VectorConcatBenchmark.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/VectorConcatBigVectorsBenchmark.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: release-notes, library:collections

#10195 fix and expand testing of signature polymorphic methods
  test/files/run/dotty-i11332.scala
  test/files/run/dotty-i11332b.scala
  test/files/run/dotty-t12348.scala
  test/files/run/t12348.scala
  test/files/run/t7965.scala
Labels: internal
