Repository scala/scala, pull requests merged in 2022-07, with the labels that each got.

#10047 StringBuilder append,delete,insert are this.type
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/Map.scala
  src/library/scala/collection/StringOps.scala
  src/library/scala/collection/immutable/ArraySeq.scala
  src/library/scala/collection/immutable/LazyList.scala
  src/library/scala/collection/immutable/Stream.scala
  src/library/scala/collection/mutable/ArraySeq.scala
  src/library/scala/collection/mutable/StringBuilder.scala
  src/library/scala/io/BufferedSource.scala
  src/reflect/scala/reflect/internal/Scopes.scala
  test/junit/scala/collection/mutable/StringBuilderTest.scala
Labels: library:collections

#10012 Make Scala-3-style implicit resolution explicitly opt-in rather than bundled in `-Xsource:3`
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/typechecker/Infer.scala
  test/files/neg/t2509-2.scala
  test/files/neg/t2509-3.scala
  test/files/neg/t2509-7b.scala
  test/files/pos/t2509-5.scala
  test/files/pos/t2509-6.scala
  test/files/pos/t2509-7a.scala
  test/files/run/t2509-1.scala
  test/files/run/t2509-4.scala
  test/files/run/t7768.scala
  test/junit/scala/tools/nsc/typechecker/InferencerTest.scala
Labels: release-notes

#10028 Preserve patmat-generated tree shapes for the back-end optimization
  src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/compiler/scala/tools/nsc/transform/LambdaLift.scala
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: performance

#10048 chore: Set permissions for GitHub actions
  .github/workflows/ci.yml
Labels: internal

#10070 Reflect future status of `App` in scaladoc
  src/library/scala/App.scala
Labels: documentation

#10073 simplify Actions config with setup-java@v3 caching support
  .github/workflows/ci.yml
Labels: internal

#10060 sbt 1.7.1 (was 1.6.2)
  project/build.properties
Labels: internal

#10064 Accept and ignore using in args
  spec/06-expressions.md
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/neg/i15552.check
  test/files/neg/i15552.scala
Labels: release-notes

#10077 Fix #12619: Tasty Reader: Add DEFAULTPARAM to default accessors.
  src/compiler/scala/tools/nsc/tasty/TreeUnpickler.scala
  test/tasty/pos/pre/tastytest/package.scala
  test/tasty/pos/src-2/tastytest/TestDefaultParamFlags.scala
  test/tasty/pos/src-3/tastytest/DefaultParamFlags.scala
Labels: prio:blocker, tastyreader

#9991 Clean-ups in CleanUp [ci: last-only]
  src/compiler/scala/tools/nsc/transform/CleanUp.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/compiler/scala/tools/nsc/transform/TypeAdaptingTransformer.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/StdNames.scala
Labels: internal

#10055 AnsiColor is also triggered by println
  src/partest/scala/tools/partest/instrumented/Instrumentation.scala
Labels: internal

#10057 improve escaped-quote handling in sys.process (CommandLineParser)
  src/compiler/scala/tools/cmd/CommandLineParser.scala
  src/compiler/scala/tools/cmd/package.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  src/compiler/scala/tools/reflect/ToolBoxFactory.scala
  src/library/scala/sys/process/Parser.scala
  src/partest/scala/tools/partest/DirectTest.scala
  src/partest/scala/tools/partest/ScaladocModelTest.scala
  src/partest/scala/tools/partest/nest/CommandLine.scala
  src/partest/scala/tools/partest/nest/FromString.scala
  src/partest/scala/tools/partest/nest/Runner.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/testkit/scala/tools/testkit/BytecodeTesting.scala
  test/benchmarks/src/main/scala/scala/tools/cmd/CommandLineParserBenchmark.scala
  test/files/pos/t7591/Demo.scala
  test/files/pos/t7591/Property.scala
  test/files/run/t5603.scala
  test/files/run/t7271.scala
  test/files/run/t7337.scala
  test/junit/scala/sys/process/ParserTest.scala
  test/junit/scala/tools/cmd/CommandLineParserTest.scala
  test/scaladoc/run/t5527.scala
Labels: library:base

#10080 Restore dealias Nil in Cleanup
  src/compiler/scala/tools/nsc/transform/CleanUp.scala
  src/partest/scala/tools/partest/CompilerTest.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/run/smallseq.check
  test/files/run/smallseq.scala
  test/files/run/t2318.check
  test/files/run/t2318.scala
  test/files/run/t5064.check
  test/files/run/t5064.scala
  test/files/run/t6989.check
  test/files/run/t7852.scala
  test/junit/scala/collection/immutable/ListTest.scala
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: performance

#10090 Better use of isJavaAtLeast in test
  test/junit/scala/tools/nsc/settings/TargetTest.scala
Labels: internal

#10089 [backport] Align -release and -target per Scala 3
  src/compiler/scala/tools/nsc/backend/jvm/PostProcessorFrontendAccess.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  test/files/neg/t12543.check
  test/files/neg/t12543.scala
  test/junit/scala/tools/nsc/settings/TargetTest.scala
Labels: release-notes

#10094 Fix compiler flag syntax in test file
  test/files/neg/t12565.scala
Labels: internal

#9893 Add `-Wnonunit-statement` to warn about discarded values in statement position
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/StdAttachments.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/api/Internals.scala
  src/reflect/scala/reflect/internal/ReificationSupport.scala
  src/reflect/scala/reflect/internal/StdAttachments.scala
  src/reflect/scala/reflect/internal/TreeInfo.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/neg/nonunit-if.check
  test/files/neg/nonunit-if.scala
  test/files/neg/nonunit-statement.check
  test/files/neg/nonunit-statement.scala
  test/files/neg/value-discard.check
  test/files/neg/value-discard.scala
  test/files/neg/virtpatmat_unreach_select.scala
  test/files/pos/skunky-expansion.scala
  test/files/pos/skunky.scala
Labels: release-notes, typelevel
