Repository scala/scala, pull requests merged in 2022-10, with the labels that each got.

#10172 Replace "Traversable" by corresponding "Iterable" in doc comments.
  src/library/scala/Array.scala
  src/library/scala/Option.scala
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/Map.scala
  src/library/scala/collection/mutable/Queue.scala
  src/library/scala/collection/mutable/Stack.scala
Labels: documentation

#10182 Test for old crasher
  test/files/pos/t7481.scala
Labels: internal

#10183 new reference compiler is Scala 2.13.10
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#10187 mailmap: condense Liang Yan entries
  .mailmap
Labels: internal

#10189 Update sbt to 1.7.2 in 2.12.x
  project/build.properties
Labels: internal

#10192 Test REPL valueOfTerm
  test/files/run/t12390.scala
Labels: internal

#10186 Tweak t12201 to run unoptimized
  test/files/instrumented/t12201.check
  test/files/instrumented/t12201.scala
Labels: internal

#10200 Careful interpolating windows paths
  test/files/run/t12390.scala
Labels: internal

#10199 Fix accessibility case for static java members
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  test/files/pos/t12673/A.java
  test/files/pos/t12673/B.java
  test/files/pos/t12673/Test.scala
Labels: backport candidate

#10162 Clarify spec of root contexts
  spec/02-identifiers-names-and-scopes.md
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  test/files/neg/t12513.check
  test/files/neg/t12513/predefer_2.scala
  test/files/neg/t12513/predefined_1.scala
  test/files/neg/t12513b.check
  test/files/neg/t12513b.scala
  test/files/pos/t12513c/c.scala
  test/files/pos/t12513c/xy.scala
Labels: documentation

#10085 Abstract parent copy does not suspend case copy
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  test/files/pos/t12623.scala
Labels: release-notes

#10202 sbt 1.7.3 (was .2)
  project/build.properties
Labels: internal

#10156 Fix `-release` on JDK 17 by updating optimizer class path
  project/PartestUtil.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/partest/scala/tools/partest/nest/AbstractRunner.scala
  src/partest/scala/tools/partest/nest/Runner.scala
  src/partest/scala/tools/partest/nest/RunnerSpec.scala
  src/repl/scala/tools/nsc/interpreter/ReplGlobal.scala
  test/files/neg/t3420b.check
  test/files/neg/t3420b.scala
  test/files/pos/t3420b.scala
  test/files/run/repl-release.check
  test/files/run/repl-release.scala
Labels: release-notes
