Repository scala/scala, pull requests merged in 2022-08, with the labels that each got.

#10098 Test status quo empty multi-arg infix pattern
  test/files/neg/t12110.check
  test/files/neg/t12110.scala
Labels: internal

#10102 Test that `-Wvalue-discard` output includes type params
  test/files/neg/t11379a.check
  test/files/neg/t11379a.scala
  test/files/neg/t11379b.check
  test/files/neg/t11379b.scala
  test/files/neg/t11379c.check
  test/files/neg/t11379c.scala
Labels: internal

#10097 in build, include more projects in root aggregate
  build.sbt
  src/tastytest/scala/tools/tastytest/ClasspathOps.scala
  src/tastytest/scala/tools/tastytest/Classpaths.scala
  src/tastytest/scala/tools/tastytest/Diff.scala
  src/tastytest/scala/tools/tastytest/Dotc.scala
  src/tastytest/scala/tools/tastytest/DotcDecompiler.scala
  src/tastytest/scala/tools/tastytest/Files.scala
  src/tastytest/scala/tools/tastytest/Javac.scala
  src/tastytest/scala/tools/tastytest/PrintTasty.scala
  src/tastytest/scala/tools/tastytest/Runner.scala
  src/tastytest/scala/tools/tastytest/Scalac.scala
  src/tastytest/scala/tools/tastytest/Script.scala
  src/tastytest/scala/tools/tastytest/SourceKind.scala
  src/tastytest/scala/tools/tastytest/TastyTest.scala
  src/tastytest/scala/tools/tastytest/TestFailure.scala
  src/tastytest/scala/tools/tastytest/Tests.scala
  src/tastytest/scala/tools/tastytest/internal/Runner.scala
  src/tastytest/scala/tools/tastytest/package.scala
Labels: internal

#10106 Improve Scaladoc for LinearSeqOps isEmpty, head, tail
  src/library/scala/collection/LinearSeq.scala
  test/junit/scala/collection/LinearSeqTest.scala
Labels: library:collections, documentation

#10095 Under `-Xsource:2.13`, warn about changed precedence in imports
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/neg/warn-shadowing-import-213.check
  test/files/neg/warn-shadowing-import-213/A.scala
  test/files/neg/warn-shadowing-import-213/B.scala
  test/files/neg/warn-shadowing-import-213/Test1.scala
  test/files/neg/warn-shadowing-import-213/Test2.scala
Labels: release-notes

#10117 bump Scala 3 versions in two places
  project/DottySupport.scala
Labels: internal

#10115 Tests of Source are junit
  test/files/jvm/t2104.scala
  test/files/run/t8690.check
  test/files/run/t8690.scala
  test/junit/scala/io/SourceTest.scala
Labels: internal

#10114 process.Parser strips escaping backslash
  src/library/scala/sys/process/Parser.scala
  test/junit/scala/sys/process/ParserTest.scala
Labels: library:base

#10108 [nomerge] Upgrade scala-compiler's dependency on scala-xml to 2.1.0 (was 1.0.6)
  src/intellij/scala.ipr.SAMPLE
  test/scalacheck/scala/tools/nsc/scaladoc/HtmlFactoryTest.scala
  test/scalacheck/scala/tools/nsc/scaladoc/SettingsUtil.scala
  versions.properties
Labels: release-notes

#10119 Merge 2.12 to 2.13 [ci: last-only]
  src/compiler/scala/tools/nsc/transform/async/ExprBuilder.scala
  src/compiler/scala/tools/nsc/transform/async/TransformUtils.scala
  src/scaladoc/scala/tools/nsc/doc/base/MemberLookupBase.scala
  test/junit/scala/tools/nsc/async/AnnotationDrivenAsyncTest.scala
  test/scaladoc/run/t12628.check
  test/scaladoc/run/t12628.scala
Labels: internal

#10122 fix Median-of-three pivot selection in quickSort method
  src/library/scala/util/Sorting.scala
Labels: library:collections

#10118 Prevent Function0 execution during LazyList deserialization
  src/library/scala/collection/immutable/LazyList.scala
  test/junit/scala/collection/immutable/LazyListTest.scala
Labels: release-notes, prio:blocker, library:collections

#10121 Update slf4j-nop to 2.0.0
  project/plugins.sbt
Labels: internal

#10123 Args files are 1 arg per line, fix -Vprint-args -
  src/compiler/scala/tools/nsc/CompilerCommand.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
Labels: prio:blocker
