Repository scala/scala, pull requests merged in 2022-02, with the labels that each got.

#9917 Update sbt to 1.6.2
  project/build.properties
  scripts/common
  src/intellij/scala.ipr.SAMPLE
  test/jcstress/project/build.properties
Labels: internal

#9918 Update sbt to 1.6.2 in 2.12.x
  project/build.properties
  scripts/common
Labels: internal

#9823 Simplify check of _root_ usage
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/StdAttachments.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/neg/t6217.scala
  test/files/neg/t6217b.scala
  test/files/neg/t6217c.scala
Labels: internal

#9919 Scala 3.1.2-RC1 (was 3.1.1-RC2)
  project/DottySupport.scala
  test/tasty/neg/src-2/TestErasedTypes.check
  test/tasty/neg/src-2/TestErasedTypes_fail.scala
  test/tasty/neg/src-3/ErasedTypes.scala
Labels: internal

#9926 Update sbt-header to 5.6.5 in 2.12.x
  project/plugins.sbt
Labels: internal

#9891 Prefer type of overridden member when inferring (under `-Xsource:3`)
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  test/files/pos/t7212.scala
  test/files/pos/t7212b/JavaClient.java
  test/files/pos/t7212b/JavaThing.java
  test/files/pos/t7212b/ScalaThing.scala
Labels: release-notes

#9929 Update slf4j-nop to 1.7.36 in 2.12.x
  project/plugins.sbt
Labels: internal

#9932 Merge 2.12.x to 2.13.x [ci: last-only]
  build.sbt
  project/plugins.sbt
  src/reflect/scala/reflect/internal/Definitions.scala
Labels: internal

#9916 [backport] make -target support JVM 8-18 with deprecated warning for 5-7
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/ant/Scalac.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/MutableSettings.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  test/files/neg/deprecated-target.check
  test/junit/scala/tools/nsc/settings/TargetTest.scala
Labels: release-notes

#9942 update doc of `Seq.combinations`.
  src/library/scala/collection/Seq.scala
  src/library/scala/collection/StringOps.scala
Labels: documentation

#9819 [bug#12464] Fix resizing for `ArrayBuffer` and `PriorityQueue`
  project/MimaFilters.scala
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/PriorityQueue.scala
  src/library/scala/runtime/PStatics.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
Labels: library:collections

#9824 For troubleshooting compiler, add `-Vdebug-type-error` (and remove `-Yissue-debug`)
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  test/files/run/debug-type-error.check
  test/files/run/debug-type-error.scala
Labels: release-notes

#9955 expand GitHub Actions matrix (add Ubuntu, more JDKs)
  .github/workflows/ci.yml
Labels: internal

#9953 Use fake dir entry in classpath for test
  test/files/pos/t9370/sample_2.scala
Labels: internal

#9945 doc: fix -release versions
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
Labels: documentation
