Repository scala/scala, pull requests merged in 2023-12, with the labels that each got.

#10619 CI config: bump setup-java to v4 (from v3)
  .github/workflows/ci.yml
Labels: internal

#10622 repo readme: be even louder about saying "Scala 2"
  README.md
Labels: documentation

#10605 Add or improve library doc [ci: last-only]
  build.sbt
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/Map.scala
  src/library/scala/collection/Seq.scala
  src/library/scala/collection/StringOps.scala
  src/library/scala/collection/immutable/Queue.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  src/library/scala/collection/mutable/Buffer.scala
  src/library/scala/collection/mutable/Growable.scala
  src/library/scala/collection/mutable/ListBuffer.scala
  src/library/scala/collection/mutable/LongMap.scala
  src/library/scala/collection/mutable/PriorityQueue.scala
  src/library/scala/collection/mutable/Stack.scala
  src/library/scala/collection/mutable/UnrolledBuffer.scala
  src/scaladoc/scala/tools/nsc/doc/Settings.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  test/files/filters
  test/scaladoc/filters
Labels: documentation

#10625 Ensure scripted tests have necessary boilerplate
  build.sbt
Labels: internal

#10628 Merge 2.12.x to 2.13.x [ci: last-only]
  .github/workflows/ci.yml
  project/build.properties
  project/plugins.sbt
Labels: internal

#10448 Prevent ArrayBuilder capacity overflow/infinite looping in ArrayBuilder.ensureSize(size:Int).
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  src/library/scala/collection/mutable/PriorityQueue.scala
  src/library/scala/runtime/PStatics.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
  test/junit/scala/collection/mutable/ArrayBuilderTest.scala
Labels: library:collections

#10637 pin bundler below 2.5
  .travis.yml
Labels: internal

#10601 Improve performance of Boolean extractors such as `NonFatal`
  src/compiler/scala/tools/nsc/transform/patmat/PatternMatching.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/run/nonfatal.scala
Labels: performance:do_not_allocate

#10615 Avoid completableFuture.asScala crash for MinimalStage
  src/library/scala/jdk/javaapi/FutureConverters.scala
  test/files/run/t12918.scala
Labels: library:concurrent

#10517 Always respect java.lang.Deprecated annotation
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/library/scala/deprecated.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  test/files/neg/deprecated.check
  test/files/neg/t12648.check
  test/files/neg/t12845.check
  test/files/neg/t12845.scala
  test/files/run/t9529.check
  test/files/run/t9644.check
  test/files/run/t9644b.check
  test/junit/scala/tools/nsc/reporters/WConfTest.scala
Labels: release-notes

#10642 Revert maladapted ArrayBuffer builder [ci: last-only]
  src/compiler/scala/tools/nsc/transform/patmat/Logic.scala
  src/library/scala/collection/ArrayOps.scala
  src/library/scala/collection/Factory.scala
  src/library/scala/collection/StrictOptimizedSeqOps.scala
  src/library/scala/collection/immutable/StrictOptimizedSeqOps.scala
  src/library/scala/collection/immutable/WrappedString.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArraySeq.scala
  src/library/scala/collection/mutable/Builder.scala
  src/library/scala/collection/mutable/CollisionProofHashMap.scala
  src/library/scala/collection/mutable/HashMap.scala
  src/library/scala/collection/mutable/HashSet.scala
  src/library/scala/collection/mutable/LinkedHashMap.scala
  src/library/scala/collection/mutable/LinkedHashSet.scala
  src/library/scala/runtime/Tuple2Zipped.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
Labels: prio:blocker, library:collections
