Repository scala/scala, pull requests merged in 2023-09, with the labels that each got.

#10524 Fix spurious "nullary overrides nilary" warning
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  test/files/pos/t12858/A.java
  test/files/pos/t12858/B.scala
Labels: prio:hi

#10530 New reference compiler is Scala 2.13.12
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#10531 Scala 3.3.1 (was 3.3.1-RC6)
  project/DottySupport.scala
Labels: internal

#10532 Corrected Docs of `Map.updatedWith`
  src/library/scala/collection/concurrent/Map.scala
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/mutable/Map.scala
Labels: library:collections, documentation

#10540 Update sbt-jmh to 0.4.6 in 2.12.x
  project/plugins.sbt
Labels: internal

#10508 Delete unused niche features of Reporter
  src/compiler/scala/tools/nsc/Reporting.scala
  test/files/run/t11731.scala
Labels: internal

#10545 Bump actions/checkout from 3 to 4
  .github/workflows/ci.yml
Labels: internal

#10548 Fix source links in our own Scaladoc (2.13.12 regression)
  build.sbt
Labels: prio:hi, documentation

#10550 JDK 21 (was 21-ea), sbt 1.9.6 (was .4)
  .github/workflows/ci.yml
  project/build.properties
Labels: internal

#10549 Align a return type in collections internals with Scala 3
  project/MimaFilters.scala
  src/library/scala/collection/immutable/HashMap.scala
Labels: internal

#10553 Merge 2.12 to 2.13 20230921 [ci: last-only]
  .github/workflows/ci.yml
  project/ScaladocSettings.scala
  project/build.properties
  project/plugins.sbt
  src/scaladoc/scala/tools/nsc/doc/html/HtmlFactory.scala
Labels: internal

#10518 Floor for NewVectorIterator.slice limit
  src/library/scala/collection/immutable/Vector.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: library:collections
