Repository scala/scala, pull requests merged in 2023-08, with the labels that each got.

#10490 Update commons-lang3 to 3.13.0 in 2.12.x
  project/plugins.sbt
Labels: internal

#10436 Make package object -Xsource:3 friendly
  src/library/scala/sys/process/package.scala
Labels: internal

#10495 Resolve TODO in mutable.PriorityQueue: explain why array(0) is not used.
  src/library/scala/collection/mutable/PriorityQueue.scala
Labels: library:collections

#10497 Boost spec of copy for abstract case class
  spec/05-classes-and-objects.md
Labels: documentation

#10472 In-source sbt compiler bridge [ci: last-only]
  build.sbt
  src/sbt-bridge/scala/tools/xsbt/API.scala
  src/sbt-bridge/scala/tools/xsbt/AbstractZincFile.scala
  src/sbt-bridge/scala/tools/xsbt/Analyzer.scala
  src/sbt-bridge/scala/tools/xsbt/CallbackGlobal.scala
  src/sbt-bridge/scala/tools/xsbt/ClassName.scala
  src/sbt-bridge/scala/tools/xsbt/Compat.scala
  src/sbt-bridge/scala/tools/xsbt/CompilerBridge.scala
  src/sbt-bridge/scala/tools/xsbt/ConsoleBridge.scala
  src/sbt-bridge/scala/tools/xsbt/DelegatingReporter.scala
  src/sbt-bridge/scala/tools/xsbt/Dependency.scala
  src/sbt-bridge/scala/tools/xsbt/ExtractAPI.scala
  src/sbt-bridge/scala/tools/xsbt/ExtractUsedNames.scala
  src/sbt-bridge/scala/tools/xsbt/GlobalHelpers.scala
  src/sbt-bridge/scala/tools/xsbt/InteractiveConsoleBridge.scala
  src/sbt-bridge/scala/tools/xsbt/InteractiveConsoleFactoryBridge.scala
  src/sbt-bridge/scala/tools/xsbt/InteractiveConsoleHelper.scala
  src/sbt-bridge/scala/tools/xsbt/InteractiveConsoleResponse.scala
  src/sbt-bridge/scala/tools/xsbt/JarUtils.scala
  src/sbt-bridge/scala/tools/xsbt/JavaUtils.scala
  src/sbt-bridge/scala/tools/xsbt/LocalToNonLocalClass.scala
  src/sbt-bridge/scala/tools/xsbt/LocateClassFile.scala
  src/sbt-bridge/scala/tools/xsbt/Log.scala
  src/sbt-bridge/scala/tools/xsbt/Message.scala
  src/sbt-bridge/scala/tools/xsbt/ScaladocBridge.scala
  src/sbt-bridge/scala/tools/xsbt/ZincCompat.scala
  test/junit/scala/tools/xsbt/BasicBridgeTest.scala
  test/junit/scala/tools/xsbt/BridgeTesting.scala
  test/junit/scala/tools/xsbt/ClassNameTest.scala
  test/junit/scala/tools/xsbt/CodeActionTest.scala
  test/junit/scala/tools/xsbt/DependencyTest.scala
  test/junit/scala/tools/xsbt/ExtractAPITest.scala
  test/junit/scala/tools/xsbt/ExtractUsedNamesTest.scala
  test/junit/scala/tools/xsbt/InteractiveConsoleInterfaceTest.scala
  test/junit/scala/tools/xsbt/SameAPI.scala
  test/junit/scala/tools/xsbt/TestCallback.scala
  test/junit/scala/tools/xsbt/package.scala
Labels: release-notes, prio:hi

#10337 Map.from and Set.from are more sound [ci: last-only]
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/Map.scala
  src/library/scala/collection/immutable/SeqMap.scala
  src/library/scala/collection/immutable/Set.scala
  src/testkit/scala/tools/testkit/ReflectUtil.scala
  test/junit/scala/collection/FactoriesTest.scala
  test/junit/scala/collection/immutable/MapTest.scala
  test/junit/scala/collection/immutable/SetTest.scala
Labels: library:collections

#10482 Add `-quickfix` compiler option to apply quick fixes to source files
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/reflect/scala/reflect/internal/util/CodeAction.scala
  test/files/neg/auto-application.check
  test/files/neg/for-comprehension-old.check
  test/files/neg/for-comprehension-val.check
  test/files/neg/macro-deprecate-idents.check
  test/files/neg/parens-for-params.check
  test/files/neg/prefix-unary-nilary-deprecation.check
  test/files/neg/prefix-unary-nilary-removal.check
  test/files/neg/procedure-deprecation.check
  test/files/neg/procedure-removal.check
  test/files/neg/t11921-alias.check
  test/files/neg/t11921.check
  test/files/neg/t11921b.check
  test/files/neg/t12798-migration.check
  test/files/neg/t12798.check
  test/files/neg/t12816.check
  test/files/neg/t12816b.check
  test/files/neg/t7187-deprecation.check
  test/files/neg/t7187.check
  test/files/neg/using-source3.check
  test/files/neg/using-source3b.check
  test/files/run/infixPostfixAttachments.check
  test/files/run/repl-errors.check
  test/junit/scala/tools/nsc/QuickfixTest.scala
Labels: release-notes, prio:hi

#10500 Fix spec build
  .travis.yml
Labels: internal

#10501 Merge 2.12.x to 2.13.x [ci: last-only]
  .travis.yml
Labels: internal

#10504 Tweak exception message in `LazyListLazinessTest`
  test/junit/scala/collection/immutable/LazyListLazinessTest.scala
Labels: internal

#10503 Obey messaging in sbt-bridge
  build.sbt
  src/reflect/scala/reflect/internal/Names.scala
  src/sbt-bridge/scala/tools/xsbt/API.scala
  src/sbt-bridge/scala/tools/xsbt/Analyzer.scala
  src/sbt-bridge/scala/tools/xsbt/CallbackGlobal.scala
  src/sbt-bridge/scala/tools/xsbt/ClassName.scala
  src/sbt-bridge/scala/tools/xsbt/CompilerBridge.scala
  src/sbt-bridge/scala/tools/xsbt/ConsoleBridge.scala
  src/sbt-bridge/scala/tools/xsbt/DelegatingReporter.scala
  src/sbt-bridge/scala/tools/xsbt/Dependency.scala
  src/sbt-bridge/scala/tools/xsbt/ExtractUsedNames.scala
  src/sbt-bridge/scala/tools/xsbt/GlobalHelpers.scala
  src/sbt-bridge/scala/tools/xsbt/InteractiveConsoleBridge.scala
  src/sbt-bridge/scala/tools/xsbt/InteractiveConsoleHelper.scala
  src/sbt-bridge/scala/tools/xsbt/ScaladocBridge.scala
Labels: internal

#10514 Update scala3-compiler_3, ... to 3.3.1-RC6
  project/DottySupport.scala
Labels: internal

#10509 Don't crash issuing spurious nilary-overrides-nullary warning
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  test/files/pos/t12851/C_2.scala
  test/files/pos/t12851/T_1.scala
Labels: prio:blocker

#10516 Update sbt to 1.9.4 in 2.12.x
  project/build.properties
Labels: internal

#10521 Message comparison in FilteringReporter strips trailing [quickfixable]
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/reporters/PrintReporter.scala
  src/compiler/scala/tools/nsc/reporters/Reporter.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/Reporter.scala
  test/junit/scala/tools/nsc/reporters/PositionFilterTest.scala
Labels: prio:hi

#10520 Fix missing and excess nullary / nilary override warnings
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  test/files/neg/nullary-override-3a.check
  test/files/neg/nullary-override-3b.check
  test/files/neg/nullary-override.check
  test/files/neg/t12815.check
  test/files/neg/t12851b.check
  test/files/neg/t12851b/C_2.scala
  test/files/neg/t12851b/T_1.scala
  test/files/neg/t5429.check
  test/files/pos/t12851c/ScalaNumber.java
  test/files/pos/t12851c/ScalaNumericConversions.scala
Labels: prio:hi

#10510 Follow-up for non-warning nilary/nullary override with BeanProperty
  src/library/scala/beans/BeanProperty.scala
  src/library/scala/beans/BooleanBeanProperty.scala
  src/reflect/scala/reflect/internal/AnnotationInfos.scala
  test/files/run/reify_ann5.check
Labels: prio:hi
