Repository scala/scala, pull requests merged in 2023-01, with the labels that each got.

#10252 Update scala3-compiler_3, ... to 3.2.1
  project/DottySupport.scala
  test/tasty/neg-full-circle/src-3-app/TestExperimentalDefsPre.check
Labels: internal

#10264 Update scala3-compiler_3, ... to 3.2.2
  project/DottySupport.scala
Labels: internal

#10256 Update sbt to 1.8.2 in 2.12.x
  project/build.properties
Labels: internal

#10267 Clean up tempdir in test
  test/files/run/t11385.scala
Labels: internal

#10271 Forward port minor ListSetTest tweak
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/junit/scala/collection/immutable/ListSetTest.scala
  test/junit/scala/tools/nsc/backend/jvm/PerRunInitTest.scala
  test/junit/scala/tools/testkit/AssertUtilTest.scala
Labels: internal

#10275 Update jackson-module-scala to 2.13.5 in 2.12.x
  build.sbt
Labels: internal

#10274 Build cleanup: take advantage of SAM conversion
  project/VersionUtil.scala
Labels: internal

#10278 Small code improvement in build definition
  project/DottySupport.scala
Labels: internal

#10279 Partest --branch checks file status
  src/partest/scala/tools/partest/nest/AbstractRunner.scala
Labels: internal

#10283 [backport] flag eta-expanding methods without parameter lists under source:2.13
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: release-notes

#10285 test tasty reader against Scala 3.3.0-RC2
  project/DottySupport.scala
  src/compiler/scala/tools/tasty/TastyFormat.scala
  src/compiler/scala/tools/tasty/TastyHeaderUnpickler.scala
  test/tasty/neg-full-circle/src-3-app/TestExperimentalDefsPre.check
Labels: internal

#10284 Fix typo, traitss -> traits
  src/library/scala/AnyVal.scala
Labels: documentation

#10281 Avoid deprecation in run/analyzerPlugins
  test/files/run/analyzerPlugins.check
  test/files/run/analyzerPlugins.scala
Labels: internal

#10276 Fix test that compared ints and strings
  test/files/jvm/t7253.check
  test/files/jvm/t7253/test.scala
Labels: internal

#10198 Use narrowest type for pt of override if Xsrc:3
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  test/files/pos/t12671.scala
Labels: release-notes, prio:hi

#10280 Small code improvement in build definition
  project/DottySupport.scala
  project/GenerateFunctionConverters.scala
  project/JitWatch.scala
  project/Osgi.scala
  project/ParserUtil.scala
  project/PartestTestListener.scala
  project/PartestUtil.scala
  project/SavedLogs.scala
  project/VersionUtil.scala
  project/genprod.scala
Labels: internal

#10272 Report total errors on stderr
  src/compiler/scala/tools/nsc/reporters/ConsoleReporter.scala
Labels: release-notes
