Repository scala/scala, pull requests merged in 2023-10, with the labels that each got.

#10556 Fix incorrectly final flag for mixed-in field
  src/compiler/scala/tools/nsc/transform/Fields.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: prio:hi

#10569 Update jackson-module-scala to 2.15.3 in 2.12.x
  build.sbt
Labels: internal

#10574 in CI, upgrade JDK 21 from EA to GA
  .github/workflows/ci.yml
Labels: internal

#10578 Merge 2.12.x to 2.13.x [ci: last-only]
  .github/workflows/ci.yml
Labels: internal

#10576 Upgrade to asm 9.6, for JDK22 support
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: release-notes

#10575 [nomerge] Upgrade to asm 9.6, for JDK22 support
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  test/junit/scala/tools/nsc/settings/TargetTest.scala
  versions.properties
Labels: release-notes

#10583 Code jar is unused
  src/partest/scala/tools/partest/nest/DirectCompiler.scala
  src/partest/scala/tools/partest/nest/PathSettings.scala
Labels: internal

#10586 Highlight Either#toOption for filtering
  src/library/scala/util/Either.scala
Labels: documentation
