Repository scala/scala, pull requests merged in 2023-05, with the labels that each got.

#10348 Support Java 17 `sealed` in Java sources
  src/compiler/scala/tools/nsc/javac/JavaParsers.scala
  src/compiler/scala/tools/nsc/transform/patmat/PatternMatching.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/neg/t12159d.check
  test/files/neg/t12159d/X.java
  test/files/neg/t12159d/t.scala
  test/files/neg/t12159e.check
  test/files/neg/t12159e/X.java
  test/files/neg/t12159e/t.scala
  test/files/neg/t12159f.check
  test/files/neg/t12159f/X.java
  test/files/neg/t12159f/Z.java
  test/files/neg/t12159f/t.scala
  test/files/neg/t12159g.check
  test/files/neg/t12159g/X.java
  test/files/neg/t12159g/t.scala
Labels: prio:hi

#10397 ClassfileParser: allow missing param names (for JDK 21)
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
Labels: release-notes, prio:hi

#10398 Lambdaless test is more forgiving
  src/partest/scala/tools/partest/ReplTest.scala
Labels: internal

#10400 add JDK 21 Early Access to nightly CI
  .github/workflows/ci.yml
  .travis.yml
  project/build.properties
  scripts/common
  test/files/neg/macro-exception.check
  test/files/neg/macro-invalidret.check
  test/files/run/sammy_after_implicit_view.scala
  test/files/run/sammy_restrictions_LMF.scala
  versions.properties
Labels: internal

#10339 Under `-Xsource:3`, include top-level symbols from same file in outer ambiguity warning
  spec/02-identifiers-names-and-scopes.md
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  test/files/jvm/protectedacc.scala
  test/files/neg/t11921-alias.scala
  test/files/neg/t11921.scala
  test/files/neg/t11921b.check
  test/files/neg/t11921b.scala
  test/files/neg/t11921c.scala
  test/files/pos/t11921b.scala
  test/files/pos/t11921c.scala
Labels: release-notes, prio:hi

#10403 More JDK 21 fixes
  test/junit/scala/jdk/javaapi/StreamConvertersJavaTest.java
  test/tasty/test/scala/tools/tastytest/TastyTestJUnit.scala
Labels: internal

#10148 bugfix: Matcher should be able to match on name exactly
  src/interactive/scala/tools/nsc/interactive/Global.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
Labels: prio:hi

#10408 docs: add in a note about elidable not being supported in Scala 3
  src/library/scala/annotation/elidable.scala
Labels: documentation

#10409 Scala 3.3.1-RC1 (enable TastyTest on JDK 21)
  project/DottySupport.scala
  test/tasty/neg/src-2/TestErasedTypes.check
  test/tasty/neg/src-2/TestSaferExceptions.check
  test/tasty/test/scala/tools/tastytest/TastyTestJUnit.scala
Labels: internal

#10417 revert pull request #10148 in its entirety
  src/interactive/scala/tools/nsc/interactive/Global.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl/scala/tools/nsc/interpreter/Interface.scala
  src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala
Labels: prio:blocker, internal
