Repository scala/scala, pull requests merged in 2023-11, with the labels that each got.

#10588 REPL: upgrade JLine to 3.24.1 (was .22)
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: release-notes, prio:hi, tool:REPL, dependencies

#10568 Clarify implicit params
  spec/07-implicits.md
Labels: documentation

#10589 Include implicit Manager example in Using doc
  src/library/scala/util/Using.scala
Labels: documentation

#10591 Type tweaks in Using
  src/library/scala/util/Using.scala
Labels: library:base

#10593 BigInt conversion checks for null
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/math/BigInt.scala
  src/library/scala/util/ChainingOps.scala
  test/junit/scala/math/BigIntTest.scala
Labels: library:base

#10590 Improve name of default value
  src/library/scala/collection/concurrent/Map.scala
  src/library/scala/collection/concurrent/TrieMap.scala
  src/library/scala/collection/mutable/Map.scala
Labels: library:collections

#10594 Fix enabling IncOptions.useOptimizedSealed causing under-compilation in Scala 2.13
  src/sbt-bridge/scala/tools/xsbt/ExtractUsedNames.scala
  test/junit/scala/tools/xsbt/ExtractUsedNamesTest.scala
Labels: welcome

#10596 Update sbt to 1.9.7 in 2.12.x
  project/build.properties
Labels: internal

#10566 Specification for tail-call elimination and `@tailrec`
  spec/04-basic-declarations-and-definitions.md
  spec/11-annotations.md
Labels: documentation

#10597 Comment on comment in identifier
  spec/01-lexical-syntax.md
Labels: documentation

#10562 Don't warn about synthetic apply if user-added
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/nsc/typechecker/Unapplies.scala
  test/files/neg/t12798-migration.check
  test/files/neg/t12798.check
  test/files/neg/t12883.check
  test/files/neg/t12883.scala
  test/files/pos/t12883.scala
Labels: prio:hi

#10542 Forward-port from in compiler bridge: fix fullName for nested classes
  src/sbt-bridge/scala/tools/xsbt/API.scala
  src/sbt-bridge/scala/tools/xsbt/CallbackGlobal.scala
  src/sbt-bridge/scala/tools/xsbt/ReflectAccess.java
  test/sbt-test/source-dependencies/compactify-nested/test
Labels: prio:hi

#10528 Fixes issue with blocking and BatchingExecutor
  src/library/scala/concurrent/BatchingExecutor.scala
  test/junit/scala/concurrent/FutureTest.scala
Labels: library:concurrent

#10581 `-doc-source-url` compatibility with 2.12.11
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
  test/junit/scala/tools/nsc/doc/html/ModelFactoryTest.scala
  test/scaladoc/run/doc-source-url-java.scala
  test/scaladoc/run/doc-source-url.scala
Labels: release-notes, prio:hi

#10525 fix: SliceIterator to drop a max of Int.MaxValue
  src/library/scala/collection/Iterator.scala
  test/junit/scala/collection/IteratorTest.scala
Labels: library:collections

#10527 Improve readability of Stepper test [ci: last-only]
  src/library/scala/collection/immutable/IntMap.scala
  src/library/scala/collection/immutable/LongMap.scala
  src/library/scala/collection/immutable/TreeSeqMap.scala
  test/junit/scala/jdk/StepperTest.scala
Labels: library:collections, internal

#10558 Flaky IteratorTest bails not fails
  src/library/scala/collection/Iterator.scala
  src/testkit/scala/tools/testkit/AssertUtil.scala
  test/junit/scala/collection/IteratorTest.scala
Labels: library:collections, internal

#10602 Uniform -opt in tests
  test/files/instrumented/InstrumentationTest.scala
  test/files/jvm/bytecode-test-example/Foo_1.scala
  test/files/jvm/bytecode-test-example/Test.scala
  test/files/jvm/matchbox/Test.scala
  test/files/jvm/matchbox/matchbox_1.scala
  test/files/jvm/unreachable/Foo_1.scala
  test/files/neg/deprecated.scala
  test/files/run/anyval-box-types.scala
  test/files/run/nothingTypeNoOpt.scala
  test/files/run/t7407.scala
  test/files/run/t7852.scala
  test/files/run/t8925.scala
  test/files/specialized/spec-patmatch.scala
Labels: internal
