Repository scala/scala, pull requests merged in 2023-03, with the labels that each got.

#10321 [nomerge] Deal with overloads in new ambiguity warning
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  test/files/neg/t11921-alias.check
  test/files/neg/t11921b.check
  test/files/neg/t11921b.scala
  test/files/pos/t11921-depth.scala
  test/files/pos/t11921b.scala
Labels: prio:hi

#10324 Deal with overloads in new ambiguity warning (2.13)
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  test/files/neg/t11921-alias.check
  test/files/neg/t11921.check
  test/files/neg/t11921b.check
  test/files/neg/t11921b.scala
  test/files/pos/t11921b.scala
Labels: prio:hi

#10313 Lint for integral divisions that are widened to a float
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/library/scala/math/BigInt.scala
  src/library/scala/runtime/RichInt.scala
  src/library/scala/runtime/ScalaNumberProxy.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/TreeInfo.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/neg/lint-int-div-to-float.check
  test/files/neg/lint-int-div-to-float.scala
  test/files/run/is-valid-num.scala
Labels: release-notes

#10306 [nomerge] Re-STARR onto 2.12.18-M1 and add JDK 20 (early access) to daily CI matrix
  .github/workflows/ci.yml
  build.sbt
  test/files/jvm/future-spec.check
  test/files/jvm/future-spec/FutureTests.scala
  test/files/jvm/future-spec/PromiseTests.scala
  test/files/jvm/future-spec/TryTests.scala
  test/files/jvm/future-spec/main.scala
  test/files/jvm/scala-concurrent-tck.check
  test/files/jvm/scala-concurrent-tck.scala
  test/files/jvm/unreachable/Foo_1.check
  test/files/neg/macro-exception.check
  test/files/neg/macro-invalidret.check
  test/files/run/reflection-magicsymbols-invoke.check
  test/files/run/t2318.scala
  test/files/run/t6989.check
  test/files/run/t9529.check
  test/files/run/t9529/Test_1.scala
  test/junit/scala/runtime/FloatBoxingTest.scala
  test/junit/scala/tools/nsc/classpath/MultiReleaseJarTest.scala
  test/junit/scala/tools/testing/AllocationTest.scala
  test/scaladoc/run/doc-source-url-java.scala
  test/scaladoc/run/doc-source-url.scala
  versions.properties
Labels: prio:blocker, internal

#10335 Re-STARR onto 2.13.11-M1 and add JDK 20 (early access) to daily CI matrix
  .github/workflows/ci.yml
  build.sbt
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/compiler/scala/tools/nsc/classpath/VirtualDirectoryClassPath.scala
  src/compiler/scala/tools/nsc/util/ClassPath.scala
  src/library/scala/io/Source.scala
  src/library/scala/util/Using.scala
  src/library/scala/util/control/NonFatal.scala
  src/reflect/scala/reflect/internal/util/AbstractFileClassLoader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl/scala/tools/nsc/interpreter/Power.scala
  src/scaladoc/scala/tools/nsc/doc/model/ModelFactory.scala
  test/files/jvm/scala-concurrent-tck.scala
  test/files/run/reflection-magicsymbols-invoke.check
  test/files/run/t6989.check
  test/files/run/t9529.check
  test/junit/scala/runtime/FloatBoxingTest.scala
  test/junit/scala/tools/nsc/classpath/MultiReleaseJarTest.scala
  test/junit/scala/util/TryTest.scala
  test/junit/scala/util/UsingTest.scala
  test/scaladoc/run/doc-source-url-java.scala
  test/scaladoc/run/doc-source-url.scala
  versions.properties
Labels: prio:blocker, internal

#10338 [nomerge] fix (?) REPL test that intermittently fails on Windows
  .gitignore
  test/files/run/repl-paste-parse.check
  test/files/run/repl-paste-parse.scala
Labels: internal

#10341 Update sbt-buildinfo to 0.11.0 in 2.12.x
  project/project/plugins.sbt
Labels: internal

#10342 Add an icon for IDEA to display
  .idea/icon.png
Labels: internal

#10296 Replace removeFirst with removeHead in ArrayDeque documentation
  src/library/scala/collection/mutable/ArrayDeque.scala
Labels: library:collections, documentation

#10322 Removed random values in NumericRange unit tests
  test/junit/scala/collection/immutable/NumericRangeTest.scala
Labels: prio:hi, library:collections, internal

#9944 Improvements to `-Vimplicits`; errors now show complete implicit search tree
  src/compiler/scala/tools/nsc/typechecker/splain/SplainData.scala
  src/compiler/scala/tools/nsc/typechecker/splain/SplainFormatting.scala
  test/files/run/splain-tree.check
  test/files/run/splain-tree.scala
  test/files/run/splain.check
Labels: prio:hi

#10287 Partest toolargs caching [ci: last-only]
  src/partest/scala/tools/partest/nest/Runner.scala
Labels: internal

#10343 fix semantic merge conflict in partest tool
  src/partest/scala/tools/partest/nest/Runner.scala
Labels: internal

#10336 javabootclasspath supersedes jrt
  src/compiler/scala/tools/util/PathResolver.scala
Labels: release-notes

#10331 Improve check for empty vector slice
  src/library/scala/collection/immutable/Vector.scala
  test/junit/scala/collection/immutable/VectorTest.scala
Labels: library:collections

#10302 Avoid exception in post-typer checks
  src/compiler/scala/tools/nsc/CompilationUnits.scala
  src/compiler/scala/tools/nsc/typechecker/Analyzer.scala
Labels: prio:hi

#10347 Check feature setting eagerly
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
Labels: internal

#10327 Accept `implicit _`, `implicit (x: Int)` in lambdas, like Scala 3 does
  spec/06-expressions.md
  spec/13-syntax-summary.md
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  test/files/pos/t3672.scala
Labels: release-notes

#10349 Regression test cyclic reference
  test/files/pos/t10639/Identifiable_1.java
  test/files/pos/t10639/Size_1.java
  test/files/pos/t10639/broken_2.scala
Labels: internal

#10355 Fix tasty/TestLogarithms.scala failed in some platform
  test/tasty/run/src-2/tastytest/TestLogarithms.scala
  test/tasty/run/src-3/tastytest/Logarithms.scala
Labels: internal

#10350 Runner scripts -usebootcp and require javaBootClassPath
  src/compiler/scala/tools/util/PathResolver.scala
Labels: prio:hi

#10319 Make scalac's argument-file processing more like javac's in handling spaces and line breaks
  src/compiler/scala/tools/nsc/CompilerCommand.scala
  src/compiler/scala/tools/nsc/Global.scala
  test/files/run/argfile.scala
Labels: release-notes, prio:hi

#10356 Respect user target always
  src/compiler/scala/tools/nsc/backend/jvm/PostProcessorFrontendAccess.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  test/junit/scala/tools/nsc/settings/TargetTest.scala
Labels: prio:hi

#10360 silence warning on JDK 20
  test/junit/scala/util/UsingTest.scala
Labels: internal

#10359 Use BTypes in StringConcatFactory code gen
  src/compiler/scala/tools/nsc/backend/jvm/BCodeIdiomatic.scala
  src/compiler/scala/tools/nsc/backend/jvm/CoreBTypes.scala
Labels: prio:hi
