Repository scala/scala, pull requests merged in 2023-04, with the labels that each got.

#10362 [nomerge] Upgrade to asm 9.5, for JDK21 support
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  test/junit/scala/tools/nsc/settings/TargetTest.scala
  versions.properties
Labels: release-notes, prio:blocker, java interop

#10363 Upgrade to asm 9.5, for JDK21 support
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: release-notes, prio:blocker, java interop

#10366 GitHub Actions config: JDK 20 is GA
  .github/workflows/ci.yml
Labels: internal

#10369 Lint for integral divisions that are widened to a float [forward port from 2.12]
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/library/scala/math/BigInt.scala
  src/library/scala/runtime/RichInt.scala
  src/library/scala/runtime/ScalaNumberProxy.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/neg/lint-int-div-to-float.check
  test/files/neg/lint-int-div-to-float.scala
  test/files/run/is-valid-num.scala
  test/scalacheck/scala/math/BigIntProperties.scala
Labels: prio:hi

#10371 Update sbt-mima-plugin to 1.1.2 in 2.12.x
  project/plugins.sbt
Labels: internal

#10373 Update LinkedHash{Map,Set} from factory method
  src/library/scala/collection/mutable/LinkedHashMap.scala
  src/library/scala/collection/mutable/LinkedHashSet.scala
  test/junit/scala/collection/mutable/LinkedHashMapTest.scala
  test/junit/scala/collection/mutable/LinkedHashSetTest.scala
Labels: library:collections

#10105 Support JDK 17 `PermittedSubclasses` in classfiles
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/ast/parser/CommonTokens.scala
  src/compiler/scala/tools/nsc/ast/parser/Tokens.scala
  src/compiler/scala/tools/nsc/javac/JavaParsers.scala
  src/compiler/scala/tools/nsc/javac/JavaTokens.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/partest/scala/tools/partest/nest/AbstractRunner.scala
  src/reflect/scala/reflect/internal/StdAttachments.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/reflect/scala/reflect/internal/Trees.scala
  src/reflect/scala/reflect/internal/Types.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/neg/t12159.check
  test/files/neg/t12159/H.java
  test/files/neg/t12159/I.java
  test/files/neg/t12159/J.java
  test/files/neg/t12159/M.java
  test/files/neg/t12159/s.scala
  test/files/neg/t12159b.check
  test/files/neg/t12159b/I.java
  test/files/neg/t12159b/J.java
  test/files/neg/t12159b/s_2.scala
  test/files/neg/t12159c.check
  test/files/neg/t12159c/H.java
  test/files/neg/t12159c/s_2.scala
  test/files/pos/t12159/H.java
  test/files/pos/t12159/I.java
  test/files/pos/t12159/J.java
  test/files/pos/t12159/M.java
  test/files/pos/t12159/s.scala
  test/files/pos/t12159b/H_1.java
  test/files/pos/t12159b/s_2.scala
  test/files/pos/t12474/Nat.java
  test/files/pos/t12474/s.scala
Labels: release-notes, prio:hi

#10380 Scala 3.3.0-RC4 (was -RC3)
  project/DottySupport.scala
Labels: internal

#10383 adjust tests on JDK 17+ for `PermittedSubclasses` change
  test/files/neg/t8700b-new.check
  test/files/neg/t8700b-new/Bar_2.scala
  test/files/neg/t8700b-new/Baz_1.java
  test/files/neg/t8700b-new/Foo_1.java
  test/files/neg/t8700b-old.check
  test/files/neg/t8700b-old/Bar_2.scala
  test/files/neg/t8700b-old/Baz_1.java
  test/files/neg/t8700b-old/Foo_1.java
Labels: internal

#10382 Add caveat for global context to Future
  src/library/scala/concurrent/Future.scala
Labels: documentation

#10381 Update jackson-module-scala to 2.15.0 in 2.12.x
  build.sbt
Labels: internal

#10384 Update scala3-compiler_3, ... to 3.3.0-RC5
  project/DottySupport.scala
Labels: internal
