Repository scala/scala, pull requests merged in 2023-02, with the labels that each got.

#10301 Update sbt-jmh to 0.4.4 in 2.12.x
  project/plugins.sbt
Labels: internal

#10300 Update jackson-module-scala to 2.14.2 in 2.12.x
  build.sbt
Labels: internal

#10304 GitHub Actions: update actions/checkout to v3
  .github/workflows/ci.yml
Labels: internal

#10293 Tweak class doc for StringBuilder
  src/library/scala/Array.scala
  src/library/scala/collection/concurrent/Map.scala
  src/library/scala/collection/immutable/BitSet.scala
  src/library/scala/collection/immutable/LazyList.scala
  src/library/scala/collection/immutable/List.scala
  src/library/scala/collection/immutable/ListMap.scala
  src/library/scala/collection/immutable/Queue.scala
  src/library/scala/collection/immutable/TreeMap.scala
  src/library/scala/collection/immutable/TreeSet.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/BitSet.scala
  src/library/scala/collection/mutable/CollisionProofHashMap.scala
  src/library/scala/collection/mutable/HashMap.scala
  src/library/scala/collection/mutable/HashSet.scala
  src/library/scala/collection/mutable/ListBuffer.scala
  src/library/scala/collection/mutable/StringBuilder.scala
  src/library/scala/collection/mutable/WeakHashMap.scala
Labels: documentation

#10303 small code improvement
  project/DottySupport.scala
Labels: internal

#10307 add `dependabot.yml` for GitHub Actions update
  .github/dependabot.yml
Labels: internal

#10299 Tasty Reader: test APPLYsigpoly, fail in forced annotations
  src/compiler/scala/tools/nsc/tasty/TreeUnpickler.scala
  src/compiler/scala/tools/tasty/TastyFormat.scala
  test/tasty/neg/src-2/TestApplySigPoly.check
  test/tasty/neg/src-2/TestApplySigPoly_fail.scala
  test/tasty/neg/src-2/TestApplySigPoly_pre.scala
  test/tasty/neg/src-3/ApplySigPoly.scala
  test/tasty/run/src-2/tastytest/TestApplySigPoly.scala
  test/tasty/run/src-3/tastytest/ApplySigPoly.scala
Labels: release-notes, tastyreader

#10310 spec: update Jekyll and Redcarpet versions
  .travis.yml
  Gemfile
Labels: internal

#10292 Improve doc of `Seq#sortWith`
  src/library/scala/collection/Seq.scala
Labels: documentation

#10259 Fix `take` and `drop` on very large `NumericRange`s
  src/library/scala/collection/immutable/NumericRange.scala
  test/junit/scala/collection/immutable/NumericRangeTest.scala
  test/scalacheck/scala/collection/immutable/NumericRangeProperties.scala
Labels: library:collections

#10317 Update scala3-compiler_3, ... to 3.3.0-RC3
  project/DottySupport.scala
Labels: internal

#10291 Honor more deprecations under separate compilation
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/compiler/scala/tools/nsc/typechecker/Duplicators.scala
  src/library/scala/collection/mutable/ArrayDeque.scala
  src/library/scala/collection/mutable/Queue.scala
  src/library/scala/collection/mutable/Stack.scala
  src/library/scala/collection/mutable/UnrolledBuffer.scala
  src/partest/scala/tools/partest/nest/DirectCompiler.scala
  src/partest/scala/tools/partest/nest/Runner.scala
  src/partest/scala/tools/partest/package.scala
  test/files/jvm/deprecation.check
  test/files/jvm/deprecation/Test_1.scala
  test/files/jvm/deprecation/Use_2.java
  test/files/neg/t10752.check
  test/files/neg/t10752/Test_2.scala
  test/files/neg/t9617.check
  test/files/neg/t9617/Test.scala
Labels: prio:hi

#10330 fix `test/files/jvm/natives.scala` on ARM Macs
  test/files/jvm/.gitignore
  test/files/jvm/libnatives-arm.jnilib
  test/files/jvm/libnatives-x86.jnilib
  test/files/jvm/mkLibNatives.sh
  test/files/jvm/natives.scala
Labels: internal
