Repository scala/scala, pull requests merged in 2023-06, with the labels that each got.

#10420 new reference compiler is 2.13.11
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#10412 Update jackson-module-scala to 2.15.1 in 2.12.x
  build.sbt
Labels: internal

#10368 Partest fails if nothing to compile
  src/partest/scala/tools/partest/nest/Runner.scala
Labels: internal

#10413 Print verbose symbol output with syntax trees
  src/compiler/scala/tools/nsc/Global.scala
Labels: internal

#10387 [backport] sbt 1.9.0 (was 1.8.3)
  project/build.properties
  project/plugins.sbt
Labels: internal

#10433 Update sbt-jmh to 0.4.5 in 2.12.x
  project/plugins.sbt
Labels: internal

#10431 Update sbt-header to 5.10.0 in 2.12.x
  project/plugins.sbt
Labels: internal

#10434 [ci: last-only] Merge 2.12 to 2.13 (20230612)
  project/plugins.sbt
Labels: internal

#10424 Avoid brittle flags encoding for Java enums
  src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala
  src/compiler/scala/tools/nsc/javac/JavaParsers.scala
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/compiler/scala/tools/nsc/transform/patmat/MatchAnalysis.scala
  src/reflect/scala/reflect/internal/ClassfileConstants.scala
  test/files/neg/sealed-java-enums.scala
  test/files/neg/t12800.check
  test/files/neg/t12800/JetBrains.java
  test/files/neg/t12800/matcher_1.scala
  test/files/neg/t8700b-new/Bar_2.scala
  test/files/neg/t8700b-new/Baz_1.java
  test/files/neg/t8700b-new/Foo_1.java
  test/files/neg/t8700b-old.check
  test/files/neg/t8700b-old/Bar_2.scala
  test/files/neg/t8700b-old/Foo_1.java
  test/files/neg/t8700b.check
  test/files/neg/t8700b/Bar_2.scala
  test/files/neg/t8700b/Baz.java
  test/files/neg/t8700b/Foo.java
  test/files/pos/t12800/JetBrains.java
  test/files/pos/t12800/matcher_1.scala
Labels: prio:blocker

#10435 Add explicit result type to some non-private methods
  src/library/scala/collection/View.scala
  src/library/scala/collection/convert/JavaCollectionWrappers.scala
  src/library/scala/collection/immutable/TreeSet.scala
  src/library/scala/collection/mutable/LinkedHashMap.scala
  src/library/scala/collection/mutable/LinkedHashSet.scala
  src/library/scala/collection/mutable/TreeMap.scala
  src/library/scala/concurrent/duration/Duration.scala
  src/library/scala/math/BigDecimal.scala
  src/library/scala/math/Ordering.scala
  src/library/scala/sys/process/ProcessBuilderImpl.scala
Labels: library:base, Scala 3 related

#10416 Fix ListBuffer.insertAfter, used in patchInPlace
  src/library/scala/collection/mutable/ListBuffer.scala
  test/junit/scala/collection/mutable/ListBufferTest.scala
Labels: library:collections

#10451 Update sbt to 1.9.1 in 2.12.x
  project/build.properties
Labels: internal
