Repository scala/scala, pull requests merged in 2023-07, with the labels that each got.

#10452 Revert aggressive optimization of String lobounds
  src/reflect/scala/reflect/internal/tpe/TypeConstraints.scala
Labels: prio:hi

#10439 Emit migration warnings under `-Xsource:3` as fatal warnigns, not errors
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/Unapplies.scala
  src/compiler/scala/tools/reflect/FastStringInterpolator.scala
  src/partest/scala/tools/partest/nest/Runner.scala
  test/files/neg/caseclass_private_constructor.scala
  test/files/neg/deprecate_package_object_extends.check
  test/files/neg/deprecate_package_object_extends.scala
  test/files/neg/dotless-targs-a.check
  test/files/neg/dotless-targs-a.scala
  test/files/neg/dotless-targs-ranged-a.check
  test/files/neg/dotless-targs-ranged-a.scala
  test/files/neg/early-type-defs.check
  test/files/neg/early-type-defs.scala
  test/files/neg/for-comprehension-val.check
  test/files/neg/for-comprehension-val.scala
  test/files/neg/nested-class-shadowing-removal.check
  test/files/neg/nested-class-shadowing-removal.scala
  test/files/neg/parens-for-params.check
  test/files/neg/parens-for-params.scala
  test/files/neg/prefix-unary-nilary-removal.check
  test/files/neg/prefix-unary-nilary-removal.scala
  test/files/neg/procedure-removal.check
  test/files/neg/procedure-removal.scala
  test/files/neg/t12798-migration.check
  test/files/neg/t12798-migration.scala
  test/files/neg/t12798.check
  test/files/neg/t12798.scala
  test/files/neg/t12798b.check
  test/files/neg/t12798b.scala
  test/files/neg/t5265b.check
  test/files/neg/t5265b.scala
  test/files/neg/t5606.check
  test/files/neg/t5606b.check
  test/files/neg/t7212.check
  test/files/neg/t7212.scala
  test/files/pos/caseclass_private_constructor.scala
  test/files/pos/t11980.scala
  test/files/pos/t7212.scala
  test/files/pos/t7212b/ScalaThing.scala
  test/files/run/t10751.check
  test/files/run/t1980.check
  test/files/run/t3220-213.check
  test/files/run/t3220-214.check
  test/files/run/t3220-214.scala
Labels: release-notes, prio:hi

#10444 Add explicit result type to some non-private methods
  src/library/scala/PartialFunction.scala
  src/library/scala/collection/Iterable.scala
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/Iterator.scala
  src/library/scala/collection/LazyZipOps.scala
  src/library/scala/collection/concurrent/TrieMap.scala
  src/library/scala/collection/convert/JavaCollectionWrappers.scala
  src/library/scala/collection/immutable/ArraySeq.scala
  src/library/scala/collection/immutable/BitSet.scala
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/immutable/HashSet.scala
  src/library/scala/collection/immutable/RedBlackTree.scala
  src/library/scala/collection/mutable/AnyRefMap.scala
  src/library/scala/collection/mutable/ArraySeq.scala
  src/library/scala/collection/mutable/BitSet.scala
  src/library/scala/collection/mutable/LongMap.scala
  src/library/scala/collection/mutable/UnrolledBuffer.scala
  src/library/scala/reflect/Manifest.scala
  src/library/scala/runtime/RichBoolean.scala
  src/library/scala/runtime/RichByte.scala
  src/library/scala/runtime/RichChar.scala
  src/library/scala/runtime/RichInt.scala
  src/library/scala/runtime/RichLong.scala
  src/library/scala/runtime/RichShort.scala
  src/library/scala/typeConstraints.scala
  src/library/scala/util/DynamicVariable.scala
  src/library/scala/util/Properties.scala
Labels: library:base, internal, Scala 3 related

#10429 IteratorTest mustn't use spent iterator after terminal op
  src/library/scala/collection/immutable/Range.scala
  test/junit/scala/collection/IteratorTest.scala
  test/junit/scala/collection/immutable/RangeTest.scala
Labels: library:collections, internal

#10438 Tweak spec for subrange unary_-
  spec/12-the-scala-standard-library.md
Labels: documentation

#10406 Implement CodeAction (actionable diagnostic)
  project/MimaFilters.scala
  src/compiler/scala/reflect/macros/contexts/Parsers.scala
  src/compiler/scala/tools/nsc/CompilationUnits.scala
  src/compiler/scala/tools/nsc/Parsing.scala
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  src/compiler/scala/tools/nsc/javac/JavaParsers.scala
  src/compiler/scala/tools/nsc/javac/JavaScanners.scala
  src/compiler/scala/tools/nsc/reporters/ConsoleReporter.scala
  src/compiler/scala/tools/nsc/reporters/ForwardingReporter.scala
  src/compiler/scala/tools/nsc/reporters/NoReporter.scala
  src/compiler/scala/tools/nsc/reporters/Reporter.scala
  src/compiler/scala/tools/nsc/reporters/StoreReporter.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/reflect/package.scala
  src/interactive/scala/tools/nsc/interactive/InteractiveReporter.scala
  src/partest/scala/tools/partest/nest/DirectCompiler.scala
  src/reflect/scala/reflect/internal/Reporting.scala
  src/reflect/scala/reflect/internal/util/CodeAction.scala
  src/reflect/scala/reflect/runtime/JavaUniverse.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/Reporter.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/Scripted.scala
  test/files/presentation/t12308.check
  test/files/run/maxerrs.scala
  test/junit/scala/tools/nsc/async/AnnotationDrivenAsyncTest.scala
  test/junit/scala/tools/nsc/reporters/AbstractCodeActionTest.scala
  test/junit/scala/tools/nsc/reporters/CodeActionTest.scala
  test/junit/scala/tools/nsc/reporters/CodeActionXsource3Test.scala
  test/junit/scala/tools/nsc/reporters/ConsoleReporterTest.scala
  test/junit/scala/tools/nsc/reporters/PositionFilterTest.scala
  test/junit/scala/tools/nsc/reporters/WConfTest.scala
  test/junit/scala/tools/nsc/symtab/SymbolTableForUnitTesting.scala
Labels: release-notes, prio:hi

#10405 Partest recognizes using
  src/partest/scala/tools/partest/nest/Runner.scala
  test/files/neg/check-dead.scala
  test/files/neg/t10701.check
  test/files/neg/t10701/Test.java
  test/files/neg/t10806.check
  test/files/neg/t10806.scala
  test/files/neg/t3098/a.scala
  test/files/neg/using-source3.check
  test/files/neg/using-source3.scala
  test/files/neg/using-source3b.check
  test/files/neg/using-source3b.scala
  test/files/pos/t6047.scala
  test/files/run/reflect-java-param-names/J_1.java
  test/files/run/synchronized.scala
  test/files/run/t10231/A_1.java
  test/files/run/t10450/A.java
  test/files/run/t10699/A_1.java
  test/files/run/t7198.scala
  test/files/run/t7634.scala
Labels: internal

#10460 [backport] Simplify macro exception stack handling
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  test/files/neg/macro-invalidret.check
Labels: internal

#10459 scala-xml 2.2.0 (was 2.1.0)
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: release-notes

#10461 Fix test directive syntax so test passes on Windows
  test/files/run/t9915/C_1.java
Labels: internal

#10463 fix a checkfile on JDK 20+
  test/files/neg/macro-exception.check
Labels: internal

#10465 sbt 1.9.2 (was .1)
  project/build.properties
Labels: internal

#10453 Update scala3-compiler_3, ... to 3.3.1-RC4
  project/DottySupport.scala
Labels: internal

#10467 Merge 2.12 to 2.13 [ci: last-only]
  project/build.properties
Labels: internal

#10473 Add disclaimer to fatal warnings
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  test/files/neg/deprecate_package_object_extends.check
  test/files/neg/dotless-targs-a.check
  test/files/neg/dotless-targs-b.check
  test/files/neg/for-comprehension-val.check
  test/files/neg/nested-class-shadowing-removal.check
  test/files/neg/parens-for-params.check
  test/files/neg/t12798.check
  test/files/neg/t12798b.check
  test/files/neg/t12816.check
  test/files/neg/t12816b.check
  test/files/neg/t5265b.check
  test/files/neg/t5606.check
  test/files/neg/view-bounds-removal.check
  test/files/neg/wconfSource1.check
  test/files/neg/wconfSource2.check
  test/junit/scala/tools/nsc/reporters/WConfTest.scala
Labels: release-notes, prio:hi

#10462 Re-enable new ambiguity warning under 2.13
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/StdAttachments.scala
  test/files/neg/t11921-alias.check
  test/files/neg/t11921.check
  test/files/neg/t11921b.check
  test/files/neg/t12816.check
  test/files/neg/t12816b.check
  test/files/neg/using-source3.check
  test/files/neg/using-source3b.check
  test/junit/scala/tools/nsc/reporters/AbstractCodeActionTest.scala
Labels: release-notes, prio:hi

#9350 Invoke javac from REPL paste [ci: last-only]
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/JavacTool.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/JavapClass.scala
  test/files/run/t10655.check
  test/files/run/t10655.scala
Labels: release-notes

#10477 Update sbt-mima-plugin to 1.1.3 in 2.12.x
  project/plugins.sbt
Labels: internal

#10478 update checkfiles (fix semantic merge conflict)
  test/files/neg/t11921-alias.check
  test/files/neg/t11921.check
  test/files/neg/t11921b.check
  test/files/neg/t12816.check
  test/files/neg/t12816b.check
  test/files/neg/using-source3.check
  test/files/neg/using-source3b.check
Labels: internal
