Repository scala/scala, pull requests merged in 2024-02, with the labels that each got.

#10648 Accommodate case companion as function
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/compiler/scala/tools/nsc/typechecker/Unapplies.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/neg/t3664.check
  test/files/neg/t3664.scala
  test/files/neg/t3664b.check
  test/files/neg/t3664b.scala
  test/files/neg/t3664c.check
  test/files/neg/t3664c.scala
  test/files/pos/t3664.scala
  test/files/run/t3664.check
  test/files/run/t3664.scala
Labels: release-notes

#10684 Fix signature of HashSet.subsetOf
  src/library/scala/collection/immutable/HashSet.scala
Labels: library:collections

#10685 Don't include `inPackagePrefix` in ImplicitInfo equality
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
Labels: prio:blocker

#10688 Disable tasty pipelining tests on windows
  test/tasty/test/scala/tools/tastytest/TastyTestJUnit.scala
Labels: internal

#10695 fix `scala` task in our sbt build so REPL has JLine features again
  build.sbt
Labels: tool:REPL, internal

#10698 re-STARR onto 2.12.19
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#10697 re-STARR onto 2.13.13
  build.sbt
  project/MimaFilters.scala
  versions.properties
Labels: internal

#10699 sbt 1.9.9 (was .8)
  .travis.yml
  project/build.properties
  scripts/common
Labels: internal

#10701 Merge 2.12.x to 2.13.x [ci: last-only]
  .travis.yml
  build.sbt
  project/build.properties
  scripts/common
Labels: internal

#10700 ".tasty" files are no longer considered source files of a symbol.
  build.sbt
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/reflect/scala/reflect/internal/Symbols.scala
  src/tastytest/scala/tools/tastytest/Scaladoc.scala
  src/tastytest/scala/tools/tastytest/TastyTest.scala
  test/tasty/pos-doctool/src-2/app/Main.scala
  test/tasty/pos-doctool/src-3/testlib/ADT.scala
  test/tasty/test/scala/tools/tastytest/TastyTestJUnit.scala
Labels: prio:blocker
