Repository scala/scala, pull requests merged in 2024-04, with the labels that each got.

#10721 Avoid NoPosition.start in Scaladoc warning
  src/compiler/scala/tools/nsc/ast/DocComments.scala
Labels: prio:hi

#10722 Defer array resize on empty
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
  test/junit/scala/collection/mutable/ArrayBuilderTest.scala
Labels: prio:blocker, library:collections

#10714 Include library-aux sources in library sources jar
  build.sbt
Labels: release-notes, prio:hi

#10733 Don't process ignored escapes for raw
  src/compiler/scala/tools/reflect/FastStringInterpolator.scala
  test/files/pos/t12976.scala
Labels: release-notes

#10716 Remove SHELLOPTS=vi and -Xjline support, reinstate -Xnojline
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/manual/scala/man1/scalac.scala
  src/partest/scala/tools/partest/ReplTest.scala
  src/repl-frontend/scala/tools/nsc/interpreter/jline/Reader.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ShellConfig.scala
  test/files/run/type-tag-leak.scala
  test/junit/scala/tools/nsc/interpreter/CompletionTest.scala
  test/macro-annot/run/repl/repl_2.scala
Labels: release-notes

#10704 Rename `-Xlint:named-booleans` to `-Wunnamed-boolean-literal` (and no longer include it in `-Xlint`)
  build.sbt
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/StdNames.scala
  test/files/neg/named-booleans-relaxed.check
  test/files/neg/named-booleans-relaxed.scala
  test/files/neg/named-booleans.check
  test/files/neg/named-booleans.scala
  test/files/neg/warn-unused-locals.scala
  test/junit/scala/tools/nsc/QuickfixTest.scala
Labels: release-notes, prio:hi

#10696 in Scaladoc, be clearer that `asInstanceOf` is unsafe (and platform-dependent)
  .gitignore
  src/library-aux/scala/Any.scala
Labels: documentation

#10741 Update scala3-compiler_3, ... to 3.4.1
  project/DottySupport.scala
Labels: internal

#10746 merge 2.12 to 2.13 20240409 [ci: last-only]
  .github/workflows/ci.yml
  project/project/plugins.sbt
Labels: prio:hi, internal

#10748 silence some warnings in test code
  src/partest/scala/tools/partest/nest/StreamCapture.scala
  test/scalacheck/scala/reflect/quasiquotes/TermConstructionProps.scala
  test/tasty/test/scala/tools/tastytest/TastyTestJUnit.scala
Labels: internal

#10753 Move terminal test to properties
  project/MimaFilters.scala
  src/library/scala/util/Properties.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ShellConfig.scala
  test/files/neg/t6323a.scala
Labels: internal

#10755 Align WConf category for WFlagUnnamedBooleanLiteral
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/typechecker/RefChecks.scala
Labels: internal
