Repository scala/scala, pull requests merged in 2024-08, with the labels that each got.

#10825 merge 2.12 to 2.13 20240805 [ci: last-only]
  SECURITY.md
  build.sbt
  project/plugins.sbt
  src/compiler/scala/tools/nsc/transform/Erasure.scala
Labels: prio:hi, internal

#10802 One-only parallel instance for sbt-test
  build.sbt
Labels: internal

#10815 Reduce unused parameters in parser
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
Labels: internal

#10826 Prevent cross-talk in scripted tests when running multiple builds
  build.sbt
  project/ScriptCommands.scala
  project/VersionUtil.scala
Labels: internal

#10827 JLine 3.26.3 (was 3.25.1)
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: release-notes, prio:hi

#10816 Fix infinite loop bug in the mutable LongMap
  src/library/scala/collection/mutable/LongMap.scala
  test/junit/scala/collection/mutable/LongMapTest.scala
Labels: prio:hi

#10744 Support JDK 23 in optimizer (via upgrade to patched ASM 9.7.0)
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/ProdConsAnalyzer.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: release-notes

#10833 Augment regression test for bugs 9244+11558 [ci: last-only]
  CONTRIBUTING.md
  test/files/pos/t11558.scala
Labels: internal

#10840 Regression test for bug 10532
  test/files/pos/t10532/C.java
  test/files/pos/t10532/D.scala
  test/files/pos/t10532/test.scala
Labels: internal

#10841 Update scala3-compiler_3, ... to 3.5.1-RC2
  project/DottySupport.scala
Labels: prio:blocker, internal

#10818 Improve `LazyList` self-reference error
  src/library/scala/collection/immutable/LazyList.scala
  test/junit/scala/collection/immutable/LazyListTest.scala
Labels: library:collections

#10747 [nomerge] Support JDK 23 in optimizer (via upgrade to patched ASM 9.7.0)
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/ProdConsAnalyzerImpl.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  test/junit/scala/tools/nsc/settings/TargetTest.scala
  versions.properties
Labels: release-notes

#10837 Update commons-lang3 to 3.16.0 in 2.12.x
  project/plugins.sbt
Labels: internal

#10836 Update sbt-mima-plugin to 1.1.4 in 2.12.x
  project/plugins.sbt
Labels: internal

#10838 Wrap AnnotatedType toString in parens if underlying is infix
  src/reflect/scala/reflect/internal/Types.scala
  test/files/run/annot-infix-tostr.check
  test/files/run/annot-infix-tostr.scala
Labels: internal

#10829 chore: fix some comments
  test/async/jvm/toughtype.scala
  test/files/bench/equality/eqeq.eqlog
  test/junit/scala/tools/nsc/backend/jvm/BytecodeTest.scala
Labels: internal

#10847 New reference compiler is Scala 2.13.15-M1
  versions.properties
Labels: internal

#10801 Support alternative JVM system images (via `-system`, like javac)
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/compiler/scala/tools/util/PathResolver.scala
  test/junit/scala/tools/nsc/classpath/JrtClassPathTest.scala
Labels: release-notes
