Repository scala/scala, pull requests merged in 2024-12, with the labels that each got.

#10945 Update sbt, scripted-plugin to 1.10.6 in 2.12.x
  project/build.properties
Labels: internal

#10944 Update jackson-module-scala to 2.18.2 in 2.12.x
  build.sbt
Labels: internal

#10946 TASTy reader: Scala 3.6.2 (was .1)
  project/DottySupport.scala
Labels: internal

#10948 Update compiler-interface to 1.10.5
  build.sbt
Labels: internal

#10936 Regression test improved XML does not warn
  src/testkit/scala/tools/testkit/BytecodeTesting.scala
  src/testkit/scala/tools/testkit/XMLTesting.scala
  test/junit/scala/tools/nsc/parser/ParserTest.scala
  test/junit/scala/tools/nsc/typechecker/XMLTest.scala
Labels: internal

#10954 use GitHub Actions for CLA check
  .github/workflows/cla.yml
Labels: internal

#10956 Merge 2.12.x to 2.13.x [ci: last-only]
  .github/workflows/cla.yml
  project/build.properties
  project/project/plugins.sbt
Labels: internal

#10881 Scaladoc: under `-release`, fix generation of links to JVM classes
  src/scaladoc/scala/tools/nsc/doc/model/MemberLookup.scala
Labels: welcome

#10958 ArrayBuilder of Unit needs addAll forwarded
  src/library/scala/collection/immutable/HashMap.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayBuilder.scala
  test/junit/scala/collection/mutable/ArrayBuilderTest.scala
Labels: library:collections

#10888 Upgrade to asm 9.7.1, for JDK24 support
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: release-notes

#10961 no more Travis-CI for PR validation, use GitHub Actions
  .github/workflows/merge.yml
  .github/workflows/validate.yml
  .travis.yml
Labels: internal

#10964 Fix `NoClassDefFoundError` when using old zinc version [ci: last-only]
  src/sbt-bridge/scala/tools/xsbt/CallbackGlobal.scala
Labels: prio:hi, internal

#10969 Update sbt, scripted-plugin to 1.10.7 in 2.12.x
  project/build.properties
Labels: internal

#10967 Update compiler-interface to 1.10.7
  build.sbt
Labels: internal
