Repository scala/scala, pull requests merged in 2024-01, with the labels that each got.

#10649 Consolidate tests
  test/files/run/array-cleanup-optimation-specialized.scala
  test/files/run/sd760a.scala
  test/files/run/sd760b.scala
Labels: internal

#10644 Allow module lookup from Java
  src/compiler/scala/tools/nsc/typechecker/Contexts.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/reflect/scala/reflect/internal/Names.scala
  test/files/run/t9714/J.java
  test/files/run/t9714/Module.scala
Labels: release-notes

#10647 Correct position of import selector rename [ci: last-only]
  src/compiler/scala/tools/nsc/ast/parser/Parsers.scala
  test/files/neg/t12813.check
  test/files/neg/t12813b.check
  test/files/neg/t12813c.check
  test/files/neg/t12813c.scala
Labels: prio:hi

#10655 Additional non-essential tweaks [ci: last-only]
  src/compiler/scala/reflect/reify/utils/Extractors.scala
  src/compiler/scala/tools/nsc/transform/SpecializeTypes.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/compiler/scala/tools/nsc/util/DocStrings.scala
  src/compiler/scala/tools/tasty/Signature.scala
  src/interactive/scala/tools/nsc/interactive/Global.scala
  src/reflect/scala/reflect/internal/SymbolTable.scala
  src/reflect/scala/reflect/internal/util/WeakHashSet.scala
  src/repl/scala/tools/nsc/interpreter/IMain.scala
Labels: internal

#10656 SIP 42 Binary literals finds acceptance
  spec/01-lexical-syntax.md
  spec/13-syntax-summary.md
  src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
  test/files/run/literals.check
  test/files/run/literals.scala
Labels: release-notes

#10664 Update jackson-module-scala to 2.16.1 in 2.12.x
  build.sbt
Labels: internal

#10653 Bump copyright year to 2024
  NOTICE
  doc/LICENSE.md
  doc/License.rtf
  project/VersionUtil.scala
  src/library/scala/util/Properties.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  src/scalap/decoder.properties
Labels: prio:blocker, documentation

#10666 Update sbt-jmh to 0.4.7 in 2.12.x
  project/plugins.sbt
Labels: internal

#10661 Update compiler-interface to 1.9.6
  build.sbt
Labels: internal

#10379 [backport] InterruptedException handling for Futures
  src/library/scala/concurrent/impl/Promise.scala
  test/benchmarks/src/main/scala/scala/concurrent/FutureBenchmark.scala
  test/files/jvm/future-spec/FutureTests.scala
  test/files/jvm/future-spec/PromiseTests.scala
  test/files/jvm/future-spec/main.scala
  test/files/jvm/scala-concurrent-tck.check
  test/files/jvm/scala-concurrent-tck.scala
Labels: release-notes, library:concurrent

#10632 Fix rare `NullPointerException` in some tree-based collections (by fixing `RedBlackTree.doFrom`)
  src/library/scala/collection/immutable/RedBlackTree.scala
  test/junit/scala/collection/immutable/SortedSetTest.scala
  test/scalacheck/redblacktree.scala
Labels: prio:hi, library:collections

#10640 [backport] Fix RedBlackTree.doFrom / doTo / doUntil
  src/library/scala/collection/immutable/RedBlackTree.scala
  test/junit/scala/collection/immutable/SortedSetTest.scala
  test/scalacheck/redblacktree.scala
Labels: library:collections

#10665 Update sbt to 1.9.8 in 2.12.x
  .travis.yml
  project/build.properties
  scripts/common
Labels: internal

#10668 Remove no-longer-needed JDK 21 workaround in build
  .travis.yml
  scripts/common
Labels: internal

#10627 Add indexOf() and lastIndexOf() to NumericRange.
  src/library/scala/collection/immutable/NumericRange.scala
  test/junit/scala/collection/immutable/NumericRangeTest.scala
Labels: library:collections

#10638 [nomerge] Tweak help for -target for 2.12 restriction only
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
Labels: documentation

#10543 `-Yrelease` supplements `--release`, allows access to additional JVM packages
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/util/PathResolver.scala
  test/files/neg/unsafe.check
  test/files/neg/unsafe.scala
  test/files/pos/unsafe.scala
  test/junit/scala/tools/nsc/classpath/JrtClassPathTest.scala
Labels: release-notes

#10671 [backport] `-Yrelease` supplements `--release`, allows access to additional JVM packages
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/classpath/DirectoryClassPath.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/compiler/scala/tools/util/PathResolver.scala
  src/repl/scala/tools/nsc/interpreter/ReplGlobal.scala
  test/files/neg/unsafe.check
  test/files/neg/unsafe.scala
  test/files/pos/unsafe.scala
  test/junit/scala/tools/nsc/classpath/JrtClassPathTest.scala
Labels: release-notes

#10675 Classfile reader: allow `CONSTANT_Dynamic` in constant pool
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/reflect/scala/reflect/internal/ClassfileConstants.scala
  test/files/pos/t12396/A_1.java
  test/files/pos/t12396/B_2.scala
  test/junit/scala/tools/nsc/backend/jvm/ClassfileParserTest.scala
Labels: prio:blocker

#10676 Merge 2.12. to 2.13 [ci: last-only]
  .travis.yml
  scripts/common
  src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala
  src/reflect/scala/reflect/internal/ClassfileConstants.scala
  test/files/pos/t12396/A_1.java
  test/files/pos/t12396/B_2.scala
  test/junit/scala/tools/nsc/backend/jvm/ClassfileParserTest.scala
Labels: release-notes, prio:blocker

#10624 Specify behavior of folds and reduces when operator is not associative or collection is unordered
  src/library/scala/collection/ArrayOps.scala
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/StringOps.scala
Labels: library:collections, documentation
