Repository scala/scala, pull requests merged in 2025-02, with the labels that each got.

#10907 Unexpected eta expansion is behind -Xsource-features:eta-expand-always
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/typechecker/ContextErrors.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  test/files/neg/t13055.check
  test/files/neg/t13055.scala
  test/files/neg/t7187-3.scala
  test/files/neg/t7187-deprecation.scala
  test/files/pos/t13055.scala
  test/files/run/t3664.scala
Labels: release-notes

#10976 Fix AnnotationInfo when using named/default arguments, support custom annotation subclasses
  project/MimaFilters.scala
  src/compiler/scala/tools/nsc/symtab/classfile/Pickler.scala
  src/compiler/scala/tools/nsc/typechecker/NamesDefaults.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/library/scala/annotation/meta/defaultArg.scala
  src/library/scala/annotation/meta/superArg.scala
  src/reflect/scala/reflect/internal/AnnotationInfos.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/internal/Mode.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/neg/annots-constant-neg.check
  test/files/neg/annots-constant-neg/Test.scala
  test/files/neg/nowarnRangePos.check
  test/files/neg/nowarnRangePos.scala
  test/files/run/sd884.check
  test/files/run/sd884.scala
  test/files/run/sd884b.check
  test/files/run/sd884b/A.scala
  test/files/run/sd884b/Test_1.scala
Labels: release-notes

#10994 Move Future.onCompleteWithUnregister out of the Future API
  project/MimaFilters.scala
  src/library/scala/concurrent/Future.scala
  src/library/scala/concurrent/impl/Promise.scala
Labels: release-notes

#10997 Revert "Do not expand lambdas used in super constructor calls."
  src/compiler/scala/tools/nsc/transform/UnCurry.scala
  test/files/neg/t10035.check
  test/files/neg/t10035.scala
  test/files/pos/t10035.scala
  test/files/run/lambda-in-constructor.scala
Labels: internal

#10950 Update JLine to 3.29.0
  src/intellij/scala.ipr.SAMPLE
  versions.properties
Labels: release-notes, tool:REPL

#10999 Remove empty check
  test/files/run/t8442.check
  test/files/run/t8442/Test.scala
Labels: internal

#10990 Boost LazyList Scaladoc just a bit
  src/library/scala/collection/immutable/LazyList.scala
Labels: documentation

#10992 add documentation for Iterator.indexWhere
  src/library/scala/collection/Iterator.scala
Labels: library:collections, documentation

#11002 minor updates to our development docs
  CONTRIBUTING.md
  README.md
Labels: documentation, internal

#11003 Prevent NPE in recursive implicit lint
  src/compiler/scala/tools/nsc/typechecker/Implicits.scala
  test/files/neg/t12226.check
  test/files/neg/t12226.scala
Labels: internal
