Repository scala/scala, pull requests merged in 2025-01, with the labels that each got.

#10973 bump copyright year to 2025
  NOTICE
  doc/LICENSE.md
  doc/License.rtf
  project/VersionUtil.scala
  src/library/scala/util/Properties.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  src/scalap/decoder.properties
Labels: documentation

#10966 correctly fix `NoClassDefFoundError` in sbt bridge
  src/sbt-bridge/scala/tools/xsbt/CallbackGlobal.scala
  test/junit/scala/tools/xsbt/TestCallback.scala
Labels: prio:blocker, internal

#10970 [nomerge] Upgrade to asm 9.7.1, for JDK24 support
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  test/junit/scala/tools/nsc/settings/TargetTest.scala
  versions.properties
Labels: prio:hi

#10974 merge 2.12 to 2.13 20250106 [ci:last-only]
  NOTICE
  doc/LICENSE.md
  doc/License.rtf
  project/VersionUtil.scala
  project/build.properties
  src/library/scala/util/Properties.scala
  src/scaladoc/scala/tools/nsc/doc/html/page/Entity.scala
  src/scalap/decoder.properties
Labels: prio:blocker, internal

#10978 no more Travis-CI for PR validation, use GitHub Actions [forward port]
  .github/workflows/ci.yml
  .github/workflows/validate.yml
  .travis.yml
Labels: internal

#10962 Improve Array.copy performance
  src/library/scala/Array.scala
  test/benchmarks/src/main/scala/scala/collection/mutable/ArrayBufferBenchmark.scala
Labels: library:collections

#10979 REPL: on Windows, allow default `-Dscala.color=auto` to show colors
  build.sbt
  src/library/scala/util/Properties.scala
Labels: release-notes, tool:REPL

#10984 Update scala3-compiler_3, ... to 3.6.3
  project/DottySupport.scala
Labels: internal

#10981 improve ArrayBuffer.addOne performance
  src/library/scala/collection/mutable/ArrayBuffer.scala
  test/benchmarks/src/main/scala/scala/collection/mutable/ArrayBufferBenchmark.scala
Labels: library:collections

#10985 Show nowarn / Wconf filters for a warning with @nowarn("verbose")
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/library/scala/annotation/nowarn.scala
  test/files/neg/nowarnRangePos.check
  test/files/neg/nowarnRangePos.scala
Labels: release-notes

#10942 Lint inferred structural types
  src/compiler/scala/reflect/reify/phases/Calculate.scala
  src/compiler/scala/reflect/reify/phases/Metalevels.scala
  src/compiler/scala/reflect/reify/phases/Reshape.scala
  src/compiler/scala/tools/nsc/Global.scala
  src/compiler/scala/tools/nsc/Reporting.scala
  src/compiler/scala/tools/nsc/settings/ScalaSettings.scala
  src/compiler/scala/tools/nsc/settings/Warnings.scala
  src/compiler/scala/tools/nsc/transform/Erasure.scala
  src/compiler/scala/tools/nsc/transform/async/ExprBuilder.scala
  src/compiler/scala/tools/nsc/typechecker/Namers.scala
  src/compiler/scala/tools/nsc/typechecker/TypeDiagnostics.scala
  src/compiler/scala/tools/nsc/typechecker/Typers.scala
  src/interactive/scala/tools/nsc/interactive/Pickler.scala
  src/library/scala/collection/Seq.scala
  src/library/scala/runtime/ModuleSerializationProxy.scala
  src/repl-frontend/scala/tools/nsc/interpreter/shell/ILoop.scala
  test/files/neg/inferred-structural-3.check
  test/files/neg/inferred-structural-3.scala
  test/files/neg/lint-inferred-structural.check
  test/files/neg/lint-inferred-structural.scala
  test/files/neg/t11921-alias.check
  test/files/neg/t11921b.scala
  test/files/pos/t11921b.scala
  test/files/pos/t12647/Resolve_2.scala
  test/files/run/inferred-structural-3.check
  test/files/run/inferred-structural-3.scala
  test/files/run/names-defaults.check
Labels: release-notes

#10937 Reduce memory footprint of evaluated values in LazyList
  project/MimaFilters.scala
  src/library/scala/collection/IterableOnce.scala
  src/library/scala/collection/immutable/LazyList.scala
  test/junit/scala/collection/Sizes.scala
  test/junit/scala/collection/immutable/LazyListGCTest.scala
  test/junit/scala/collection/immutable/LazyListTest.scala
Labels: release-notes, performance, library:collections

#10965 Remove scaladoc CSS ruleset making inherited text white on light background
  src/scaladoc/scala/tools/nsc/doc/html/resource/lib/template.css
Labels: tool:scaladoc
