Repository scala/scala, pull requests merged in 2025-04, with the labels that each got.

#11023 Mix in the `productPrefix` hash statically in case class `hashCode`
  src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala
  src/library/scala/runtime/ScalaRunTime.scala
  src/library/scala/util/hashing/MurmurHash3.scala
  src/reflect/scala/reflect/internal/Definitions.scala
  src/reflect/scala/reflect/runtime/JavaUniverseForce.scala
  test/files/run/caseClassHash.scala
  test/files/run/idempotency-case-classes.check
  test/files/run/macroPlugins-namerHooks.check
  test/files/run/t13033.scala
Labels: release-notes

#11000 Improve `s.u.Using` suppression order
  src/library/scala/util/Using.scala
  test/junit/scala/util/UsingTest.scala
Labels: library:base

#11029 A fast sliding iterator for IndexedSeqs
  project/MimaFilters.scala
  src/library/scala/collection/IndexedSeq.scala
  src/library/scala/collection/mutable/ArrayBuffer.scala
  src/library/scala/collection/mutable/ArrayDeque.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/ArraySeqBenchmark.scala
  test/benchmarks/src/main/scala/scala/collection/immutable/VectorBenchmark2.scala
  test/junit/scala/collection/mutable/ArrayBufferTest.scala
  test/junit/scala/collection/mutable/ArrayDequeTest.scala
  test/junit/scala/collection/mutable/ListBufferTest.scala
Labels: library:collections

#11040 Update Option examples to more modern style
  src/library/scala/Option.scala
Labels: documentation

#11028 [2.12.x] Upgrade asm for JDK25 support
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  test/junit/scala/tools/nsc/settings/TargetTest.scala
  versions.properties
Labels: release-notes, prio:hi

#11022 CI: mergelies: drop JDK 23, add JDK 24
  .github/workflows/merge.yml
  build.sbt
  src/partest/scala/tools/partest/nest/Runner.scala
  src/partest/scala/tools/partest/nest/TrapExit.scala
  test/files/jvm/non-fatal-tests.scala
  test/files/jvm/scala-concurrent-tck.scala
  test/files/jvm/try-type-tests.scala
  test/files/jvm/unreachable/Foo_1.check
Labels: internal

#11042 New reference compiler is 2.12.21-M2 (for JDK 25)
  .github/workflows/merge.yml
  versions.properties
Labels: internal

#11044 Fix JDK 24+ by removing more exit calls
  test/files/pos/t7591/Demo.scala
  test/files/presentation/random/src/Random.scala
  test/files/run/fail-non-value-types.scala
  test/files/run/verify-ctor.scala
Labels: internal

#11045 Adapt run/indyLambdaKinds.check to Java 24
  test/files/run/indyLambdaKinds.check
Labels: internal

#11043 Merge 2.12 to 2.13 for JDK 25 [ci: last-only]
  .github/workflows/ci.yml
  build.sbt
  project/ScalaOptionParser.scala
  src/compiler/scala/tools/nsc/backend/jvm/analysis/BackendUtils.scala
  src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala
  src/intellij/scala.ipr.SAMPLE
  src/partest/scala/tools/partest/nest/Runner.scala
  src/partest/scala/tools/partest/nest/TrapExit.scala
  test/files/jvm/non-fatal-tests.scala
  test/files/jvm/scala-concurrent-tck-b.scala
  test/files/jvm/scala-concurrent-tck.scala
  test/files/pos/t7591/Demo.scala
  test/files/presentation/random/src/Random.scala
  test/files/run/fail-non-value-types.scala
  test/files/run/indyLambdaKinds.check
  test/files/run/verify-ctor.scala
  versions.properties
Labels: internal

#11038 Update sbt-develocity to 1.2 in 2.12.x
  project/plugins.sbt
Labels: internal
